SET NAMES utf8;

UPDATE `script_texts` SET `content_loc2` = 'Que se déroule les anneaux de la haine' WHERE `sound` = 8421;
UPDATE `script_texts` SET `content_loc2` = 'Soyez béni mortels pour m\'avoir libérée. Hakkar ne me controle plus.' WHERE `sound` = 8423;
UPDATE `script_texts` SET `content_loc2` = 'Shirvallah ! Que ta rage m\'envahisse' WHERE `sound` = 8419;
UPDATE `script_texts` SET `content_loc2` = 'Hakkar ne me domine plus. Je connais enfin la paix' WHERE `sound` = 8424;
UPDATE `script_texts` SET `content_loc2` = 'Enfin la mort ! Soit maudit Hakkar ! Soit maudit !' WHERE `sound` = 8422;
UPDATE `script_texts` SET `content_loc2` = 'Entraine moi dans ta toile dame Shadra ! Déchaine ton venin' WHERE `sound` = 8418;
UPDATE `script_texts` SET `content_loc2` = 'Bethekk, ta prêtresse en appelle à ta puissance !' WHERE `sound` = 8416;
UPDATE `script_texts` SET `content_loc2` = 'Enfin ! Je suis enfin libérée de l\'Ecorcheur d\Âme ' WHERE `sound` = 8412;
UPDATE `script_texts` SET `content_loc2` = 'Je jetterais vos âmes en pature à Hakkar lui même' WHERE `sound` = 8413;
UPDATE `script_texts` SET `content_loc2` = 'L\'orgueil annonce la fin de votre monde ! Avancez mortels ! Affrontez la colère de l\'Ecorcheur d\Âme !' WHERE `sound` = 8414;
UPDATE `script_texts` SET `content_loc2` = 'Bienvenue à ce grand spectacle mes amis, approchez et mourez' WHERE `sound` = 8425;
UPDATE `script_texts` SET `content_loc2` = 'Imprudents mortels nul ne défie les fils de la flamme vivante' WHERE `sound` = 8035;
UPDATE `script_texts` SET `content_loc2` = 'Brulez mortels ! Brulez pour ce sacrilège !' WHERE `sound` = 8036;
UPDATE `script_texts` SET `content_loc2` = 'Des cendres aux cendres.' WHERE `sound` = 8037;
UPDATE `script_texts` SET `content_loc2` = 'Impossible..retenez vos coups mortels ! Je me rends... Je me rends ! Vous regretterez bientôt votre témérité. Je vais aller invoquer le seigneur de ces lieux.Si vous désirez obtenir audience, sachez  que vos misérables vies seront anéanties. Mais partez à sa recherche si vous l\'osez.' WHERE `sound` = 8038;
UPDATE `script_texts` SET `content_loc2` = 'Les runes de gardes ont été détruites ! Traquez les infidèles mes frères.' WHERE `sound` = 8039;
UPDATE `script_texts` SET `content_loc2` = 'Contemplez Ragnaros, le Seigneur du Feu ! Celui qui était ancien alors que le monde était jeune. Inclinez-vous devant lui mortels ! Inclinez-vous devant votre mort !' WHERE `sound` = 8040;
UPDATE `script_texts` SET `content_loc2` = 'Seigneurs ! Ces mortels infidèles ont envahis votre sanctuaire et voulaient voler vos secrets.' WHERE `sound` = 8041;
UPDATE `script_texts` SET `content_loc2` = 'Tu m\'as réveillé trop tôt Exécutus....Que signifie cette intrusion !' WHERE `sound` = 8043;
UPDATE `script_texts` SET `content_loc2` = 'Idiot ! Tu as laissé ces insectes ramper à travers ce noyau sacré ! Et tu les as conduit dans mon repaire ! Tu as échoué Exécutus ! Justice sera faites en vérité !' WHERE `sound` = 8044;
UPDATE `script_texts` SET `content_loc2` = 'A votre tour insecte ! Vous vouliez connaître le pouvoir de Ragnaros. Vous allez le découvrir !' WHERE `sound` = 8045;
UPDATE `script_texts` SET `content_loc2` = 'Par le feu ! Soyez purifié !' WHERE `sound` = 8046;
UPDATE `script_texts` SET `content_loc2` = 'Gouttez aux flammes de Sulfuron !' WHERE `sound` = 8047;
UPDATE `script_texts` SET `content_loc2` = 'Ma patience s\'épuise...Venez vous faire tuer moucherons !' WHERE `sound` = 8048;
UPDATE `script_texts` SET `content_loc2` = 'Venez  ! Ô mes serviteurs !' WHERE `sound` = 8049;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne pouvez pas défaire la Flamme Vivante. Venez suppots du feu ! Venez créature de la haine ! Votre maître vous appelle !' WHERE `sound` = 8050;
UPDATE `script_texts` SET `content_loc2` = 'Meurs insecte !' WHERE `sound` = 8051;
UPDATE `script_texts` SET `content_loc2` = 'Je reprends des forces' WHERE `sound` = 8593;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai échoué' WHERE `sound` = 8594;
UPDATE `script_texts` SET `content_loc2` = 'Mes pouvoirs reviennent' WHERE `sound` = 8595;
UPDATE `script_texts` SET `content_loc2` = 'Mes pouvoirs sont de retour' WHERE `sound` = 8596;
UPDATE `script_texts` SET `content_loc2` = 'Protégez la ville à tout prix !' WHERE `sound` = 8597;
UPDATE `script_texts` SET `content_loc2` = 'Sables du désert à moi ! Cachez le soleil !' WHERE `sound` = 8598;
UPDATE `script_texts` SET `content_loc2` = 'Ils ont franchis les murs' WHERE `sound` = 8599;
UPDATE `script_texts` SET `content_loc2` = 'A vos postes ! Défendez la ville !' WHERE `sound` = 8600;
UPDATE `script_texts` SET `content_loc2` = 'Les intrus seront liquidés !' WHERE `sound` = 8601;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez été liquidés' WHERE `sound` = 8602;
UPDATE `script_texts` SET `content_loc2` = 'A l\'attaque ! Qu\'ils payent !' WHERE `sound` = 8603;
UPDATE `script_texts` SET `content_loc2` = 'Exalte ton dernier souffle !' WHERE `sound` = 8604;
UPDATE `script_texts` SET `content_loc2` = 'Ecrasez les ! Chassez les !' WHERE `sound` = 8605;
UPDATE `script_texts` SET `content_loc2` = 'Détruisez les ! N\'hésitez pas !' WHERE `sound` = 8606;
UPDATE `script_texts` SET `content_loc2` = 'Fandral ! Ton heure est venue ! Va te cacher dans le rêve d\'Emeraude et prie pour que nous ne te trouvions jamais !' WHERE `sound` = 8607;
UPDATE `script_texts` SET `content_loc2` = 'La peur est pour l\'ennemie ! La peur est la mort !' WHERE `sound` = 8608;
UPDATE `script_texts` SET `content_loc2` = 'Imbécile imprudent ! Je vais te tuer moi même' WHERE `sound` = 8609;
UPDATE `script_texts` SET `content_loc2` = 'C\'en est fini d\'attendre derrière des portes fermées et des murs de pierre. Nous ne serons pas privés de notre vengeance. Les dragons eux-mêmes trembleront devant notre courroux !' WHERE `sound` = 8610;
UPDATE `script_texts` SET `content_loc2` = 'Forte-ramure pleurnichera pour avoir la vie sauve, comme la fait son morveux de fils. En ce jour mille an d\'injustice s\'achève' WHERE `sound` = 8611;
UPDATE `script_texts` SET `content_loc2` = 'L\'heure de notre vengeance sonne enfin ! Que les ténèbres règnent dans le coeur de nos ennemis' WHERE `sound` = 8612;
UPDATE `script_texts` SET `content_loc2` = 'Guerrier ! Capitaine ! Continuez le combat ! ' WHERE `sound` = 8613;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'ai pas de temps à perdre avec toi !' WHERE `sound` = 8614;
UPDATE `script_texts` SET `content_loc2` = 'Êtes-vous préssé de mourir ? Je serais heureux de vous rendre ce service' WHERE `sound` = 8615;
UPDATE `script_texts` SET `content_loc2` = 'Tremblez mortels ! L\âge des ténèbres arrive' WHERE `sound` = 8616;
UPDATE `script_texts` SET `content_loc2` = 'Puisse votre mort servir d\'exemple' WHERE `sound` = 8617;
UPDATE `script_texts` SET `content_loc2` = 'Préparez vous au retour des très anciens' WHERE `sound` = 8618;
UPDATE `script_texts` SET `content_loc2` = 'Méprisables laches ! Vous vous noierez dans des fleuves de sang !' WHERE `sound` = 8619;
UPDATE `script_texts` SET `content_loc2` = 'Les cris des mourants empliront les cieux ! Une symphonie de terreur commence' WHERE `sound` = 8620;
UPDATE `script_texts` SET `content_loc2` = 'Tremblez ! La fin arrive' WHERE `sound` = 8621;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne ferez que retarder l\'inévitable' WHERE `sound` = 8622;
UPDATE `script_texts` SET `content_loc2` = 'Vous serez jugé pour avoir profaner ces lieux sacrés' WHERE `sound` = 8646;
UPDATE `script_texts` SET `content_loc2` = 'Je vous condamne à mort' WHERE `sound` = 8647;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai servi....jusqu\'à la fin..' WHERE `sound` = 8648;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai toujours su qu\'un jour c\'est moi qui serait chassé ..' WHERE `sound` = 9165;
UPDATE `script_texts` SET `content_loc2` = 'Pour un guerrier aussi doué que moi, les armes sont optionnelles' WHERE `sound` = 9166;
UPDATE `script_texts` SET `content_loc2` = 'Crapules ! Lâches !' WHERE `sound` = 9167;
UPDATE `script_texts` SET `content_loc2` = 'Minuit viens à moi ! Dispersons ses misérables faquins' WHERE `sound` = 9168;
UPDATE `script_texts` SET `content_loc2` = 'C\'était...inévitable' WHERE `sound` = 9169;
UPDATE `script_texts` SET `content_loc2` = 'C\'est trop facile' WHERE `sound` = 9170;
UPDATE `script_texts` SET `content_loc2` = 'Bien joué Minuit !' WHERE `sound` = 9173;
UPDATE `script_texts` SET `content_loc2` = 'Comment pouvez vous ? Ce monde est cruel...cruel !' WHERE `sound` = 9178;
UPDATE `script_texts` SET `content_loc2` = 'Malheur à chaque d\'entre vous mes mignons !' WHERE `sound` = 9179;
UPDATE `script_texts` SET `content_loc2` = 'Je me suis bien occupé de vous hein ?' WHERE `sound` = 9180;
UPDATE `script_texts` SET `content_loc2` = 'L\'accès à la ménagerie est réservé aux invités' WHERE `sound` = 9183;
UPDATE `script_texts` SET `content_loc2` = 'Le conservateur n\'est plus opérationnel..' WHERE `sound` = 9184;
UPDATE `script_texts` SET `content_loc2` = 'Toute désobéissance entrainera une action offensive' WHERE `sound` = 9185;
UPDATE `script_texts` SET `content_loc2` = 'Impossible de traiter votre requête' WHERE `sound` = 9186;
UPDATE `script_texts` SET `content_loc2` = 'Ne touchez pas les vitrines' WHERE `sound` = 9187;
UPDATE `script_texts` SET `content_loc2` = 'Le règlement de la galerie sera strictement appliqué' WHERE `sound` = 9188;
UPDATE `script_texts` SET `content_loc2` = 'Enfin ! Enfin je peux rentrer chez moi !' WHERE `sound` = 9190;
UPDATE `script_texts` SET `content_loc2` = 'Ne les laisse pas nous faire du mal Tito. Tu ne le feras pas hein ?' WHERE `sound` = 9191;
UPDATE `script_texts` SET `content_loc2` = 'Tito ! Oh Tito ! Non ! ' WHERE `sound` = 9192;
UPDATE `script_texts` SET `content_loc2` = 'Oh Tito ! Nous devons trouver le moyen de rentrer à la maison. Le Vieux Sorcier est notre dernier espoir. Homme de paille, Graou, Tête de fer-blanc, vous voulez bien ? Oh attendez !Oh regardez nous avons des visiteurs. ' WHERE `sound` = 9195;
UPDATE `script_texts` SET `content_loc2` = 'Quel démon es-tu pour me tourmenter ainsi ?' WHERE `sound` = 9196;
UPDATE `script_texts` SET `content_loc2` = 'Romulo voici à boire. Je bois à toi !' WHERE `sound` = 9198;
UPDATE `script_texts` SET `content_loc2` = 'Ou est mon Seigneur ? Ou est mon Romulo ?' WHERE `sound` = 9199;
UPDATE `script_texts` SET `content_loc2` = 'Viens gentille nuit ! Rends moi mon Romulo' WHERE `sound` = 9200;
UPDATE `script_texts` SET `content_loc2` = 'Si douce est la tristesse de nos adieux' WHERE `sound` = 9201;
UPDATE `script_texts` SET `content_loc2` = 'Votre comportement est inacceptable.' WHERE `sound` = 9204;
UPDATE `script_texts` SET `content_loc2` = 'La mort arrive ! Avez-vous la conscience tranquille ?' WHERE `sound` = 9206;
UPDATE `script_texts` SET `content_loc2` = 'Ahahaha' WHERE `sound` = 9207;
UPDATE `script_texts` SET `content_loc2` = 'Il faut se débarassé de votre impureté' WHERE `sound` = 9208;
UPDATE `script_texts` SET `content_loc2` = 'Humm..des visiteurs imprévus, il va falloir se préparer' WHERE `sound` = 9211;
UPDATE `script_texts` SET `content_loc2` = 'Comme je suis maladroit ! C\'est terrible' WHERE `sound` = 9213;
UPDATE `script_texts` SET `content_loc2` = 'Une personne de plus au dîné de ce soir' WHERE `sound` = 9214;
UPDATE `script_texts` SET `content_loc2` = 'Bon ! Ou en etais-je ? Ah oui !' WHERE `sound` = 9215;
UPDATE `script_texts` SET `content_loc2` = 'La folie vous à fait venir ici devant moi. Et je serai votre perte.' WHERE `sound` = 9218;
UPDATE `script_texts` SET `content_loc2` = 'Imbécile heureux ! Le temps est le brasier dans lequel vous brulerez' WHERE `sound` = 9220;
UPDATE `script_texts` SET `content_loc2` = 'Je refuse de capituler ! Je suis un prince parmis les Eredar ! Je suis..' WHERE `sound` = 9221;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'avez quand même pas penser que vous pouviez gagner ?' WHERE `sound` = 9222;
UPDATE `script_texts` SET `content_loc2` = 'Qui sait quel secret se cache dans les ombres ? Ah oui ... moi !' WHERE `sound` = 9223;
UPDATE `script_texts` SET `content_loc2` = 'Toutes les réalités, toutes les dimensions me sont ouverte' WHERE `sound` = 9224;
UPDATE `script_texts` SET `content_loc2` = 'Vous me faites pas peur ! Vous voulez vous battre ? Ahah vraiment ? V\'nez y ! Je vous battrais avec mes deux pattes dans le dos !' WHERE `sound` = 9227;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'aviez pas besoin de fare ça !' WHERE `sound` = 9229;
UPDATE `script_texts` SET `content_loc2` = 'Aller faites donc une petite sieste.' WHERE `sound` = 9230;
UPDATE `script_texts` SET `content_loc2` = 'Tu veux donc me provoquer ? He bien toi ! Enfant !' WHERE `sound` = 9233;
UPDATE `script_texts` SET `content_loc2` = 'Tu souris au cou... qui me tue..' WHERE `sound` = 9235;
UPDATE `script_texts` SET `content_loc2` = 'Ce jour ...fera peser sur les jours avenirs..ca sombre fatalité...il commence ..le malheur..d\'autres doivent l\'achever' WHERE `sound` = 9236;
UPDATE `script_texts` SET `content_loc2` = 'Horrible gueule ! Matrice de la mort ! Je parviendrais bien par ouvrir tes lèvres pourris !' WHERE `sound` = 9237;
UPDATE `script_texts` SET `content_loc2` = 'Comme ceci ranime mon courage !' WHERE `sound` = 9238;
UPDATE `script_texts` SET `content_loc2` = 'Je vous en supplie arrêté ! Mon fils est devenu fou !' WHERE `sound` = 9241;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Oui mon fils est assez puissant. Mais moi aussi je possède quelques pouvoirs !' WHERE `sound` = 9242;
UPDATE `script_texts` SET `content_loc2` = 'Au moins...le cauchemar est terminé..' WHERE `sound` = 9244;
UPDATE `script_texts` SET `content_loc2` = 'Je vais vous montrer que ce chien battu à encore de bon crocs !' WHERE `sound` = 9245;
UPDATE `script_texts` SET `content_loc2` = 'Je vais tous vous congeler !' WHERE `sound` = 9246;
UPDATE `script_texts` SET `content_loc2` = 'Vous m\'avez fait assez perdre de temps comme ça ! Que ces jeux se termine !' WHERE `sound` = 9247;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne refuseriez pas à un vieil homme une boisson revigorante ? Non, c\'est bien ce que je pensais' WHERE `sound` = 9248;
UPDATE `script_texts` SET `content_loc2` = 'Où avez-vous trouver cela ? Est-ce lui qui vous envoie ?' WHERE `sound` = 9249;
UPDATE `script_texts` SET `content_loc2` = 'Je veux que ce cauchemar se termine !' WHERE `sound` = 9250;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis pas encore vaincu ! Non...j\'ai encore quelques tours dans mon sac' WHERE `sound` = 9251;
UPDATE `script_texts` SET `content_loc2` = 'Et que devrais-je faire de vous ? Je n\'arrive pas à me décider' WHERE `sound` = 9254;
UPDATE `script_texts` SET `content_loc2` = 'Ne les laissez pas me transformer en matelas !' WHERE `sound` = 9256;
UPDATE `script_texts` SET `content_loc2` = 'Je suppose que je ne suis pas un raté après tout' WHERE `sound` = 9257;
UPDATE `script_texts` SET `content_loc2` = 'Ah ! Vous arrivez juste à temps ! Les rituels vont commencer' WHERE `sound` = 9260;
UPDATE `script_texts` SET `content_loc2` = 'Ma vie vous appartient Ô tout puissant !' WHERE `sound` = 9262;
UPDATE `script_texts` SET `content_loc2` = 'Veuillez accepter cette humble offrande Ô tout puissant' WHERE `sound` = 9263;
UPDATE `script_texts` SET `content_loc2` = 'Mon cercle sera joint de votre sang' WHERE `sound` = 9264;
UPDATE `script_texts` SET `content_loc2` = 'Venez ! Vous qui vivez dans les ténèbres ! Ralliez-vous à moi !' WHERE `sound` = 9265;
UPDATE `script_texts` SET `content_loc2` = 'J\'aurais vraiment besoin d\'un coeur. Dites, je peux avoir le votre ?' WHERE `sound` = 9268;
UPDATE `script_texts` SET `content_loc2` = 'Et me revoila devenu un vieux seau tout rouillé' WHERE `sound` = 9270;
UPDATE `script_texts` SET `content_loc2` = 'On dirait que je ne suis pas si rouillé que ça' WHERE `sound` = 9271;
UPDATE `script_texts` SET `content_loc2` = 'Grrrr !! Grrrr !! C\'est pour mieux te camper mon enfant ! Grrr !!' WHERE `sound` = 9276;
UPDATE `script_texts` SET `content_loc2` = 'Hummmm ! Délicieux !' WHERE `sound` = 9277;
UPDATE `script_texts` SET `content_loc2` = 'Cours petite fille ! Cours !' WHERE `sound` = 9278;
UPDATE `script_texts` SET `content_loc2` = 'Qui ose s\'en prendre à la monture du Veneur ?' WHERE `sound` = 9298;
UPDATE `script_texts` SET `content_loc2` = 'Vous préférez peut être vous mesurez à un adversaire plus redoutable ?' WHERE `sound` = 9299;
UPDATE `script_texts` SET `content_loc2` = 'Un nouveau trophé a ajouter à ma collection' WHERE `sound` = 9300;
UPDATE `script_texts` SET `content_loc2` = 'Amateur ! Ne pensez pas pouvoir me battre ! Tuer est mon métier !' WHERE `sound` = 9304;
UPDATE `script_texts` SET `content_loc2` = 'Ce sera bientôt terminé !' WHERE `sound` = 9307;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'êtes pas un invité' WHERE `sound` = 9308;
UPDATE `script_texts` SET `content_loc2` = 'Ce conservateur est équipé pour la protection de la galerie' WHERE `sound` = 9309;
UPDATE `script_texts` SET `content_loc2` = 'Ohhh heureux poignard ! Voici ton fourreau ! Rouille toi la et laisse moi mourir' WHERE `sound` = 9310;
UPDATE `script_texts` SET `content_loc2` = 'Les pensées impures entrainent des actions profanes' WHERE `sound` = 9311;
UPDATE `script_texts` SET `content_loc2` = 'C\'est pour le mieux.' WHERE `sound` = 9312;
UPDATE `script_texts` SET `content_loc2` = 'Chassez vos pensées corrompues' WHERE `sound` = 9313;
UPDATE `script_texts` SET `content_loc2` = 'Le temps ! Jamais assez de temps !' WHERE `sound` = 9314;
UPDATE `script_texts` SET `content_loc2` = 'Oh ! J\'ai fais un beau gachis' WHERE `sound` = 9315;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez sonné ?' WHERE `sound` = 9316;
UPDATE `script_texts` SET `content_loc2` = 'Je vois que la notion de subtilité passe par dessus la tête de primitif comme vous' WHERE `sound` = 9317;
UPDATE `script_texts` SET `content_loc2` = 'Votre avidité, votre folie ont provoqués votre fin' WHERE `sound` = 9318;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'êtes qu\'un jouet ! Un jouet qui ne m\amuse même pas.' WHERE `sound` = 9319;
UPDATE `script_texts` SET `content_loc2` = 'Je manipule les forces célèstes à ma guise' WHERE `sound` = 9320;
UPDATE `script_texts` SET `content_loc2` = 'Comment pouvez-vous espèrer devant un tel pouvoir ?' WHERE `sound` = 9321;
UPDATE `script_texts` SET `content_loc2` = 'Vous \'avez pas seulement Malchezaar ! Mais les Légions que je commande !' WHERE `sound` = 9322;
UPDATE `script_texts` SET `content_loc2` = 'Je refuse d\être à nouveau torturé' WHERE `sound` = 9323;
UPDATE `script_texts` SET `content_loc2` = 'Qui êtes vous ? Qu\'est ce que vous voulez ? Ne m\'approchez pas !' WHERE `sound` = 9324;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis pas un simple bouffon ! Je suis Nielas Aran !' WHERE `sound` = 9325;
UPDATE `script_texts` SET `content_loc2` = 'Brulez démons de l\'enfer ! ' WHERE `sound` = 9326;
UPDATE `script_texts` SET `content_loc2` = 'Retournez dans les ténèbres glaciale !' WHERE `sound` = 9327;
UPDATE `script_texts` SET `content_loc2` = 'Ne me tourmentez plus !' WHERE `sound` = 9328;
UPDATE `script_texts` SET `content_loc2` = 'Le tout puissant sera content' WHERE `sound` = 9329;
UPDATE `script_texts` SET `content_loc2` = 'Que se sacrifice témoigne de ma fidélité' WHERE `sound` = 9330;
UPDATE `script_texts` SET `content_loc2` = 'Venez mes chéris, il y en aura pour tout le monde' WHERE `sound` = 9331;

UPDATE `script_texts` SET `content_loc2` = 'Bonsoir mesdames et messieurs et bienvenue à la représentation de ce soir !' WHERE `sound` = 9174;
UPDATE `script_texts` SET `content_loc2` = 'Bonsoir mesdames et messieurs, bienvenue à la représentation de ce soir !' WHERE `sound` = 9175;
UPDATE `script_texts` SET `content_loc2` = 'Soyez les bienvenue, mesdames et messieurs à la représentation de ce soir !' WHERE `sound` = 9176;
UPDATE `script_texts` SET `content_loc2` = 'Cette nuit, les apparences sont trompeuses ! Vous ne pourrez pas vous fiez à vos yeux.' WHERE `sound` = 9335;
UPDATE `script_texts` SET `content_loc2` = 'Prenez par exemple cette paisible dame âgée qui attend la visite de sa petite fille. Il n\'y surement rien à craindre de cette gentille vieille dame aux cheveux gris.' WHERE `sound` = 9336;
UPDATE `script_texts` SET `content_loc2` = 'Nul loin de moi l\'idée de vous trompez. Voyez pour vous même ce qui se cache sous ses couvertures. Et maintenant que le spectacle commence !' WHERE `sound` = 9337;
UPDATE `script_texts` SET `content_loc2` = 'Aujourd\'hui nous allons explorer les profondeurs de l\âme humaine. En rejoignant une petite fille égarée, qui tente désesperement avec l\'aide de ses fidèles compagnons, de rentrer chez elle.' WHERE `sound` = 9338;
UPDATE `script_texts` SET `content_loc2` = 'Mais elle est poursuivie par une méchante sorcière !' WHERE `sound` = 9339;
UPDATE `script_texts` SET `content_loc2` = 'Survivra t-elle ? Réussiera t-elle ? Seul le temps le dira ! Et maintenant que le spectacle commence !' WHERE `sound` = 9340;
UPDATE `script_texts` SET `content_loc2` = 'Ce soir, nous allons suivre le récit d\'un amour interdit.' WHERE `sound` = 9341;
UPDATE `script_texts` SET `content_loc2` = 'Mais prenez garde toute les histoires d\'amours ne finissent pas bien comme vous pourrez le voir. Parfois l\'amour écorche comme l\'épine.' WHERE `sound` = 9342;
UPDATE `script_texts` SET `content_loc2` = 'Mais ne me croyez pas sur parole ! Voyez pour vous même que tragédie se prépare lorsque se croise les chemins de deux amants maudit par les étoiles. Et maintenant...que le spectacle commence !' WHERE `sound` = 9343;
UPDATE `script_texts` SET `content_loc2` = 'Qui ose interrompre ?...Quoi ? Qu\'avez vous fait ? Vous allez tout gacher ?' WHERE `sound` = 10164;
UPDATE `script_texts` SET `content_loc2` = 'Approchez ! Approchez et brûler !' WHERE `sound` = 10165;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne devez pas le liberé' WHERE `sound` = 10166;
UPDATE `script_texts` SET `content_loc2` = 'Morveux ignorants !' WHERE `sound` = 10167;
UPDATE `script_texts` SET `content_loc2` = 'Fous ! Il nous tuera tous !' WHERE `sound` = 10168;
UPDATE `script_texts` SET `content_loc2` = 'C\'est tout ce que vous méritez' WHERE `sound` = 10169;
UPDATE `script_texts` SET `content_loc2` = 'Vos amis vont bientôt vous rejoindre' WHERE `sound` = 10170;
UPDATE `script_texts` SET `content_loc2` = 'De la chance...vous en aurez besoin..' WHERE `sound` = 10171;
UPDATE `script_texts` SET `content_loc2` = 'Ma tâche ne doit pas être interrompue' WHERE `sound` = 10286;
UPDATE `script_texts` SET `content_loc2` = 'Je pourrais peut être me servir de vous' WHERE `sound` = 10287;
UPDATE `script_texts` SET `content_loc2` = 'La colère ! La haine ! Ce sont des outils dont je peux me servir' WHERE `sound` = 10288;
UPDATE `script_texts` SET `content_loc2` = 'Voyons ce que je peux faire de vous' WHERE `sound` = 10289;
UPDATE `script_texts` SET `content_loc2` = 'Résister ne sert à rien !' WHERE `sound` = 10290;
UPDATE `script_texts` SET `content_loc2` = 'Restez loin....de moi..' WHERE `sound` = 10291;
UPDATE `script_texts` SET `content_loc2` = 'Misérables insectes importunt, libérés moi et je vous accorderai peut-être une mort rapide' WHERE `sound` = 10247;
UPDATE `script_texts` SET `content_loc2` = 'Vermines ! Sangsues ! Prenez mon sang et qu\'il vous étouffe' WHERE `sound` = 10248;
UPDATE `script_texts` SET `content_loc2` = 'Illidan est un crétin arrogant, je l\'écraserai et l\'Outreterre sera de nouveau à moi' WHERE `sound` = 10249;
UPDATE `script_texts` SET `content_loc2` = 'Du balai, parasites inconscient mon sang est à moi' WHERE `sound` = 10250;
UPDATE `script_texts` SET `content_loc2` = 'Vous croyez que votre sorcellerie de bas étage pourra me retenir longtemps ?' WHERE `sound` = 10251;
UPDATE `script_texts` SET `content_loc2` = 'Mon sang sera votre perte !' WHERE `sound` = 10252;
UPDATE `script_texts` SET `content_loc2` = 'Mouhahahahaha ! Me voila...déchainé !' WHERE `sound` = 10253;
UPDATE `script_texts` SET `content_loc2` = 'Merci de m\'avoir libéré. Maintenant mourez !' WHERE `sound` = 10254;
UPDATE `script_texts` SET `content_loc2` = 'Vous me pensiez affaibli ? Ramolli ? Qui est le plus faible maintenant ?' WHERE `sound` = 10255;
UPDATE `script_texts` SET `content_loc2` = 'Pas encore....pas encore !' WHERE `sound` = 10256;
UPDATE `script_texts` SET `content_loc2` = 'Je ne me laisserai pas prendre si facilement. Que les murs de cette prison tremble et s\éffrondre' WHERE `sound` = 10257;
UPDATE `script_texts` SET `content_loc2` = 'La Légion vous brulera tous ' WHERE `sound` = 10258;
UPDATE `script_texts` SET `content_loc2` = 'Mendiez moi votre pitoyable vie' WHERE `sound` = 10259;
UPDATE `script_texts` SET `content_loc2` = 'Courrez pauvre lâche ! Courrez !' WHERE `sound` = 10260;
UPDATE `script_texts` SET `content_loc2` = 'Votre douleur me divertie' WHERE `sound` = 10261;
UPDATE `script_texts` SET `content_loc2` = 'Vous voulez nous affrontez tous ensemble ? Ca devrait être drôle !' WHERE `sound` = 10262;
UPDATE `script_texts` SET `content_loc2` = 'Vous pouvez prendre celui là, je n\'en ai plus l\'usage' WHERE `sound` = 10263;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Tapez le sans pitié ! Il a le crâne aussi dur qu\'un Ogre!' WHERE `sound` = 10264;
UPDATE `script_texts` SET `content_loc2` = 'Ne perdez pas votre temps avec celui-ci, il est tout faible' WHERE `sound` = 10265;
UPDATE `script_texts` SET `content_loc2` = 'Vous le voulez ? Très bien ! Prenez le ' WHERE `sound` = 10266;
UPDATE `script_texts` SET `content_loc2` = 'Un pauvre diable au tapis. Aller prenez en un autre !' WHERE `sound` = 10267;
UPDATE `script_texts` SET `content_loc2` = 'Oh quel gâchis ! Au suivant !' WHERE `sound` = 10268;
UPDATE `script_texts` SET `content_loc2` = 'De toute façon je l\'aurais tué quand même' WHERE `sound` = 10269;
UPDATE `script_texts` SET `content_loc2` = 'Merci pour le coup de main ! Et maintenant....à moi de m\'amuser un peu' WHERE `sound` = 10270;
UPDATE `script_texts` SET `content_loc2` = 'Je m\'ennuie déjà' WHERE `sound` = 10271;
UPDATE `script_texts` SET `content_loc2` = 'Allons ! Un peu de nerf !' WHERE `sound` = 10272;
UPDATE `script_texts` SET `content_loc2` = 'C\'est encore moins drôle que de torturer des péons' WHERE `sound` = 10273;
UPDATE `script_texts` SET `content_loc2` = 'Perdu !' WHERE `sound` = 10274;
UPDATE `script_texts` SET `content_loc2` = 'Mais mourez donc !' WHERE `sound` = 10275;
UPDATE `script_texts` SET `content_loc2` = 'Quel...embarras..' WHERE `sound` = 10276;
UPDATE `script_texts` SET `content_loc2` = 'Moi pas aimer celui la.' WHERE `sound` = 10300;
UPDATE `script_texts` SET `content_loc2` = 'Nous tuer son ami.' WHERE `sound` = 10301;
UPDATE `script_texts` SET `content_loc2` = 'Nous tuer quelqu\'un d\'autre' WHERE `sound` = 10302;
UPDATE `script_texts` SET `content_loc2` = 'Toi rester la! Moi tuer quelqu\'un d\'autre' WHERE `sound` = 10303;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahaha' WHERE `sound` = 10304;
UPDATE `script_texts` SET `content_loc2` = 'Moi m\'ennuyer' WHERE `sound` = 10305;
UPDATE `script_texts` SET `content_loc2` = '\'crabouille !' WHERE `sound` = 10306;
UPDATE `script_texts` SET `content_loc2` = 'Hey !!' WHERE `sound` = 10307;
UPDATE `script_texts` SET `content_loc2` = 'Si toi sympa moi te laisser libre' WHERE `sound` = 10308;
UPDATE `script_texts` SET `content_loc2` = 'Moi faim !' WHERE `sound` = 10309;
UPDATE `script_texts` SET `content_loc2` = 'C\'lui la mourir facile' WHERE `sound` = 10310;
UPDATE `script_texts` SET `content_loc2` = 'Ca tout ta faute !' WHERE `sound` = 10311;
UPDATE `script_texts` SET `content_loc2` = 'Héééé ! Tête d\'abruti !' WHERE `sound` = 10312;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai pas terminé pauvre idiot !' WHERE `sound` = 10313;
UPDATE `script_texts` SET `content_loc2` = 'C\'est pas drôle !' WHERE `sound` = 10314;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que tu veux ?' WHERE `sound` = 10315;
UPDATE `script_texts` SET `content_loc2` = 'Ennuyer ! Il était presque mort !' WHERE `sound` = 10316;
UPDATE `script_texts` SET `content_loc2` = 'Et si je m\'occupais des pourparlers' WHERE `sound` = 10317;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Nous laisserons personne vivre !' WHERE `sound` = 10318;
UPDATE `script_texts` SET `content_loc2` = 'Tu as toujours faim ! C\'est ta faute si nous sommes aussi gros !' WHERE `sound` = 10319;
UPDATE `script_texts` SET `content_loc2` = 'Hé fatiguer ! Le suivant est pour toi !' WHERE `sound` = 10320;
UPDATE `script_texts` SET `content_loc2` = 'C\'est parce c\'est moi qui fait tout le travail !' WHERE `sound` = 10321;
UPDATE `script_texts` SET `content_loc2` = 'Je....je..te déteste !' WHERE `sound` = 10322;
UPDATE `script_texts` SET `content_loc2` = 'Achor-she-ki ! Repais toi mon familier ! Gaves toi !' WHERE `sound` = 10277;
UPDATE `script_texts` SET `content_loc2` = 'A-Kreesh' WHERE `sound` = 10278;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serais pas vaincu !' WHERE `sound` = 10279;
UPDATE `script_texts` SET `content_loc2` = 'Vous osez m\'affronter moi ?' WHERE `sound` = 10280;
UPDATE `script_texts` SET `content_loc2` = 'Votre insolence sera votre perte' WHERE `sound` = 10281;
UPDATE `script_texts` SET `content_loc2` = 'Meurs mauviette !' WHERE `sound` = 10282;
UPDATE `script_texts` SET `content_loc2` = 'A moi la victoire !' WHERE `sound` = 10283;
UPDATE `script_texts` SET `content_loc2` = 'Ce n\'est pas terminé !' WHERE `sound` = 10284;
UPDATE `script_texts` SET `content_loc2` = 'Soignez moi ! Vite !' WHERE `sound` = 10329;
UPDATE `script_texts` SET `content_loc2` = 'Arrière gamin !' WHERE `sound` = 10330;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'avons-nous la ?' WHERE `sound` = 10331;
UPDATE `script_texts` SET `content_loc2` = 'Hum ! Ca risque de faire un peu mal ' WHERE `sound` = 10332;
UPDATE `script_texts` SET `content_loc2` = 'Je vais aimer ça !' WHERE `sound` = 10333;
UPDATE `script_texts` SET `content_loc2` = 'Dites adieu !' WHERE `sound` = 10334;
UPDATE `script_texts` SET `content_loc2` = 'Beaucoup trop facile !' WHERE `sound` = 10335;
UPDATE `script_texts` SET `content_loc2` = 'Ahahaha...ahah...urgh..' WHERE `sound` = 10336;
UPDATE `script_texts` SET `content_loc2` = 'Jaillissez mes chéris !' WHERE `sound` = 10360;
UPDATE `script_texts` SET `content_loc2` = 'Les profondeurs vous dévorerons !' WHERE `sound` = 10361;
UPDATE `script_texts` SET `content_loc2` = 'Périssez habitants de la surface !' WHERE `sound` = 10362;
UPDATE `script_texts` SET `content_loc2` = 'Vous vous noierez dans le sang !' WHERE `sound` = 10363;
UPDATE `script_texts` SET `content_loc2` = 'Plongez dans les profondeurs de l\'oublie !' WHERE `sound` = 10364;
UPDATE `script_texts` SET `content_loc2` = 'Pour ma Dame...et Souveraine..' WHERE `sound` = 10365;
UPDATE `script_texts` SET `content_loc2` = 'Argh!! Notre matrone se chargera de vous !' WHERE `sound` = 10366;
UPDATE `script_texts` SET `content_loc2` = 'Faites leur une vidange les gars !' WHERE `sound` = 10367;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez salement déguster !' WHERE `sound` = 10368;
UPDATE `script_texts` SET `content_loc2` = 'Bouffe du métal chaud vermine !' WHERE `sound` = 10369;
UPDATE `script_texts` SET `content_loc2` = 'C\'est moi que v\'la !' WHERE `sound` = 10370;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai apporté les pains !' WHERE `sound` = 10371;
UPDATE `script_texts` SET `content_loc2` = 'T\'as eu ce que tu méritais !' WHERE `sound` = 10372;
UPDATE `script_texts` SET `content_loc2` = 'Je t\'ai eu !' WHERE `sound` = 10373;
UPDATE `script_texts` SET `content_loc2` = 'Pas de mort espèce de minable' WHERE `sound` = 10374;
UPDATE `script_texts` SET `content_loc2` = 'Maman..' WHERE `sound` = 10375;
UPDATE `script_texts` SET `content_loc2` = 'Vous vous croyez de taille parce que vous avez vaincu mes gardes ? Ahaha ! Vous ne compromettrez pas notre oeuvre !' WHERE `sound` = 10390;
UPDATE `script_texts` SET `content_loc2` = 'C\'est loin d\'être terminé !' WHERE `sound` = 10391;
UPDATE `script_texts` SET `content_loc2` = 'Votre tête va tomber !' WHERE `sound` = 10392;
UPDATE `script_texts` SET `content_loc2` = 'Je méprise toute votre espèce !' WHERE `sound` = 10393;
UPDATE `script_texts` SET `content_loc2` = 'Ba\'ahntha sol\'dorei !' WHERE `sound` = 10394;
UPDATE `script_texts` SET `content_loc2` = 'Tortille toi vers de la surface !' WHERE `sound` = 10395;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahahahaha !' WHERE `sound` = 10396;
UPDATE `script_texts` SET `content_loc2` = 'Pour son excellence...pour Vashj...' WHERE `sound` = 10397;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai gagné ma liberté !' WHERE `sound` = 10448;
UPDATE `script_texts` SET `content_loc2` = 'J\'attend ce jour depuis bien trop longtemps..hors de ma route !' WHERE `sound` = 10449;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis plus un esclave.' WHERE `sound` = 10450;
UPDATE `script_texts` SET `content_loc2` = 'L\'onde noire va avoir beaucoup de compte à rendre.' WHERE `sound` = 10451;
UPDATE `script_texts` SET `content_loc2` = 'Vous m\'avez forcé la main !' WHERE `sound` = 10452;
UPDATE `script_texts` SET `content_loc2` = 'Nous n\'aurions pas dû en arriver la !' WHERE `sound` = 10453;
UPDATE `script_texts` SET `content_loc2` = 'Ce n\'est pas ce que je voulais !' WHERE `sound` = 10454;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai vraiment une dette envers vous étranger.' WHERE `sound` = 10455;
UPDATE `script_texts` SET `content_loc2` = 'Merci étranger vous m\'avez offert l\'espoir.' WHERE `sound` = 10456;
UPDATE `script_texts` SET `content_loc2` = 'Je ne gâcherais pas cette chance, j\'irai à la rencontre de mon destin.' WHERE `sound` = 10457;
UPDATE `script_texts` SET `content_loc2` = 'L\'avenir semble bien sinistre.' WHERE `sound` = 10458;
UPDATE `script_texts` SET `content_loc2` = 'Je me battrais jusqu\'au bout !' WHERE `sound` = 10459;
UPDATE `script_texts` SET `content_loc2` = 'Taretha..' WHERE `sound` = 10460;
UPDATE `script_texts` SET `content_loc2` = 'Un bon jour...pour mourir...' WHERE `sound` = 10461;
UPDATE `script_texts` SET `content_loc2` = 'Très bien ! Allons-y!' WHERE `sound` = 10465;
UPDATE `script_texts` SET `content_loc2` = 'Un cavalier approche.' WHERE `sound` = 10466;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serais plus jamais enchaîné !' WHERE `sound` = 10467;
UPDATE `script_texts` SET `content_loc2` = 'Très bien, Moulin-de-Tarren se trouve plus à l\'Ouest puisque le temps nous est compté.' WHERE `sound` = 10468;
UPDATE `script_texts` SET `content_loc2` = 'Chevauchons !' WHERE `sound` = 10469;
UPDATE `script_texts` SET `content_loc2` = 'C\'était qui ? Ou quoi ?' WHERE `sound` = 10470;
UPDATE `script_texts` SET `content_loc2` = 'Non !' WHERE `sound` = 10471;
UPDATE `script_texts` SET `content_loc2` = 'Adieu Taretha ! Je n\'oublierais jamais votre bonté.' WHERE `sound` = 10472;
UPDATE `script_texts` SET `content_loc2` = 'Tous vos efforts ont été vain, car l\'assèchement de l\'Arbre-Monde a déjà commencé, bientôt le coeur de ce monde aura cesser de bâttre.' WHERE `sound` = 10986;
UPDATE `script_texts` SET `content_loc2` = 'Votre résistance est futile.' WHERE `sound` = 10987;
UPDATE `script_texts` SET `content_loc2` = 'Vous êtes a moi maintenant !' WHERE `sound` = 10988;
UPDATE `script_texts` SET `content_loc2` = 'A-Kreesh !' WHERE `sound` = 10989;
UPDATE `script_texts` SET `content_loc2` = 'Ce monde brûlera !' WHERE `sound` = 10990;
UPDATE `script_texts` SET `content_loc2` = 'Ton âme se morfondera pour l\'éternité' WHERE `sound` = 10991;
UPDATE `script_texts` SET `content_loc2` = 'Non ! C\'est impossible ! Nooooooooonnnn !' WHERE `sound` = 10992;
UPDATE `script_texts` SET `content_loc2` = 'L\'heure est enfin venue ! Pleurez et lamentez-vous car voici venue la fin de tout ce que vous avez pu connaître et de tout avenir ! Akmin-kurai !' WHERE `sound` = 10993;
UPDATE `script_texts` SET `content_loc2` = 'N\'abandonnez pas ! Nous devons triompher !' WHERE `sound` = 11006;
UPDATE `script_texts` SET `content_loc2` = 'Je suis en danger ! M\'aide qui peut.' WHERE `sound` = 11007;
UPDATE `script_texts` SET `content_loc2` = 'Restez sur vos gardes une autre vague arrive.' WHERE `sound` = 11008;
UPDATE `script_texts` SET `content_loc2` = 'Nous sommes perdus. Repliez-vous !' WHERE `sound` = 11009;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai fais de..mon mieux..' WHERE `sound` = 11010;
UPDATE `script_texts` SET `content_loc2` = 'Nous avons gagner un temps précieux. Maintenant nous devons reculer.' WHERE `sound` = 11011;
UPDATE `script_texts` SET `content_loc2` = 'Repoussez les ! Ne faiblissez pas !' WHERE `sound` = 11030;
UPDATE `script_texts` SET `content_loc2` = 'Je ne plierai devant personne !' WHERE `sound` = 11031;
UPDATE `script_texts` SET `content_loc2` = 'Soyons prêt pour la prochaine vague ! LOK-TAR OGAR !' WHERE `sound` = 11032;
UPDATE `script_texts` SET `content_loc2` = 'C\'est terminé...repliez vous . Nous avons échoué.' WHERE `sound` = 11033;
UPDATE `script_texts` SET `content_loc2` = 'Urghhhh.....' WHERE `sound` = 11034;
UPDATE `script_texts` SET `content_loc2` = 'Nous avons remplis notre rôle..et plutôt bien..c\'est aux autres de jouer maintenant.' WHERE `sound` = 11035;
UPDATE `script_texts` SET `content_loc2` = 'Manach sheek-trish !' WHERE `sound` = 11041;
UPDATE `script_texts` SET `content_loc2` = 'Pliez devant ma volonté !' WHERE `sound` = 11042;
UPDATE `script_texts` SET `content_loc2` = 'Dégage vermine !' WHERE `sound` = 11043;
UPDATE `script_texts` SET `content_loc2` = 'Toutes la création sera dévorée !' WHERE `sound` = 11044;
UPDATE `script_texts` SET `content_loc2` = 'Je suis l\'avènement de la fin !' WHERE `sound` = 11045;
UPDATE `script_texts` SET `content_loc2` = 'Ils sont passés !' WHERE `sound` = 11049;
UPDATE `script_texts` SET `content_loc2` = 'Repoussez les aussi longtemps que possible !' WHERE `sound` = 11050;
UPDATE `script_texts` SET `content_loc2` = 'Nous devons tenir bon !' WHERE `sound` = 11051;
UPDATE `script_texts` SET `content_loc2` = 'La victoire ou la mort !' WHERE `sound` = 11059;
UPDATE `script_texts` SET `content_loc2` = 'Ne lâchez pas un pouce de terrain !' WHERE `sound` = 11060;
UPDATE `script_texts` SET `content_loc2` = 'Venez m\'attaquer et payez le de vos vies !' WHERE `sound` = 11061;
UPDATE `script_texts` SET `content_loc2` = 'Je donne ma vie... avec joie.' WHERE `entry` = -1555035;
UPDATE `script_texts` SET `content_loc2` = 'Votre mort sert une cause supérieure !' WHERE `entry` = -1555034;
UPDATE `script_texts` SET `content_loc2` = 'Je sers fièrement !' WHERE `entry` = -1555033;
UPDATE `script_texts` SET `content_loc2` = 'Venez à mon aide, obéissez à votre maître !' WHERE `entry` = -1555032;
UPDATE `script_texts` SET `content_loc2` = 'Bien, un digne sacrifice.' WHERE `entry` = -1555031;
UPDATE `script_texts` SET `content_loc2` = 'Tu feras un bon exemple pour les autres.' WHERE `entry` = -1555030;
UPDATE `script_texts` SET `content_loc2` = 'Je ferai une offrande de ton sang !' WHERE `entry` = -1555029;
UPDATE `script_texts` SET `content_loc2` = 'Que vos esprits restent clairs car le jour du Jugement approche ! Bientôt, le destructeur de mondes reviendra pour tenir sa promesse. Bientôt la destruction de toute chose va commencer !' WHERE `entry` = -1555028;
UPDATE `script_texts` SET `content_loc2` = 'Arrgh, aah...ahhh' WHERE `entry` = -1555027;
UPDATE `script_texts` SET `content_loc2` = 'Aidez-nous, vite !' WHERE `entry` = -1555026;
UPDATE `script_texts` SET `content_loc2` = 'Mais perdu ! haha haha' WHERE `entry` = -1555025;
UPDATE `script_texts` SET `content_loc2` = 'Toi mort pour de bon.' WHERE `entry` = -1555024;
UPDATE `script_texts` SET `content_loc2` = 'Vous être des gens morts !' WHERE `entry` = -1555023;
UPDATE `script_texts` SET `content_loc2` = 'Tuons un peu !' WHERE `entry` = -1555022;
UPDATE `script_texts` SET `content_loc2` = 'Vous le regretterez !' WHERE `entry` = -1555021;
UPDATE `script_texts` SET `content_loc2` = 'Ténébreux promettre !' WHERE `entry` = -1555020;
UPDATE `script_texts` SET `content_loc2` = 'Et nous avoir place dans nouveau monde.' WHERE `entry` = -1555019;
UPDATE `script_texts` SET `content_loc2` = 'Préparé au retour du ténébreux.' WHERE `entry` = -1555018;
UPDATE `script_texts` SET `content_loc2` = 'C\'est pas... bon... signe...' WHERE `entry` = -1555017;
UPDATE `script_texts` SET `content_loc2` = 'Aidez-nous, vite !' WHERE `entry` = -1555016;
UPDATE `script_texts` SET `content_loc2` = 'Bien essayé !' WHERE `entry` = -1555015;
UPDATE `script_texts` SET `content_loc2` = 'Pas de billet de retour !' WHERE `entry` = -1555014;
UPDATE `script_texts` SET `content_loc2` = 'Je vois des gens qui sont morts !' WHERE `entry` = -1555013;
UPDATE `script_texts` SET `content_loc2` = 'Rions un peu !' WHERE `entry` = -1555012;
UPDATE `script_texts` SET `content_loc2` = 'Vous le regretterez !' WHERE `entry` = -1555011;
UPDATE `script_texts` SET `content_loc2` = 'La puissance t\'appartiendra !' WHERE `entry` = -1555010;
UPDATE `script_texts` SET `content_loc2` = 'Toute la création doit être défaite !' WHERE `entry` = -1555009;
UPDATE `script_texts` SET `content_loc2` = 'Toute la chair doit brûler.' WHERE `entry` = -1555008;
UPDATE `script_texts` SET `content_loc2` = 'Ne soyez... pas trop... sûr de vous, mortels.' WHERE `entry` = -1555007;
UPDATE `script_texts` SET `content_loc2` = 'C\'est le morceau que je préfère.' WHERE `entry` = -1555006;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez peur de la mort ?' WHERE `entry` = -1555005;
UPDATE `script_texts` SET `content_loc2` = 'Imbéciles ! Aidez-moi avant qu\'il ne soit trop tard !' WHERE `entry` = -1555004;
UPDATE `script_texts` SET `content_loc2` = 'Enfin ! De quoi soulager la monotonie !' WHERE `entry` = -1555003;
UPDATE `script_texts` SET `content_loc2` = 'Je vais vous briser !' WHERE `entry` = -1555002;
UPDATE `script_texts` SET `content_loc2` = 'Pitoyables mortels ! Vous le paierez cher !' WHERE `entry` = -1555001;
UPDATE `script_texts` SET `content_loc2` = 'Des infidèles ont envahis le sanctuaire. Insectes pleurnichards... vous ne connaissez pas encore le sens profond du mot douleur !' WHERE `entry` = -1555000;
UPDATE `script_texts` SET `content_loc2` = 'Je vous prédis une mort douloureuse !' WHERE `sound` = 11101;
UPDATE `script_texts` SET `content_loc2` = 'Votre stratégie était imparfaite.' WHERE `sound` = 11102;
UPDATE `script_texts` SET `content_loc2` = 'C\'était la seule issue logique.' WHERE `sound` = 11103;
UPDATE `script_texts` SET `content_loc2` = 'Mesurer deux fois,couper une fois' WHERE `sound` = 11104;
UPDATE `script_texts` SET `content_loc2` = 'Et si ma division est bien posée, je crois que vous êtes mort !' WHERE `sound` = 11105;
UPDATE `script_texts` SET `content_loc2` = 'Voilà....argh...impondérable...' WHERE `sound` = 11106;
UPDATE `script_texts` SET `content_loc2` = 'Il vous reste approximativement cinq secondes à vivre.' WHERE `sound` = 11109;
UPDATE `script_texts` SET `content_loc2` = 'Une conclusion bien prévisible.' WHERE `sound` = 11110;
UPDATE `script_texts` SET `content_loc2` = 'L\'opération continuera selon  le plan.' WHERE `sound` = 11111;
UPDATE `script_texts` SET `content_loc2` = 'Avec l\'angle et la vitesse d\'approche parfaite.' WHERE `sound` = 11112;
UPDATE `script_texts` SET `content_loc2` = 'Un peu dépassé mais très efficace.' WHERE `sound` = 11113;
UPDATE `script_texts` SET `content_loc2` = 'Mes calculs ne prévoyaient pas...' WHERE `sound` = 11114;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'aimez pas la vie c\'est ca ?' WHERE `sound` = 11186;
UPDATE `script_texts` SET `content_loc2` = 'Et n\'y revenez pas !' WHERE `sound` = 11187;
UPDATE `script_texts` SET `content_loc2` = 'En\'dala finel el\'dal!' WHERE `sound` = 11188;
UPDATE `script_texts` SET `content_loc2` = 'Vous supporterez toute cette chaleur ?' WHERE `sound` = 11189;
UPDATE `script_texts` SET `content_loc2` = 'Anar\'endal dracon !' WHERE `sound` = 11190;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis pas seule.' WHERE `sound` = 11191;
UPDATE `script_texts` SET `content_loc2` = 'Anu...bala belore...alon.' WHERE `sound` = 11192;
UPDATE `script_texts` SET `content_loc2` = 'Notre calendrier est serré ! Je ne vous laisserais pas perturber notre travail !' WHERE `sound` = 11193;
UPDATE `script_texts` SET `content_loc2` = 'Une simple petite nuisance.' WHERE `sound` = 11194;
UPDATE `script_texts` SET `content_loc2` = 'On dirait bien que vous avez perdu.' WHERE `sound` = 11195;
UPDATE `script_texts` SET `content_loc2` = 'Il est temps de compléter mon équipe de travail.' WHERE `sound` = 11196;
UPDATE `script_texts` SET `content_loc2` = 'Je recherche un bon coéquiper.' WHERE `sound` = 11197;
UPDATE `script_texts` SET `content_loc2` = 'Vous êtes en service maintenant.' WHERE `sound` = 11198;
UPDATE `script_texts` SET `content_loc2` = 'Je préfère les travaux pratique !' WHERE `sound` = 11199;
UPDATE `script_texts` SET `content_loc2` = 'Le projet continuera...' WHERE `sound` = 11200;
UPDATE `script_texts` SET `content_loc2` = 'Les Sin\'dorei règnent en maître !' WHERE `sound` = 11117;
UPDATE `script_texts` SET `content_loc2` = 'Ca n\'est pas terminé...' WHERE `sound` = 11118;
UPDATE `script_texts` SET `content_loc2` = 'Tal anu\'men no Sin\'dorei!' WHERE `sound` = 11134;
UPDATE `script_texts` SET `content_loc2` = 'La chaleur du soleil m\'attend.' WHERE `sound` = 11135;
UPDATE `script_texts` SET `content_loc2` = 'Votre âme appartient aux abysses !' WHERE `sound` = 11136;
UPDATE `script_texts` SET `content_loc2` = 'Par le sang des Bien-nés !' WHERE `sound` = 11137;
UPDATE `script_texts` SET `content_loc2` = 'Pour le Puit de Soleil !' WHERE `sound` = 11138;
UPDATE `script_texts` SET `content_loc2` = 'Ahahaha ! Vous êtes désespèrement surclassé !' WHERE `sound` = 11139;
UPDATE `script_texts` SET `content_loc2` = 'Je vais balayer vos illusions de grandeur.' WHERE `sound` = 11140;
UPDATE `script_texts` SET `content_loc2` = 'Sang pour sang !' WHERE `sound` = 11152;
UPDATE `script_texts` SET `content_loc2` = 'Non ! ....Je...ne...peux..urgh..' WHERE `sound` = 11153;
UPDATE `script_texts` SET `content_loc2` = 'Anar\'alah belore!' WHERE `sound` = 11157;
UPDATE `script_texts` SET `content_loc2` = 'D\'autres périls vous attendent...' WHERE `sound` = 11158;
UPDATE `script_texts` SET `content_loc2` = 'Préparez-vous !' WHERE `sound` = 11203;
UPDATE `script_texts` SET `content_loc2` = 'Pardonnez moi mon prince...j\'ai ...échoué..' WHERE `sound` = 11204;
UPDATE `script_texts` SET `content_loc2` = 'Alerte ! Vous êtes désigné pour être exterminer !' WHERE `sound` = 11213;
UPDATE `script_texts` SET `content_loc2` = 'Extinction du système..' WHERE `sound` = 11214;
UPDATE `script_texts` SET `content_loc2` = 'Extermination accomplie.' WHERE `sound` = 11215;
UPDATE `script_texts` SET `content_loc2` = 'Forme de vie intruse placée en dysfonctionnement.' WHERE `sound` = 11216;
UPDATE `script_texts` SET `content_loc2` = 'Menace neutralisée.' WHERE `sound` = 11217;
UPDATE `script_texts` SET `content_loc2` = 'Lancement des mesures alternatives.' WHERE `sound` = 11218;
UPDATE `script_texts` SET `content_loc2` = 'Calculs des paramètres de puissance.' WHERE `sound` = 11219;
UPDATE `script_texts` SET `content_loc2` = 'L\'énergie, la puissance, mon peuple en est dépendant. Cette addiction se fit jour après la destruction du puît de soleil. Bienvenue dans l\'avenir, dommage qu\'il vous arriviez trop tard pour tout arrêter. Plus personne ne peut désormais se dresser contre moi ! Selama ashal\'anore!' WHERE `sound` = 11256;
UPDATE `script_texts` SET `content_loc2` = 'Capernian fera en sorte que vous séjour ici ne se prolonge pas.' WHERE `sound` = 11257;
UPDATE `script_texts` SET `content_loc2` = 'Bien, vous êtes dîgne de mesurer votre talent à mon maître ingénieur Télonicus' WHERE `sound` = 11258;
UPDATE `script_texts` SET `content_loc2` = 'Impréssionnant, voyons comment tiendront vos nerfs face à l\'assombrisseur Thaladred' WHERE `sound` = 11259;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez tenu tête à certain de mes plus talentueux conseillers. Mais personne ne peut résister à la puissance du marteau de sang ! Je vous présente ..le seigneur Sanguinar !' WHERE `sound` = 11260;
UPDATE `script_texts` SET `content_loc2` = 'Comme vous le voyez j\'ai plus d\'une corde à mon arc.' WHERE `sound` = 11261;
UPDATE `script_texts` SET `content_loc2` = 'Peut être vous ai-je sous estimé , il ne serait pas très loyal de vous faire combattre mes quatre conseillers en même temps. Mais mon peuple n\'a jamais été traiter avec loyauté, je ne fais que rendre la politesse.' WHERE `sound` = 11262;
UPDATE `script_texts` SET `content_loc2` = 'Il est hélas parfois nécéssaire de prendre en main les choses soit même...Balamore shanal !' WHERE `sound` = 11263;
UPDATE `script_texts` SET `content_loc2` = 'Voyons comment vous vous débrouillerez une fois la tête en bas' WHERE `sound` = 11264;
UPDATE `script_texts` SET `content_loc2` = 'On a du mal à garder les pieds sur terre ?' WHERE `sound` = 11265;
UPDATE `script_texts` SET `content_loc2` = 'Par le pouvoir du soleil !' WHERE `sound` = 11266;
UPDATE `script_texts` SET `content_loc2` = 'Anara\'nel belore !' WHERE `sound` = 11267;
UPDATE `script_texts` SET `content_loc2` = 'Obéis moi !' WHERE `sound` = 11268;
UPDATE `script_texts` SET `content_loc2` = 'Soumet toi à ma volontée !' WHERE `sound` = 11269;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne triompherez pas !' WHERE `sound` = 11270;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez jouer et perdu !' WHERE `sound` = 11271;
UPDATE `script_texts` SET `content_loc2` = 'C\'était un jeux d\'enfant.' WHERE `sound` = 11272;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis pas arrivé si loin pour échouer maintenant! Je ne laisserais pas l\'avenir que je prépare être remis en cause. Vous allez goûter à ma vraie puissance !' WHERE `sound` = 11273;
UPDATE `script_texts` SET `content_loc2` = 'Pour...Quel...Thalas..' WHERE `sound` = 11274;
UPDATE `script_texts` SET `content_loc2` = 'Contrôler les esprits faibles n\'est que l\'enfance de l\'art, car je rends allégeance à des puissance que le temps n\'atteint pas, que le destin n\'ébranle pas. Nul entitée dans ce monde ne détient la force de nous faire courber l\'échine, pas même la puissante Légion.' WHERE `sound` = 11122;
UPDATE `script_texts` SET `content_loc2` = 'Contemplez celui qui sera votre perte.' WHERE `sound` = 11123;
UPDATE `script_texts` SET `content_loc2` = 'Votre destin est écrit !' WHERE `sound` = 11124;
UPDATE `script_texts` SET `content_loc2` = 'Le chaos que j\'ai semé ici n\'est qu\'un avant goût.' WHERE `sound` = 11125;
UPDATE `script_texts` SET `content_loc2` = 'Rrrrrrr...je ne suis qu\'un parmis une multitude infinie..' WHERE `sound` = 11126;
UPDATE `script_texts` SET `content_loc2` = 'Tu feras comme je l\'ordonne faible créature.' WHERE `sound` = 11127;
UPDATE `script_texts` SET `content_loc2` = 'Ta volonté ne t\'appartiens plus.' WHERE `sound` = 11128;
UPDATE `script_texts` SET `content_loc2` = 'Déguerpissez !' WHERE `sound` = 11129;
UPDATE `script_texts` SET `content_loc2` = 'Je vous montrerais des horreurs qui dépassent vos pires cauchemars' WHERE `sound` = 11130;
UPDATE `script_texts` SET `content_loc2` = 'Nous nous étendons sur l\'univers, aussi innombrable que des étoiles !' WHERE `sound` = 11131;
UPDATE `script_texts` SET `content_loc2` = 'Par tous les grands gluants de Gnomeregan ou suis-je ? Et qui êtes-vous ? Ahhhhhh ! Ma tête ....la mère de toute les migaines..' WHERE `sound` = 11171;
UPDATE `script_texts` SET `content_loc2` = 'Pauvres petits ! Je ne sais pas qui vous êtes l\'ami mais personne ne traite le grand Milhouse Tempête-de-mana de pauvre petit ! Je n\'ai aucune idée de ce qui se passe ici mais je serais très heureux de rejoindre votre combat contre cet imbécile insolent. En garde crétin !' WHERE `sound` = 11172;
UPDATE `script_texts` SET `content_loc2` = 'Il faut juste que je fasse quelques préparatifs..Allez y commencé sans moi !..Il faut que j\'invoque un peu d\'eau..' WHERE `sound` = 11173;
UPDATE `script_texts` SET `content_loc2` = 'Génial ! Ensuite quelques sorts de protection...Voilà maintenant on peut discuter !' WHERE `sound` = 11174;
UPDATE `script_texts` SET `content_loc2` = 'Et bien sur il me faut un peu de mana, vous allez adorer ! Attendez voir..' WHERE `sound` = 11175;
UPDATE `script_texts` SET `content_loc2` = 'Ahahaha ! Voila ! Bon qui avait commandé une double portion de bottage de fesse ?' WHERE `sound` = 11176;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'ai même pas eu à bouger le petit doigt pour celui-là !' WHERE `sound` = 11177;
UPDATE `script_texts` SET `content_loc2` = 'C\'est quand vous voulez pour participer.' WHERE `sound` = 11178;
UPDATE `script_texts` SET `content_loc2` = 'Allumez le feu !! Allumez le feu !!' WHERE `sound` = 11179;
UPDATE `script_texts` SET `content_loc2` = 'Un gros cube, un petit cube, c\'est l\'heure du frégicube !' WHERE `sound` = 11180;
UPDATE `script_texts` SET `content_loc2` = 'Du soin...du soin....pour l\'amour de tout ce que ce monde a de sacré...c\'est à dire moi ! Soignez moi ! Je meurs...' WHERE `sound` = 11181;
UPDATE `script_texts` SET `content_loc2` = 'Vous aurez des nouvelles de mon avocat....' WHERE `sound` = 11182;
UPDATE `script_texts` SET `content_loc2` = 'Ce soir on vous met...ce soir on vous met le feu !' WHERE `sound` = 11183;
UPDATE `script_texts` SET `content_loc2` = 'Je savais que le prince serait en colère, mais je...je n\'étais plus moi même. Il fallait que je les relâche, le tout-puissant me parle voyez-vous. Attendez ...des étrangers...ce n\'est pas Kael Thas qui vous envoie ? Bien, il me suffira de dire au prince que c\'est vous qui avez libéré les prisonniers. Ahahahaha..' WHERE `sound` = 11222;
UPDATE `script_texts` SET `content_loc2` = 'Les Naarus gardaient certaines des créatures les plus dangeureuses de l\'univers dans ces cellules. Je vais vous en présenter une nouvelle.' WHERE `sound` = 11223;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Oui ! Encore une autre ! Votre esprit est à moi !' WHERE `sound` = 11224;
UPDATE `script_texts` SET `content_loc2` = 'Contempler cette nouvelle créature d\'une puissance incommensurable !' WHERE `sound` = 11225;
UPDATE `script_texts` SET `content_loc2` = 'Comment ça ? Un pauvre petit gnome ? Je ferais mieux la prochaine fois Ô tout puissant !' WHERE `sound` = 11226;
UPDATE `script_texts` SET `content_loc2` = 'L\'anarchie ! Le chaos le plus total ! Oh quelle grande sagesse est la votre !Oui tout est clair maintenant ! Bien sur !' WHERE `sound` = 11227;
UPDATE `script_texts` SET `content_loc2` = 'Il reste une dernière cellule...oui tout puissant...tout de suite..' WHERE `sound` = 11228;
UPDATE `script_texts` SET `content_loc2` = 'Bienvenue Ô tout-puissant, je suis votre humble serviteur.' WHERE `sound` = 11229;
UPDATE `script_texts` SET `content_loc2` = 'Que faîtes-vous ? Ce sont des spécimens très fragiles !' WHERE `sound` = 11144;
UPDATE `script_texts` SET `content_loc2` = 'Votre cycle de vie est maintenant terminé !' WHERE `sound` = 11145;
UPDATE `script_texts` SET `content_loc2` = 'Allez nourrir les vers !' WHERE `sound` = 11146;
UPDATE `script_texts` SET `content_loc2` = 'Endorel aluminor !' WHERE `sound` = 11147;
UPDATE `script_texts` SET `content_loc2` = 'La nature se plie à ma volonté.' WHERE `sound` = 11148;
UPDATE `script_texts` SET `content_loc2` = 'Il faut préserver...les spécimens..' WHERE `sound` = 11149;
UPDATE `script_texts` SET `content_loc2` = 'Gardes ! En position ! Nous avons de la visite !' WHERE `sound` = 11277;
UPDATE `script_texts` SET `content_loc2` = 'Votre présemption causera votre perte ! Garde prêter moi votre force !' WHERE `sound` = 11278;
UPDATE `script_texts` SET `content_loc2` = 'Aller tuez les ! Je ne m\'en porterais que mieux !' WHERE `sound` = 11279;
UPDATE `script_texts` SET `content_loc2` = 'Je suis plus puissant que jamais !' WHERE `sound` = 11280;
UPDATE `script_texts` SET `content_loc2` = 'Plus de savoirs ! Plus de pouvoirs !' WHERE `sound` = 11281;
UPDATE `script_texts` SET `content_loc2` = 'Racaille terrestre !' WHERE `sound` = 11282;
UPDATE `script_texts` SET `content_loc2` = 'Alana be\'lendor !' WHERE `sound` = 11283;
UPDATE `script_texts` SET `content_loc2` = 'Me voilà débarassé de vous.' WHERE `sound` = 11284;
UPDATE `script_texts` SET `content_loc2` = 'Son excellence...vous attends..' WHERE `sound` = 11285;
UPDATE `script_texts` SET `content_loc2` = 'Je ne peux pas vous laissez nous gêner.' WHERE `sound` = 11289;
UPDATE `script_texts` SET `content_loc2` = 'Ah ca va mieux ! Beaucoup mieux !' WHERE `sound` = 11290;
UPDATE `script_texts` SET `content_loc2` = 'Ils m\'ont forcés à le faire.' WHERE `sound` = 11291;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'avais pas le choix.' WHERE `sound` = 11292;
UPDATE `script_texts` SET `content_loc2` = 'Je suis ...libéré..' WHERE `sound` = 11293;
UPDATE `script_texts` SET `content_loc2` = 'Argh!!! Le poison !!' WHERE `sound` = 11297;
UPDATE `script_texts` SET `content_loc2` = 'Je vais nous débarrasser de vous !' WHERE `sound` = 11298;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne valez pas mieux qu\'eux !' WHERE `sound` = 11299;
UPDATE `script_texts` SET `content_loc2` = 'C\'est vous...la maladie...pas moi..' WHERE `sound` = 11300;
UPDATE `script_texts` SET `content_loc2` = 'Hors d\'ici elfes insignifiants je prends le contrôle !' WHERE `sound` = 11304;
UPDATE `script_texts` SET `content_loc2` = 'A chacun ses démons.' WHERE `sound` = 11305;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'ai pas mon égal !' WHERE `sound` = 11306;
UPDATE `script_texts` SET `content_loc2` = 'Péris créature mortelle !' WHERE `sound` = 11307;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Oui ! Ahahahaha !' WHERE `sound` = 11308;
UPDATE `script_texts` SET `content_loc2` = 'Enfin je suis libre ! Cela fait bien trop longtemps que j\'ai goûté à la vraie libertée !' WHERE `sound` = 11309;
UPDATE `script_texts` SET `content_loc2` = 'Enfin mon exil s\'achève !' WHERE `sound` = 11312;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Non ! Mais qu\'avez vous fait ? C\'est moi le maître ! Vous entendez !  Moi...je suis ....argh....impossible...de le retenir...' WHERE `sound` = 11313;
UPDATE `script_texts` SET `content_loc2` = 'Tue ... Tue !' WHERE `sound` = 11314;
UPDATE `script_texts` SET `content_loc2` = 'Voilà ! J\'aime ça !' WHERE `sound` = 11315;
UPDATE `script_texts` SET `content_loc2` = 'Qui est le maître maintenant ?' WHERE `sound` = 11316;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne pouvez pas me tuer imbécile ! Je reviendrais....je...arghhh !' WHERE `sound` = 11317;
UPDATE `script_texts` SET `content_loc2` = 'Que les flots des profondeurs vous emportent !' WHERE `sound` = 11321;
UPDATE `script_texts` SET `content_loc2` = 'Par les marées !' WHERE `sound` = 11322;
UPDATE `script_texts` SET `content_loc2` = 'Détruisez-les mes sujets !' WHERE `sound` = 11323;
UPDATE `script_texts` SET `content_loc2` = 'Il est impossible de m\'échapper !' WHERE `sound` = 11324;
UPDATE `script_texts` SET `content_loc2` = 'Bientôt ...ce sera terminé !' WHERE `sound` = 11325;
UPDATE `script_texts` SET `content_loc2` = 'C\'est fait !' WHERE `sound` = 11326;
UPDATE `script_texts` SET `content_loc2` = 'Lutter ne fait qu\'empirer les choses.' WHERE `sound` = 11327;
UPDATE `script_texts` SET `content_loc2` = 'Seul les plus forts survivront !' WHERE `sound` = 11328;
UPDATE `script_texts` SET `content_loc2` = 'Par les ...hauts...courants..d\'Ageon..' WHERE `sound` = 11329;
UPDATE `script_texts` SET `content_loc2` = 'L\'eau est la vie ! Elle devient une denrée rare ici en Outreterre. Une denrée que nous seuls controlerons, nous sommes les Bien-Nés et le temps est venu pour nous de reprendre enfin la place qui nous revient dans le monde.' WHERE `sound` = 11531;
UPDATE `script_texts` SET `content_loc2` = 'Je vais te déchirer de part en part !' WHERE `sound` = 11532;
UPDATE `script_texts` SET `content_loc2` = 'Victoire au seigneur Illidan !' WHERE `sound` = 11533;
UPDATE `script_texts` SET `content_loc2` = 'Je te crache dessus..racaille de la surface !' WHERE `sound` = 11534;
UPDATE `script_texts` SET `content_loc2` = 'Mort aux étrangers !' WHERE `sound` = 11535;
UPDATE `script_texts` SET `content_loc2` = 'Droit au coeur !' WHERE `sound` = 11536;
UPDATE `script_texts` SET `content_loc2` = 'File vers ta cible !' WHERE `sound` = 11537;
UPDATE `script_texts` SET `content_loc2` = 'J\'esperais ne pas devoir m\'abaisser à affrontrer des créatures de la surface. Mais vous ne me laissez pas le choix.' WHERE `sound` = 11538;
UPDATE `script_texts` SET `content_loc2` = 'L\'heure est venue ! N\'épargnez personne !' WHERE `sound` = 11539;
UPDATE `script_texts` SET `content_loc2` = 'Il faudrait peut être vous mettre à l\'abris' WHERE `sound` = 11540;
UPDATE `script_texts` SET `content_loc2` = 'Votre vie touche à sa fin.' WHERE `sound` = 11541;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez échoué.' WHERE `sound` = 11542;
UPDATE `script_texts` SET `content_loc2` = 'Bel\'amere an\'delay' WHERE `sound` = 11543;
UPDATE `script_texts` SET `content_loc2` = 'Seigneur Illidan...je suis désolée..' WHERE `sound` = 11544;
UPDATE `script_texts` SET `content_loc2` = 'Rraahhh ! J\'espèrais un vrai défi.' WHERE `sound` = 5830;
UPDATE `script_texts` SET `content_loc2` = 'Ah ! C\'est tout ?' WHERE `sound` = 5831;
UPDATE `script_texts` SET `content_loc2` = 'Lâmes de lumière !' WHERE `sound` = 5832;
UPDATE `script_texts` SET `content_loc2` = 'Que la Lumière me donne la force !' WHERE `sound` = 5833;
UPDATE `script_texts` SET `content_loc2` = 'Infidèles... ils doivent être purifiés !' WHERE `sound` = 5835;
UPDATE `script_texts` SET `content_loc2` = 'Indignes limaces.' WHERE `sound` = 5836;
UPDATE `script_texts` SET `content_loc2` = 'A vos cotés ma Dame.' WHERE `sound` = 5837;
UPDATE `script_texts` SET `content_loc2` = 'Mograine est tombé ? Vous paierez pour cette trahison !' WHERE `sound` = 5838;
UPDATE `script_texts` SET `content_loc2` = 'La Lumière a parlé !' WHERE `sound` = 5839;
UPDATE `script_texts` SET `content_loc2` = 'Que mon champion se lève !' WHERE `sound` = 5840;
UPDATE `script_texts` SET `content_loc2` = 'Venez...mourir..' WHERE `sound` = 11355;
UPDATE `script_texts` SET `content_loc2` = 'Cavalez..' WHERE `sound` = 11356;
UPDATE `script_texts` SET `content_loc2` = 'On ne s\'échappe pas..' WHERE `sound` = 11357;
UPDATE `script_texts` SET `content_loc2` = 'Reste la..' WHERE `sound` = 11358;
UPDATE `script_texts` SET `content_loc2` = 'Prie..pour ta vie..' WHERE `sound` = 11359;
UPDATE `script_texts` SET `content_loc2` = 'Finis..' WHERE `sound` = 11360;
UPDATE `script_texts` SET `content_loc2` = 'Indigne...' WHERE `sound` = 11361;
UPDATE `script_texts` SET `content_loc2` = 'Meurs...' WHERE `sound` = 11362;
UPDATE `script_texts` SET `content_loc2` = 'Urghhh....!!' WHERE `sound` = 11363;
UPDATE `script_texts` SET `content_loc2` = 'Les Gronns sont la seule vraie puissance de l\'Outreterre !' WHERE `sound` = 11367;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne terrasserez pas la main de Gruul !' WHERE `sound` = 11368;
UPDATE `script_texts` SET `content_loc2` = 'Tuez le suivant sera pas si facile !' WHERE `sound` = 11369;
UPDATE `script_texts` SET `content_loc2` = 'Ahaha ! Ca ne prouve rien !' WHERE `sound` = 11370;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai pas peur de vous !' WHERE `sound` = 11371;
UPDATE `script_texts` SET `content_loc2` = 'Bien ! Maintenant c\'est à moi !' WHERE `sound` = 11372;
UPDATE `script_texts` SET `content_loc2` = 'T\'es pas si solide en fait !' WHERE `sound` = 11373;
UPDATE `script_texts` SET `content_loc2` = 'Mouhahahahahaha !' WHERE `sound` = 11374;
UPDATE `script_texts` SET `content_loc2` = 'Maulgar est roi !' WHERE `sound` = 11375;
UPDATE `script_texts` SET `content_loc2` = 'Gruul....vous écrasera..' WHERE `sound` = 11376;
UPDATE `script_texts` SET `content_loc2` = 'Je ne tiendrais pas très longtemps' WHERE `sound` = 11385;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Pas encore !' WHERE `sound` = 11386;
UPDATE `script_texts` SET `content_loc2` = 'Prenez garde ! Je suis vivant !' WHERE `sound` = 11399;
UPDATE `script_texts` SET `content_loc2` = 'C\'est stupide !' WHERE `sound` = 11400;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahahaha !' WHERE `sound` = 11401;
UPDATE `script_texts` SET `content_loc2` = 'Assez ! Terminer !' WHERE `sound` = 11402;
UPDATE `script_texts` SET `content_loc2` = 'A genou !' WHERE `sound` = 11403;
UPDATE `script_texts` SET `content_loc2` = 'Je ne vous...laisserais pas...m\'oublier !' WHERE `sound` = 11404;
UPDATE `script_texts` SET `content_loc2` = 'Prenez garde pleutre !' WHERE `sound` = 11405;
UPDATE `script_texts` SET `content_loc2` = 'Vous pouvez avoir tout ce que vous désirez...en y mettant le prix.' WHERE `sound` = 11408;
UPDATE `script_texts` SET `content_loc2` = 'Le bonheur est à portée de main.' WHERE `sound` = 11409;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Vous allez rester avec nous maintenant.' WHERE `sound` = 11410;
UPDATE `script_texts` SET `content_loc2` = 'Méfiez-vous de ce que vous désirez.' WHERE `sound` = 11411;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez les yeux plus gros que le ventre.' WHERE `sound` = 11412;
UPDATE `script_texts` SET `content_loc2` = 'Je vous attendrai' WHERE `sound` = 11413;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serai jamais loin' WHERE `sound` = 11414;
UPDATE `script_texts` SET `content_loc2` = 'Douleurs et souffrances ! Voilà tout ce qui vous attends.' WHERE `sound` = 11415;
UPDATE `script_texts` SET `content_loc2` = 'Ne me laissez pas seul !' WHERE `sound` = 11416;
UPDATE `script_texts` SET `content_loc2` = 'Regardez ce que vous m\'avez fait faire !' WHERE `sound` = 11417;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'ai pas demandé ça !' WHERE `sound` = 11418;
UPDATE `script_texts` SET `content_loc2` = 'La douleur ne fait que commencer !' WHERE `sound` = 11419;
UPDATE `script_texts` SET `content_loc2` = 'Je ne veux pas y retourner !' WHERE `sound` = 11420;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que je fais maintenant ?' WHERE `sound` = 11421;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai mieux à faire !' WHERE `sound` = 11422;
UPDATE `script_texts` SET `content_loc2` = 'Selama am\'oronor !' WHERE `sound` = 11423;
UPDATE `script_texts` SET `content_loc2` = 'Bien joué !' WHERE `sound` = 11424;
UPDATE `script_texts` SET `content_loc2` = 'Seigneur Illidan je..' WHERE `sound` = 11425;
UPDATE `script_texts` SET `content_loc2` = 'Savourez vos derniers instants.' WHERE `sound` = 11426;
UPDATE `script_texts` SET `content_loc2` = 'Vous êtes à moi !' WHERE `sound` = 11427;
UPDATE `script_texts` SET `content_loc2` = 'Assez jouer !' WHERE `sound` = 11428;
UPDATE `script_texts` SET `content_loc2` = 'La horde ...va...vous écrasez !' WHERE `sound` = 11432;
UPDATE `script_texts` SET `content_loc2` = 'Au banquet !' WHERE `sound` = 11433;
UPDATE `script_texts` SET `content_loc2` = 'Encore ! J\'en veux encore !' WHERE `sound` = 11434;
UPDATE `script_texts` SET `content_loc2` = 'Boire votre sang ! Mangez votre chair !' WHERE `sound` = 11435;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai grand faim !' WHERE `sound` = 11436;
UPDATE `script_texts` SET `content_loc2` = 'Ahhhhhh Rrrrrr !!' WHERE `sound` = 11437;
UPDATE `script_texts` SET `content_loc2` = 'Beuarghhhh ! Je vais arracher la chair de vos os !' WHERE `sound` = 11438;
UPDATE `script_texts` SET `content_loc2` = 'Arrgggghhhh !!!' WHERE `sound` = 11439;
UPDATE `script_texts` SET `content_loc2` = 'Allons donc quelle grossieretée ! Bandal !' WHERE `sound` = 11440;
UPDATE `script_texts` SET `content_loc2` = 'Shorel\'aran' WHERE `sound` = 11441;
UPDATE `script_texts` SET `content_loc2` = 'Belasa menoor!' WHERE `sound` = 11442;
UPDATE `script_texts` SET `content_loc2` = 'Diel ma\'ahn...oreindel\'o' WHERE `sound` = 11443;
UPDATE `script_texts` SET `content_loc2` = 'Diel fin\'al' WHERE `sound` = 11444;
UPDATE `script_texts` SET `content_loc2` = 'Sha\'amoor ara mashal ?' WHERE `sound` = 11445;
UPDATE `script_texts` SET `content_loc2` = 'Sha\'amoor sine menoor !' WHERE `sound` = 11446;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez mourir au nom de Dame Vashj !' WHERE `sound` = 11450;
UPDATE `script_texts` SET `content_loc2` = 'Restez la !' WHERE `sound` = 11451;
UPDATE `script_texts` SET `content_loc2` = 'Je m\'occuperai de vous tout à l\'heure.' WHERE `sound` = 11452;
UPDATE `script_texts` SET `content_loc2` = 'Bel\'anen dal\'lorei!' WHERE `sound` = 11453;
UPDATE `script_texts` SET `content_loc2` = 'Le sang va couler !' WHERE `sound` = 11454;
UPDATE `script_texts` SET `content_loc2` = 'Votre reussite n\'aura pas durer !' WHERE `sound` = 11455;
UPDATE `script_texts` SET `content_loc2` = 'Il est temps pour vous de partir..' WHERE `sound` = 11456;
UPDATE `script_texts` SET `content_loc2` = 'Bal\'amer ch\'itah !' WHERE `sound` = 11457;
UPDATE `script_texts` SET `content_loc2` = 'Ma puissance a ses limites ! Meurs ! Meurs !' WHERE `sound` = 11458;
UPDATE `script_texts` SET `content_loc2` = 'Le seigneur Illidan va vous écrasez..' WHERE `sound` = 11459;
UPDATE `script_texts` SET `content_loc2` = 'Fuyez ou mourez !' WHERE `sound` = 11482;
UPDATE `script_texts` SET `content_loc2` = 'Mon travail est terminé.' WHERE `sound` = 11483;
UPDATE `script_texts` SET `content_loc2` = 'Comme il convient.' WHERE `sound` = 11484;
UPDATE `script_texts` SET `content_loc2` = 'Le destin..attends..' WHERE `sound` = 11485;
UPDATE `script_texts` SET `content_loc2` = 'Pas de seconde chance !' WHERE `sound` = 11486;
UPDATE `script_texts` SET `content_loc2` = 'Je suis pleine de surprise.' WHERE `sound` = 11487;
UPDATE `script_texts` SET `content_loc2` = 'Pour Quel\'Thalas ! Pour le puit de soleil !' WHERE `sound` = 11488;
UPDATE `script_texts` SET `content_loc2` = 'Vous jouez vous payez.' WHERE `sound` = 11501;
UPDATE `script_texts` SET `content_loc2` = 'Pas très impressionnant.' WHERE `sound` = 11502;
UPDATE `script_texts` SET `content_loc2` = 'Vous vous amusez bien ?' WHERE `sound` = 11503;
UPDATE `script_texts` SET `content_loc2` = 'Alors...vous êtes en vacance ?' WHERE `sound` = 11504;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez l\'air un peu tendu.' WHERE `sound` = 11505;
UPDATE `script_texts` SET `content_loc2` = 'Soyez pas timide.' WHERE `sound` = 11506;
UPDATE `script_texts` SET `content_loc2` = 'Je suis...toute à vous..' WHERE `sound` = 11507;
UPDATE `script_texts` SET `content_loc2` = 'Un de perdu dix de retrouvé.' WHERE `sound` = 11508;
UPDATE `script_texts` SET `content_loc2` = 'Les histoires d\'amours finissent mal en général.' WHERE `sound` = 11509;
UPDATE `script_texts` SET `content_loc2` = 'Arretez de jouer avec mes sentiments !' WHERE `sound` = 11510;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'avais pas terminée !' WHERE `sound` = 11511;
UPDATE `script_texts` SET `content_loc2` = 'J\'étais le premier vous savez...la roue de mon destin a fait tellement de tour...ahahaha..il s\'est écoulé tant de temps...j\'ai beaucoup a rattraper.' WHERE `sound` = 11512;
UPDATE `script_texts` SET `content_loc2` = 'A moi la vengeance !' WHERE `sound` = 11513;
UPDATE `script_texts` SET `content_loc2` = 'Vous me serez utile.' WHERE `sound` = 11514;
UPDATE `script_texts` SET `content_loc2` = 'Le pire est à venir.' WHERE `sound` = 11515;
UPDATE `script_texts` SET `content_loc2` = 'La mort..hahahaha...ce n\'est pas si terrible.' WHERE `sound` = 11516;
UPDATE `script_texts` SET `content_loc2` = 'De quoi avez-vous peur ?' WHERE `sound` = 11517;
UPDATE `script_texts` SET `content_loc2` = 'Laissez tomber.' WHERE `sound` = 11518;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai quelque chose pour vous.' WHERE `sound` = 11519;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez être un peu plus respectueux !' WHERE `sound` = 11520;
UPDATE `script_texts` SET `content_loc2` = 'La roue...tourne...encore..' WHERE `sound` = 11521;
UPDATE `script_texts` SET `content_loc2` = 'Vous voulez me tester ?' WHERE `sound` = 11524;
UPDATE `script_texts` SET `content_loc2` = 'Bel effort.' WHERE `sound` = 11525;
UPDATE `script_texts` SET `content_loc2` = 'Quel glorieux coup de grâce.' WHERE `sound` = 11526;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez... de la chance...' WHERE `sound` = 11527;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'êtes pas taillé pour ça !' WHERE `sound` = 11528;
UPDATE `script_texts` SET `content_loc2` = 'Anar\'alah belore !' WHERE `sound` = 11529;
UPDATE `script_texts` SET `content_loc2` = 'Vous voulez me tuer ? Ahahah ! Vous d\'abord !' WHERE `sound` = 11530;
UPDATE `script_texts` SET `content_loc2` = 'Les esprits du vent ! Y vont être votre fin !' WHERE `sound` = 12031;
UPDATE `script_texts` SET `content_loc2` = 'Je vais vous cramer !' WHERE `sound` = 12032;
UPDATE `script_texts` SET `content_loc2` = 'Sont ou mes perce coques ? Au boulot faut que ça éclose !' WHERE `sound` = 12033;
UPDATE `script_texts` SET `content_loc2` = 'J\'vais vous montrer la force du nombre.' WHERE `sound` = 12034;
UPDATE `script_texts` SET `content_loc2` = 'Le temps il est écoulé !' WHERE `sound` = 12035;
UPDATE `script_texts` SET `content_loc2` = 'C\'est finis pour toi !' WHERE `sound` = 12036;
UPDATE `script_texts` SET `content_loc2` = 'Tazaga-choo!' WHERE `sound` = 12037;
UPDATE `script_texts` SET `content_loc2` = 'Zul\'Jin...Il a une surprise pour vous !' WHERE `sound` = 12038;
UPDATE `script_texts` SET `content_loc2` = 'Venez étranger ! L\'esprit du faucon-dragon il a faim d\'âme honorable.' WHERE `sound` = 12039;
UPDATE `script_texts` SET `content_loc2` = 'Venez mes amis ! Vos corps y vont nourrir mes petits ! Vos âmes elles vont me donner la puissance !' WHERE `sound` = 12040;
UPDATE `script_texts` SET `content_loc2` = 'Gardes ! Bougez-vous ! C\'est l\'heure du massacre !' WHERE `sound` = 12066;
UPDATE `script_texts` SET `content_loc2` = 'Gardes ! Allez ! C\'est quoi qui vous fait le plus peur hein ? Eux ou moi ?' WHERE `sound` = 12067;
UPDATE `script_texts` SET `content_loc2` = 'Au galop ! Et rapporter moi des têtes.' WHERE `sound` = 12068;
UPDATE `script_texts` SET `content_loc2` = 'Oh ! Je vais perdre ma patience ! Allez et faites leur regretter d\'être né ! ' WHERE `sound` = 12069;
UPDATE `script_texts` SET `content_loc2` = 'Vous serez mort bien vite !' WHERE `sound` = 12070;
UPDATE `script_texts` SET `content_loc2` = 'Ca va faire mal !' WHERE `sound` = 12071;
UPDATE `script_texts` SET `content_loc2` = 'Vous demandez la bête ? Je vais vous donnez la bête !' WHERE `sound` = 12072;
UPDATE `script_texts` SET `content_loc2` = 'Place ! Voilà le Nalorakk !' WHERE `sound` = 12073;
UPDATE `script_texts` SET `content_loc2` = 'C\'était votre chance ! Maintenant c\'est trop tard !' WHERE `sound` = 12074;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahaha ! Alors qu\'est ce que t\'as à dire hein ?' WHERE `sound` = 12075;
UPDATE `script_texts` SET `content_loc2` = 'Les Amanis ..ils vont régner à nouveau !' WHERE `sound` = 12076;
UPDATE `script_texts` SET `content_loc2` = 'Je vous attendrai de l\'autre côté.' WHERE `sound` = 12077;
UPDATE `script_texts` SET `content_loc2` = 'Argh...y a quoi que mieux que celle de l\'esprit de l\'ours pour l\'éternité ? Approchez maintenant ! Venez me donner vos âmes !' WHERE `sound` = 12078;
UPDATE `script_texts` SET `content_loc2` = 'J\'vous sens étranger ! Essayez pas de retarder votre destin ! Venez à moi maintenant et le sacrifice y sera rapide !' WHERE `sound` = 12079;
UPDATE `script_texts` SET `content_loc2` = 'Vous me faites perdre mon temps.' WHERE `sound` = 12378;
UPDATE `script_texts` SET `content_loc2` = 'Ma faim n\'a pas de limite !' WHERE `sound` = 12381;
UPDATE `script_texts` SET `content_loc2` = 'Hum..Oui ! Je suis un dieu !' WHERE `sound` = 12382;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Encore ! Il m\'en faut encore !' WHERE `sound` = 12383;
UPDATE `script_texts` SET `content_loc2` = 'Je suis invincible !' WHERE `sound` = 12385;
UPDATE `script_texts` SET `content_loc2` = 'Assez de distraction !' WHERE `sound` = 12388;
UPDATE `script_texts` SET `content_loc2` = 'Draiiiiii.....nerrrrrr.....viiiieee' WHERE `sound` = 12389;
UPDATE `script_texts` SET `content_loc2` = 'Liiiiii.....béééééé.......réééééé' WHERE `sound` = 12390;
UPDATE `script_texts` SET `content_loc2` = 'Irrrrr......rrréééé....préééééé....ssssiiii.....bleeee' WHERE `sound` = 12392;
UPDATE `script_texts` SET `content_loc2` = 'Cooooooonnnn.....sssuuuuuuu.....mmmmeeeeezzz !' WHERE `sound` = 12393;
UPDATE `script_texts` SET `content_loc2` = 'Exterminez les !' WHERE `sound` = 12395;
UPDATE `script_texts` SET `content_loc2` = 'Ce n\'était pas...prévu..' WHERE `sound` = 12397;
UPDATE `script_texts` SET `content_loc2` = 'Comme c\'est horrible !' WHERE `sound` = 12398;
UPDATE `script_texts` SET `content_loc2` = 'Hé bien quelle chance !' WHERE `sound` = 12400;
UPDATE `script_texts` SET `content_loc2` = 'La ça commence à m\'exaspérée !' WHERE `sound` = 12401;
UPDATE `script_texts` SET `content_loc2` = 'Maudit laquais ! Je vous achèverai moi même !' WHERE `sound` = 12403;
UPDATE `script_texts` SET `content_loc2` = 'C\'est ce que j\'appelle un bon début.' WHERE `sound` = 12405;
UPDATE `script_texts` SET `content_loc2` = 'J\'aurais jurer que vous étiez plus nombreux.' WHERE `sound` = 12407;
UPDATE `script_texts` SET `content_loc2` = 'On ne peut plus vraiment parler de groupe non ?' WHERE `sound` = 12409;
UPDATE `script_texts` SET `content_loc2` = 'Que ce nombre un est solitaire.' WHERE `sound` = 12410;
UPDATE `script_texts` SET `content_loc2` = 'C\'était très sympa ! Vraiment !' WHERE `sound` = 12411;
UPDATE `script_texts` SET `content_loc2` = 'Ne prenez pas un air si satisfait. Je sais à quoi vous pensez, mais le donjon de la tempête n\'était qu\'un contretemps. Croyez-vous vraiment que je confierais notre avenir à un aveugle ? Un batard demi elfe de la nuit?  Ahahaha ! Oh non ! Ce n\'était qu\'une étape vers une projet plus global ! C\'est ce qui vous amène ici. Et cette fois vous ne vous en mêlerez pas !' WHERE `sound` = 12413;
UPDATE `script_texts` SET `content_loc2` = 'La vengeance brûle !' WHERE `sound` = 12415;
UPDATE `script_texts` SET `content_loc2` = 'Felomin ashal !' WHERE `sound` = 12417;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez me trouver renversant !' WHERE `sound` = 12418;
UPDATE `script_texts` SET `content_loc2` = 'Maître ! Donne moi la force !' WHERE `sound` = 12419;
UPDATE `script_texts` SET `content_loc2` = 'Ne vous sentez pas...trop à l\'aise !' WHERE `sound` = 12420;
UPDATE `script_texts` SET `content_loc2` = 'Ma chute n\'y changera rien ! Le maître vous aura ! Vous vous noierez dans votre propre sang ! Ce monde brulera ! Ahhhhhhh !!' WHERE `sound` = 12421;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serais plus jamais l\'esclave de Malygos ! Osez me défier et vous serez détruit !' WHERE `sound` = 12422;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez expier !' WHERE `sound` = 12423;
UPDATE `script_texts` SET `content_loc2` = 'La souffrance ne fait que commencer !' WHERE `sound` = 12424;
UPDATE `script_texts` SET `content_loc2` = 'Au nom de Kil\'Jaeden !' WHERE `sound` = 12425;
UPDATE `script_texts` SET `content_loc2` = 'Vous étiez prévenu !' WHERE `sound` = 12426;
UPDATE `script_texts` SET `content_loc2` = 'Mon réveil est total ! Vous allez tous mourir !' WHERE `sound` = 12427;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai besoin...de votre aide...je ne tiendrai ...pas longtemps...' WHERE `sound` = 12428;
UPDATE `script_texts` SET `content_loc2` = 'Arghhhh ! Aidez moi je vais perdre l\'esprit !' WHERE `sound` = 12429;
UPDATE `script_texts` SET `content_loc2` = 'Vite ! C\'est en train de m\'emporter !' WHERE `sound` = 12430;
UPDATE `script_texts` SET `content_loc2` = 'Je vous suis redevable à jamais et lorsque nous aurons triomphé de Kil\'Jaeden le monde entier vous sera redevable également.' WHERE `sound` = 12431;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahahaha ! Il n\'y aura pas de sursis ! Mon travail ici est presque terminé !' WHERE `sound` = 12451;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis jamais du côté des perdants !' WHERE `sound` = 12452;
UPDATE `script_texts` SET `content_loc2` = 'Je me delecte de votre détresse.' WHERE `sound` = 12453;
UPDATE `script_texts` SET `content_loc2` = 'Que coule votre sang !' WHERE `sound` = 12454;
UPDATE `script_texts` SET `content_loc2` = 'Bel être mortel !' WHERE `sound` = 12455;
UPDATE `script_texts` SET `content_loc2` = 'On ne vous avait pas dit ? Je gagne toujours !' WHERE `sound` = 12456;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai assez joué avec vous !' WHERE `sound` = 12457;
UPDATE `script_texts` SET `content_loc2` = 'Misérable lézard ! La mort est la seule réponse que tu trouvera ici !' WHERE `sound` = 12458;
UPDATE `script_texts` SET `content_loc2` = 'Ta magie est faible !' WHERE `sound` = 12459;
UPDATE `script_texts` SET `content_loc2` = 'Je vais t\'écraser !' WHERE `sound` = 12460;
UPDATE `script_texts` SET `content_loc2` = 'C\'était marrant mais j\'attend toujours un réél défi !' WHERE `sound` = 12461;
UPDATE `script_texts` SET `content_loc2` = 'Venez tenter votre chance !' WHERE `sound` = 12462;
UPDATE `script_texts` SET `content_loc2` = 'Rahhhh ! Encore des agneaux pour l\'abattoir !' WHERE `sound` = 12463;
UPDATE `script_texts` SET `content_loc2` = 'Meurs insecte !' WHERE `sound` = 12464;
UPDATE `script_texts` SET `content_loc2` = 'Viande froide !' WHERE `sound` = 12465;
UPDATE `script_texts` SET `content_loc2` = 'Trop facile !' WHERE `sound` = 12466;
UPDATE `script_texts` SET `content_loc2` = 'Donnez moi de l\'action !' WHERE `sound` = 12467;
UPDATE `script_texts` SET `content_loc2` = 'A chaque jour son glorieu combat !' WHERE `sound` = 12468;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne savez rien de la puissance.' WHERE `sound` = 12469;
UPDATE `script_texts` SET `content_loc2` = 'Vous appellez ça un réel défi ? Mourez !' WHERE `sound` = 12470;
UPDATE `script_texts` SET `content_loc2` = 'Argh ! Bien joué ! Ca devient enfin interessant...' WHERE `sound` = 12471;
UPDATE `script_texts` SET `content_loc2` = 'Attendez mes amis ! Ce démon doit nous renseigner avant de recevoir son due' WHERE `sound` = 12472;
UPDATE `script_texts` SET `content_loc2` = 'Ou est Anveena démon ? Qu\'est il devenu de Kalec ?' WHERE `sound` = 12473;
UPDATE `script_texts` SET `content_loc2` = 'Tu vas me dire ou ils sont !' WHERE `sound` = 12474;
UPDATE `script_texts` SET `content_loc2` = 'Parle ça n\'a que trop duré !' WHERE `sound` = 12475;
UPDATE `script_texts` SET `content_loc2` = 'Malygos ! Seigneur ! J\'ai fais de mon mieux !' WHERE `sound` = 12476;
UPDATE `script_texts` SET `content_loc2` = 'Qui trouble ce sanctuaire ?' WHERE `sound` = 11230;
UPDATE `script_texts` SET `content_loc2` = 'Vous devez mourir...hum attendez ..ce n\'est pas ! Si ! Vous devez mourir !' WHERE `sound` = 11231;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que je fais ? Pourquoi est ce que..?' WHERE `sound` = 11232;
UPDATE `script_texts` SET `content_loc2` = 'A moi mes enfants.' WHERE `sound` = 11233;
UPDATE `script_texts` SET `content_loc2` = 'Peut être n\'est ce pas....Non, nous nous battrons, venez à moi!' WHERE `sound` = 11234;
UPDATE `script_texts` SET `content_loc2` = 'Je suis si troublé...ce n\'est pas ..ma place..' WHERE `sound` = 11235;
UPDATE `script_texts` SET `content_loc2` = 'Vous là ! Occupez-vous de ce bruit bizarre.' WHERE `sound` = 5775;
UPDATE `script_texts` SET `content_loc2` = 'Nous sommes attaqués ! Repoussez les envahisseurs !' WHERE `sound` = 5777;
UPDATE `script_texts` SET `content_loc2` = 'L\'heure est venue ! Gul\'dan, ordonne à tes démonistes de redoubler leurs efforts ! Le portail va s\'ouvrir dans quelques instants et ta horde pourra se déchaîner sur ce monde riche et sans défense !' WHERE `sound` = 10435;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que c\'est ? Des champions ? Qui viennent pour m\'aider ? Je sens la l\'influence du ténébreux cet évènement porte clairement sa bénédiction.' WHERE `sound` = 10436;
UPDATE `script_texts` SET `content_loc2` = 'Champions, mon bouclier s\'affaiblit !' WHERE `sound` = 10437;
UPDATE `script_texts` SET `content_loc2` = 'Mes pouvoirs doivent se concentrer sur la porte ! Je n\'ai pas le temps de renforcer le bouclier !' WHERE `sound` = 10438;
UPDATE `script_texts` SET `content_loc2` = 'Le bouclier est presque détruit ! Tout ceux à quoi j\'ai oeuvré est en péril !' WHERE `sound` = 10439;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Maudite soit cette enveloppe mortelle ...' WHERE `sound` = 10441;
UPDATE `script_texts` SET `content_loc2` = 'Je vous suis reconnaissant, champions. Maintenant, la horde de Gul\'dan va pouvoir balayer ce monde comme une nuée de sauterelle et tout mes plans préparés avec soin vont enfin arriver à leur terme !' WHERE `sound` = 10440;


/** SANS SOUND **/
UPDATE `script_texts` SET `content_loc2` = 'Venez, mes petits. Affrontez-moi !' WHERE `entry` = -1000100;
UPDATE `script_texts` SET `content_loc2` = 'Merci de m\'avoir libéré, je vais ouvrir cette porte pour vous, ensuite je sortirai d\'ici.' WHERE `entry` = -1033000;
UPDATE `script_texts` SET `content_loc2` = 'Quelle chance. D\'habitude je dois quitter mon antre pour me nourrir.' WHERE `entry` = -1249000;
UPDATE `script_texts` SET `content_loc2` = 'Restez à votre place mortels !' WHERE `entry` = -1249001;
UPDATE `script_texts` SET `content_loc2` = 'Les efforts inutiles m\'ennuie. Je vais vous incinérer depuis les airs.' WHERE `entry` = -1249002;
UPDATE `script_texts` SET `content_loc2` = 'On dirait que vous avez besoin d\'une nouvelle leçon, mortels !' WHERE `entry` = -1249003;
UPDATE `script_texts` SET `content_loc2` = 'prend une grande inspiration.' WHERE `entry` = -1249004;
UPDATE `script_texts` SET `content_loc2` = 'La sérénitée...enfin !' WHERE `entry` = -1309001;
UPDATE `script_texts` SET `content_loc2` = 'Je vous ordonne de faire pleuvoir le feu sur ses intrus !' WHERE `entry` = -1309003;
UPDATE `script_texts` SET `content_loc2` = 'Shadra, fais de moi ton avatar !' WHERE `entry` = -1309006;
UPDATE `script_texts` SET `content_loc2` = 'Aide-moi ma couvée !' WHERE `entry` = -1309007;
UPDATE `script_texts` SET `content_loc2` = 'Faites de $N votre festin, mes jolies !' WHERE `entry` = -1309012;
UPDATE `script_texts` SET `content_loc2` = 'DING !' WHERE `entry` = -1309016;
UPDATE `script_texts` SET `content_loc2` = 'GRATS !' WHERE `entry` = -1309017;
UPDATE `script_texts` SET `content_loc2` = 'Je garde un oeil sur vous, $N !' WHERE `entry` = -1309018;
UPDATE `script_texts` SET `content_loc2` = 'Ne me mettez pas en colère. Vous n\'allez pas aimer quand je suis colère.' WHERE `entry` = -1309019;
UPDATE `script_texts` SET `content_loc2` = 'Voler ne vous rendra pas meilleur, mortels !' WHERE `entry` = -1309021;
UPDATE `script_texts` SET `content_loc2` = 'Vous osez mettre les pieds sur la terre sainte des Hakkari ? Serviteurs d\'Hakkar, détruisez les infidèles !' WHERE `entry` = -1309022;
UPDATE `script_texts` SET `content_loc2` = 'Serviteurs d\'Hakkar, entendez votre Dieu. La quiétude de ce temple a été profané. Des intrus ont pénétrés sur notre sol sacré! L\'Avatar du Sang doit être protéger. Tuez les tous !' WHERE `entry` = -1309023;
UPDATE `script_texts` SET `content_loc2` = 'accompli son dernier devoir pour Ragnaros' WHERE `entry` = -1409000;
UPDATE `script_texts` SET `content_loc2` = 'entre dans une frénésie meurtrière' WHERE `entry` = -1409001;
UPDATE `script_texts` SET `content_loc2` = 'refuse de mourir pendant que son maître est en danger.' WHERE `entry` = -1409002;
UPDATE `script_texts` SET `content_loc2` = 'Dans ce monde où le temps est votre ennemie, il est mon plus grand allié. Le grand jeu de la vie dans lequel vous pensiez jouer est n fait en train de se jouer de vous. A cela je dis...' WHERE `entry` = -1469004;
UPDATE `script_texts` SET `content_loc2` = 'rentre en pleine frénésie !' WHERE `entry` = -1469031;
UPDATE `script_texts` SET `content_loc2` = 'sens votre peur.' WHERE `entry` = -1509000;
UPDATE `script_texts` SET `content_loc2` = 'pose son regard sur $N' WHERE `entry` = -1509002;
UPDATE `script_texts` SET `content_loc2` = 'Ils arrivent maintenant. Essayez de ne pas vous faire tuer, sang frais.' WHERE `entry` = -1509003;
UPDATE `script_texts` SET `content_loc2` = 'Tu te rappelles, Rajaxx, quand je disais que je te tuerai en dernier ? J\'ai menti...' WHERE `entry` = -1509004;
UPDATE `script_texts` SET `content_loc2` = 'Bientôt vous allez connaître le prix de votre ingérence, mortels...Le maître est bientôt de retour .... Et quand il va se relever, votre monde cessera !' WHERE `entry` = -1509017;
UPDATE `script_texts` SET `content_loc2` = 'est affaibli !' WHERE `entry` = -1531011;
UPDATE `script_texts` SET `content_loc2` = 'commence à rouiller.' WHERE `entry` = -1532038;
UPDATE `script_texts` SET `content_loc2` = 'commence à incanter une nova de glace' WHERE `entry` = -1544013;
UPDATE `script_texts` SET `content_loc2` = 'les liens commencent à s\'affaiblir' WHERE `entry` = -1544014;
UPDATE `script_texts` SET `content_loc2` = 'enrage.' WHERE `entry` = -1540041;
UPDATE `script_texts` SET `content_loc2` = 'Venez intrus...' WHERE `entry` = -1542008;
UPDATE `script_texts` SET `content_loc2` = 'Est ce que vous sentez ça ? La viande fraîche se fait rare dans notre citadel. Mefiez-vous de tous les envahisseurs.' WHERE `entry` = -1543000;
UPDATE `script_texts` SET `content_loc2` = 'devient enragé !' WHERE `entry` = -1544012;
UPDATE `script_texts` SET `content_loc2` = 'envoie ses ennemies vers leurs tombes aquatiques !' WHERE `entry` = -1548039;
UPDATE `script_texts` SET `content_loc2` = 'Le violent tremblement de terre a alerté les murlocs proche !' WHERE `entry` = -1548040;
UPDATE `script_texts` SET `content_loc2` = 'invoque des globes d\'eau' WHERE `entry` = -1548041;
UPDATE `script_texts` SET `content_loc2` = 'J\'en ai assez de tout ça ! Maintenant j\'en appelle a la fureur du cosmos lui même.' WHERE `entry` = -1550014;
UPDATE `script_texts` SET `content_loc2` = 'Je ne fais plus qu\'un...avec le VIDE ! ' WHERE `entry` = -1550015;
UPDATE `script_texts` SET `content_loc2` = 'pose son regard sur $N !' WHERE `entry` = -1550037;
UPDATE `script_texts` SET `content_loc2` = 'émet des sons étranges.' WHERE `entry` = -1553006;
UPDATE `script_texts` SET `content_loc2` = 'lève son marteau d\'un air menaçant..' WHERE `entry` = -1554012;
UPDATE `script_texts` SET `content_loc2` = 'attire l\'énergie depuis les airs.' WHERE `entry` = -1555036;
UPDATE `script_texts` SET `content_loc2` = 'bascule dans le vide..' WHERE `entry` = -1557014;
UPDATE `script_texts` SET `content_loc2` = '%s acquiert une nouvelle cible !' WHERE `entry` = -1564010;
UPDATE `script_texts` SET `content_loc2` = '%s frappe le sol avec colère !' WHERE `entry` = -1564011;
UPDATE `script_texts` SET `content_loc2` = 'Le sol commence à s\'ouvrir !' WHERE `entry` = -1564012;
UPDATE `script_texts` SET `content_loc2` = 'Sortez de l\'ombre ! Je suis revenue pour vous guider contre notre vrai ennemie ! Brisez vos chaînes et levez les armes contre notre maître Illidari !' WHERE `entry` = -1564015;
UPDATE `script_texts` SET `content_loc2` = 'Pour notre leader ! Pour Akama !' WHERE `entry` = -1564016;
UPDATE `script_texts` SET `content_loc2` = 'Pour Akama !' WHERE `entry` = -1564017;
UPDATE `script_texts` SET `content_loc2` = '%s devient enragé !' WHERE `entry` = -1564054;
UPDATE `script_texts` SET `content_loc2` = 'devient plus grand !' WHERE `entry` = -1565019;
UPDATE `script_texts` SET `content_loc2` = 'commence à canaliser l\'énergie du Gangrecristal proche...' WHERE `entry` = -1585006;
UPDATE `script_texts` SET `content_loc2` = 'décharge de pure énergie !' WHERE `entry` = -1585011;
UPDATE `script_texts` SET `content_loc2` = 'Suivez moi, $N. Je vais vous conduire à la cachette des Défias. Mais vous feriez mieux de me protéger ou je serai bientôt mort.' WHERE `entry` = -1000101;
UPDATE `script_texts` SET `content_loc2` = 'L\'entrée est cachée ici dans Ruisselune. Gardez vos yeux grand ouvert à cause des voleurs. Ils me veulent mort.' WHERE `entry` = -1000102;
UPDATE `script_texts` SET `content_loc2` = 'Vous pouvez aller dire à Roidemantel que c\'est ici que le gang Défias se terre, $N.' WHERE `entry` = -1000103;
UPDATE `script_texts` SET `content_loc2` = '%s venez en vitesse ! Préparez vous à combattre !' WHERE `entry` = -1000104;
UPDATE `script_texts` SET `content_loc2` = 'A l\'aide !' WHERE `entry` = -1000105;
UPDATE `script_texts` SET `content_loc2` = 'Tous le modne est prêt ?' WHERE `entry` = -1000106;
UPDATE `script_texts` SET `content_loc2` = 'D\'accord, allons-y !' WHERE `entry` = -1000107;
UPDATE `script_texts` SET `content_loc2` = 'Tenez vous prêt. Aile-argent est juste après cette courbe.' WHERE `entry` = -1000108;
UPDATE `script_texts` SET `content_loc2` = 'Aile-Argent est à nous !' WHERE `entry` = -1000109;
UPDATE `script_texts` SET `content_loc2` = 'Aller faire votre rapport et dits que l\'avant-poste est à nous. Nous, nous resterons ici.' WHERE `entry` = -1000110;
UPDATE `script_texts` SET `content_loc2` = 'Notre maison est par ici, à travers le bosquet.' WHERE `entry` = -1000111;
UPDATE `script_texts` SET `content_loc2` = 'Aidez-moi !' WHERE `entry` = -1000112;
UPDATE `script_texts` SET `content_loc2` = 'Ma pauvre famille. Tout a été détruit.' WHERE `entry` = -1000113;
UPDATE `script_texts` SET `content_loc2` = 'Père ! Père ! Tu es en vie !' WHERE `entry` = -1000114;
UPDATE `script_texts` SET `content_loc2` = 'Tu peux remercier $N de m\'avoir ramené ici saint et sauf, père.' WHERE `entry` = -1000115;
UPDATE `script_texts` SET `content_loc2` = 'serre son père dans ses bras.' WHERE `entry` = -1000116;
UPDATE `script_texts` SET `content_loc2` = 'Nous avons besoin d\'un plan, je vais tout de même récupérer une arme et une armure.' WHERE `entry` = -1560024;
UPDATE `script_texts` SET `content_loc2` = 'Taretha doît être dans la taverne. Allons-y.' WHERE `entry` = -1560029;
UPDATE `script_texts` SET `content_loc2` = 'Taretha ! Quel type de magie est-ce donc ?' WHERE `entry` = -1560030;
UPDATE `script_texts` SET `content_loc2` = 'Je suis libre ! Merci à tous !' WHERE `entry` = -1560048;
UPDATE `script_texts` SET `content_loc2` = 'Thrall, vous vous êtes échapper !' WHERE `entry` = -1560049;
UPDATE `script_texts` SET `content_loc2` = 'Merci d\'avoir accepter de nous aider. Maintenant sortons d\'ici $N' WHERE `entry` = -1000117;
UPDATE `script_texts` SET `content_loc2` = 'Par ici ! Ils nous suivent !' WHERE `entry` = -1000118;
UPDATE `script_texts` SET `content_loc2` = 'Accordez moi un moment de repos. La journée a été dure et j\'ai peu de force' WHERE `entry` = -1000119;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez entendu quelque chose ?' WHERE `entry` = -1000120;
UPDATE `script_texts` SET `content_loc2` = 'Le Guet-del\'épervier finalement ! Maintenant, ou est mon...Oh non ! Mon paquet a disparu ! Ou est..' WHERE `entry` = -1000121;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne m\'empecherez pas d\'arriver au Guet-de-l\'épervier !' WHERE `entry` = -1000122;
UPDATE `script_texts` SET `content_loc2` = 'se libère !' WHERE `entry` = -1544015;
UPDATE `script_texts` SET `content_loc2` = 'devient enragé !' WHERE `entry` = -1189004;
UPDATE `script_texts` SET `content_loc2` = 'luit avec énergie !' WHERE `entry` = -1509001;
UPDATE `script_texts` SET `content_loc2` = 'crie au loin, ouvrez les portes vers le Néant !' WHERE `entry` = -1532089;
UPDATE `script_texts` SET `content_loc2` = 'sombre dans une rage venue du Néant' WHERE `entry` = -1532090;
UPDATE `script_texts` SET `content_loc2` = 'entre en pleine frénésie !' WHERE `entry` = -1269018;
UPDATE `script_texts` SET `content_loc2` = 'Stop ! N\'allez pas plus loin mortels !. Vous êtes mal préparés pour faire face aux forces du Vol Infini. Venez, laissez moi vous aidez .' WHERE `entry` = -1269019;
UPDATE `script_texts` SET `content_loc2` = 'Orcs de la Horde ! Ce portail est la voie de votre nouvelle destinée ! Azeroth se trouve devant vous, venez la prendre !' WHERE `entry` = -1269027;
UPDATE `script_texts` SET `content_loc2` = 'Gul\'dan dit la véritée ! Nous devons retourner annoncer la nouvelle à nos frères ! Retraite à travers le portail !' WHERE `entry` = -1269028;
UPDATE `script_texts` SET `content_loc2` = 'Prêt quand vous l\'êtes, $c' WHERE `entry` = -1000123;
UPDATE `script_texts` SET `content_loc2` = 'La Dispute a commencé. $N, soyez prêt à combattre' WHERE `entry` = -1000124;
UPDATE `script_texts` SET `content_loc2` = 'Vous ! Entrez dans la Dispute !' WHERE `entry` = -1000125;
UPDATE `script_texts` SET `content_loc2` = 'Le challenger est au sol !' WHERE `entry` = -1000126;
UPDATE `script_texts` SET `content_loc2` = 'La Dispute est terminé.' WHERE `entry` = -1000127;
