SET NAMES utf8;


##################
# MANGOS_STRING
##################

UPDATE `mangos_string` SET `content_loc2` = 'La créature (Entry: %u) ne peut pas être domptée.' WHERE `entry` = 343;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de l\'Alliance a été réinitialisé!' WHERE `entry` = 614;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau de la Horde a été réinitialisé!' WHERE `entry` = 615;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle de la Tour des Mages!' WHERE `entry` = 667;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle de la Tour des Mages!' WHERE `entry` = 668;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle des ruines Draeneï!' WHERE `entry` = 669;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle des ruines Draeneï!' WHERE `entry` = 670;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle de la Tour des Elfes de Sang!' WHERE `entry` = 671;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle de la Tour des Elfes de Sang!' WHERE `entry` = 672;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a pris le contrôle des Ruines des saccageurs gangrenés!' WHERE `entry` = 673;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a pris le contrôle des Ruines des saccageurs gangrenés!' WHERE `entry` = 674;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle de la Tour des Mages!' WHERE `entry` = 675;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle de la Tour des Mages!' WHERE `entry` = 676;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle des ruines Draeneï!' WHERE `entry` = 677;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle des ruines Draeneï!' WHERE `entry` = 678;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle de la Tour des Elfes de Sang!' WHERE `entry` = 679;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle de la Tour des Elfes de Sang!' WHERE `entry` = 680;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a perdu le contrôle des Ruines des saccageurs gangrenés!' WHERE `entry` = 681;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a perdu le contrôle des Ruines des saccageurs gangrenés!' WHERE `entry` = 682;
UPDATE `mangos_string` SET `content_loc2` = '$N a pris le drapeau!' WHERE `entry` = 683;
UPDATE `mangos_string` SET `content_loc2` = 'L\'Alliance a capturé le drapeau!' WHERE `entry` = 684;
UPDATE `mangos_string` SET `content_loc2` = 'La Horde a capturé le drapeau!' WHERE `entry` = 685;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau a été laché!' WHERE `entry` = 686;
UPDATE `mangos_string` SET `content_loc2` = 'Le drapeau a été réinitialisé!' WHERE `entry` = 687;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe est trop grand pour ce champ de bataille. Veuillez regrouper pour rejoindre.' WHERE `entry` = 1122;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe est trop grand pour cette arène. Veuillez regrouper pour rejoindre.' WHERE `entry` = 1123;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte des membres n\'appartenant pas à votre équipe d\'arène. Veuillez regrouper pour rejoindre.' WHERE `entry` = 1124;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe ne comporte pas assez de joueurs pour rejoindre ce match.' WHERE `entry` = 1125;
UPDATE `mangos_string` SET `content_loc2` = 'L\'équipe d\'Or l\'emporte!' WHERE `entry` = 1126;
UPDATE `mangos_string` SET `content_loc2` = 'L\'équipe Verte l\'emporte!' WHERE `entry` = 1127;
UPDATE `mangos_string` SET `content_loc2` = 'Il n\'y a pas assez de joueurs dans sur ce champ de bataille. Il prendra bientôt fin, à moins que des joueurs le rejoigne afin d\'équilibrer la balance.' WHERE `entry` = 1128;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte un membre hors ligne. Veuillez le supprimer avant de rejoindre.' WHERE `entry` = 1129;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe contient des joueurs d\'une faction opposée. Vous ne pouvez pas rejoindre ce champ de bataille comme un groupe.' WHERE `entry` = 1130;
UPDATE `mangos_string` SET `content_loc2` = 'Votre groupe comporte des joueurs de différentes tranches de niveau. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 1131;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est déjà inscrit pour ce champ de bataille. Il doit le quitter avant que vous puissiez rejoindre ce champ de bataille comme un groupe.' WHERE `entry` = 1132;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est un déserteur. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 1133;
UPDATE `mangos_string` SET `content_loc2` = 'Un membre de votre groupe est déjà inscrit pour trois champ de bataille. Vous ne pouvez pas rejoindre comme un groupe.' WHERE `entry` = 1134;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas téléporter sur une carte de champ de bataille ou d\'arène.' WHERE `entry` = 1135;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas invoquer un joueur sur une carte de champ de bataille ou d\'arène.' WHERE `entry` = 1136;
UPDATE `mangos_string` SET `content_loc2` = 'Vous devez être en mode MJ afin de téléporter un joueur dans sur un champ de bataille.' WHERE `entry` = 1137;
UPDATE `mangos_string` SET `content_loc2` = 'Vous ne pouvez pas vous téléporter d\'un champ de bataille à un autre. Veuillez d\'abord quitter le champ de bataille actuel.' WHERE `entry` = 1138;


##################
# LOCALES_CREATURE
##################

UPDATE `locales_creature` SET `name_loc2` = 'Goli Krumn' WHERE `entry` = 1365;
UPDATE `locales_creature` SET `name_loc2` = 'Mug\'thol' WHERE `entry` = 2257;
UPDATE `locales_creature` SET `name_loc2` = 'Targ' WHERE `entry` = 2420;
UPDATE `locales_creature` SET `name_loc2` = 'Furmund' WHERE `entry` = 9550;
UPDATE `locales_creature` SET `name_loc2` = 'Magtheridon' WHERE `entry` = 17257;
UPDATE `locales_creature` SET `name_loc2` = 'K\'ure' WHERE `entry` = 17545;
UPDATE `locales_creature` SET `name_loc2` = 'Leokk' WHERE `entry` = 22268;
UPDATE `locales_creature` SET `name_loc2` = 'Fêtard de l\'Hiver elfe de sang' WHERE `entry` = 22998;
UPDATE `locales_creature` SET `name_loc2` = 'Fêtarde de l\'Hiver elfe de sang' WHERE `entry` = 22999;
UPDATE `locales_creature` SET `name_loc2` = 'Eudé Tintinnabourse', `subname_loc2` = 'Gourmandises Fumebois' WHERE `entry` = 23064;
UPDATE `locales_creature` SET `name_loc2` = 'Sauveteur aileron-d\'hiver' WHERE `entry` = 27434;


##################
# LOCALES_GAMEOBJECT
##################

UPDATE `locales_gameobject` SET `name_loc2` = 'Doodad_HF_Mag_door01' WHERE `entry` = 183847;
UPDATE `locales_gameobject` SET `name_loc2` = 'Doodad_Hellfire_Raid_FX01' WHERE `entry` = 184653;
UPDATE `locales_gameobject` SET `name_loc2` = 'Œuf arakkoa pourri' WHERE `entry` = 184795;
UPDATE `locales_gameobject` SET `name_loc2` = 'Œuf arakkoa pourri' WHERE `entry` = 184796;
UPDATE `locales_gameobject` SET `name_loc2` = 'Œuf arakkoa pourri' WHERE `entry` = 184797;
UPDATE `locales_gameobject` SET `name_loc2` = 'Œuf arakkoa pourri - leurre' WHERE `entry` = 184801;
UPDATE `locales_gameobject` SET `name_loc2` = 'HDressing, Christmas, Hanging Streams x3' WHERE `entry` = 187194;
UPDATE `locales_gameobject` SET `name_loc2` = 'HDressing, Christmas Standing Medium Exterior' WHERE `entry` = 187235;
UPDATE `locales_gameobject` SET `name_loc2` = 'Pendant, Banderoles - Noël' WHERE `entry` = 187567;


##################
# LOCALES_ITEM
##################

UPDATE `locales_item` SET `name_loc2` = 'Rempart du golem de roche' WHERE `entry` = 11785;
UPDATE `locales_item` SET `name_loc2` = 'Eau-de-vie spéciale' WHERE `entry` = 17196;
UPDATE `locales_item` SET `name_loc2` = 'Formule : Enchantement d\'arme (Frappe majeure)', `description_loc2` = 'Vous apprend à enchanter de manière permanente une arme de mêlée pour infliger 7 points de dégâts supplémentaires. Nécessite un objet de niveau 35 ou supérieur.' WHERE `entry` = 22552;
UPDATE `locales_item` SET `name_loc2` = 'Formule : Enchantement de cape (Pénétration des sorts)', `description_loc2` = 'Vous apprend à enchanter de manière permanente une cape pour augmenter votre pénétration des sorts de 20. Nécessite un objet de niveau 35 ou supérieur.' WHERE `entry` = 28274;
UPDATE `locales_item` SET `name_loc2` = 'Bottes de muletier', `description_loc2` = '100' WHERE `entry` = 29804;
UPDATE `locales_item` SET `name_loc2` = 'Dessin : Cœur de don Julio', `description_loc2` = 'Vous apprend à tailler un Cœur de don Julio.' WHERE `entry` = 33305;
UPDATE `locales_item` SET `name_loc2` = 'Cuissards de la nécropole' WHERE `entry` = 36400;
UPDATE `locales_item` SET `name_loc2` = 'Garde-porte' WHERE `entry` = 40370;
UPDATE `locales_item` SET `name_loc2` = 'Anneau de beauté décomposée' WHERE `entry` = 40375;
UPDATE `locales_item` SET `name_loc2` = 'Drapé de l\'ennemi mortel' WHERE `entry` = 40403;
UPDATE `locales_item` SET `name_loc2` = 'Marque de Norgannon' WHERE `entry` = 40531;
UPDATE `locales_item` SET `name_loc2` = 'Garde-mains adroits givrés' WHERE `entry` = 40541;
UPDATE `locales_item` SET `name_loc2` = 'Chaperon de rationalité' WHERE `entry` = 40562;
UPDATE `locales_item` SET `name_loc2` = 'Tunique du gardien de l\'artefact' WHERE `entry` = 40588;
UPDATE `locales_item` SET `name_loc2` = 'Espauliers du repaire élevé' WHERE `entry` = 40590;
UPDATE `locales_item` SET `name_loc2` = 'Bottes des énergies soignantes' WHERE `entry` = 40592;
UPDATE `locales_item` SET `name_loc2` = 'Spallières de catatonie' WHERE `entry` = 40594;
UPDATE `locales_item` SET `name_loc2` = 'Plastron du gladiateur fatal en plaques d\'effroi' WHERE `entry` = 40784;
UPDATE `locales_item` SET `name_loc2` = 'Plastron du gladiateur fatal en écailles' WHERE `entry` = 40785;
UPDATE `locales_item` SET `name_loc2` = 'Gantelets du gladiateur haineux en plaques d\'effroi' WHERE `entry` = 40803;
UPDATE `locales_item` SET `name_loc2` = 'Corselet ornementé du gladiateur haineux' WHERE `entry` = 40904;
UPDATE `locales_item` SET `name_loc2` = 'Garde-jambes du gladiateur haineux en peau de wyrm' WHERE `entry` = 41302;
UPDATE `locales_item` SET `name_loc2` = 'Robe du gladiateur fatal en cuir de kodo' WHERE `entry` = 41309;
UPDATE `locales_item` SET `name_loc2` = 'Garde-jambes du gladiateur fatal en cuir' WHERE `entry` = 41654;
UPDATE `locales_item` SET `name_loc2` = 'Lance barbelée gelée', `description_loc2` = '10000D46BA0lus rafraîchissant !' WHERE `entry` = 41815;
UPDATE `locales_item` SET `name_loc2` = 'Jambières du gladiateur haineux en étoffe lunaire' WHERE `entry` = 41862;
UPDATE `locales_item` SET `name_loc2` = 'Gants du gladiateur haineux en étoffe lunaire' WHERE `entry` = 41872;
UPDATE `locales_item` SET `name_loc2` = 'Chausses du gladiateur fatal en soie' WHERE `entry` = 41958;
UPDATE `locales_item` SET `name_loc2` = 'Carte de Sombrelune : Illusion' WHERE `entry` = 42988;
UPDATE `locales_item` SET `name_loc2` = 'Carte de Sombrelune : Mort' WHERE `entry` = 42990;


##################
# LOCALES_NPC_TEXT
##################

UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Salutations, $N !', `Text0_1_loc2` = 'Salutations, $N !' WHERE `entry` = 328;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Un pouvoir phénoménal se trouve dans les esprits ou "miniatures" des créatures contre lesquelles nous nous battons.$B$BRegardez en vous ; apprenez à utiliser le pouvoir de votre propre esprit et vous serez bien plus $gpuissant:puissante; que vous ne l\'imaginez.' WHERE `entry` = 1757;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'La terre conserve bien des secrets, $c ; il est de notre devoir de nous assurer que ce qui doit rester un secret pour le bien de tous ne soit pas découvert.' WHERE `entry` = 2284;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'L\'auberge ? Ah oui ! Vous cherchez les meilleures bières de la région ? La Taverne de Brûlepierre, c\'est là qu\'il faut aller. $B$BVous la trouverez à gauche des portes de Forgefer si vous entrez, à droite si vous sortez.', `Text0_1_loc2` = 'L\'auberge ? Ah oui ! Vous cherchez les meilleures bières de la région ? La Taverne de Brûlepierre, c\'est là qu\'il faut aller. $B$BVous la trouverez à gauche des portes de Forgefer si vous entrez, à droite si vous sortez.', `Text1_0_loc2` = 'Si vous cherchez une maison d\'hôte, l\'auberge de Brûlepierre est le bon endroit. Elle se trouve à gauche des portes de Forgefer si vous entrez, à droite si vous sortez. $B$BOh ! Et si vous allez par là, dites-leur de me mettre une pinte de côté.', `Text1_1_loc2` = 'Si vous cherchez une maison d\'hôte, l\'auberge de Brûlepierre est le bon endroit. Elle se trouve à gauche des portes de Forgefer si vous entrez, à droite si vous sortez. $B$BOh ! Et si vous allez par là, dites-leur de me mettre une pinte de côté.' WHERE `entry` = 2768;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Où est l\'hôtel des ventes ? Juste à droite des portes de Forgefer quand vous entrez dans la ville. Vous le trouverez juste en face de la chambre forte.', `Text0_1_loc2` = 'Où est l\'hôtel des ventes ? Juste à droite des portes de Forgefer quand vous entrez dans la ville. Vous le trouverez juste en face de la chambre forte.' WHERE `entry` = 3014;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Bixi et Buliwyf ont dû écraser ou taillader des orcs avec à peu près tous les types d\'armes existant. Vous les trouverez près des Armes de Timberline si vous avez besoin d\'une formation.', `Text0_1_loc2` = 'Bixi et Buliwyf ont dû écraser ou taillader des orcs avec à peu près tous les types d\'armes existant. Vous les trouverez près des Armes de Timberline si vous avez besoin d\'une formation.', `Text1_0_loc2` = 'Vous voulez apprendre à utiliser de nouvelles armes, pas vrai ? Ma foi, vous devriez parler à Bixi ou Buliwyf, aux Armes de Timberline. Ils savent tout utiliser, des arbalètes aux.. aux zweihanders !', `Text1_1_loc2` = 'Vous voulez apprendre à utiliser de nouvelles armes, pas vrai ? Ma foi, vous devriez parler à Bixi ou Buliwyf, aux Armes de Timberline. Ils savent tout utiliser, des arbalètes aux.. aux zweihanders !' WHERE `entry` = 4518;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Salutations, $N !', `Text0_1_loc2` = 'Vous avez besoin d\'une illusion ?$B$BSi votre illusion flanche au milieu de votre quête, revenez me voir et je vous offrirai de nouveau le déguisement.$B$BSi vous échouez, n\'abandonnez pas ! Revenez me voir, je vous aiderai jusqu\'à ce que vous ayez atteint vos objectifs.' WHERE `entry` = 4773;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Rabais pour vous et pour les vôtres !', `Text0_1_loc2` = 'Rabais pour vous et pour les vôtres !', `Text1_0_loc2` = 'Directement de la ferme à votre assiette : les meilleurs produits sont ceux des Gourmandises Fumebois !', `Text1_1_loc2` = 'Directement de la ferme à votre assiette : les meilleurs produits sont ceux des Gourmandises Fumebois !', `Text2_0_loc2` = 'C\'est l\'époque des bonnes affaires ! Fah la la la la !', `Text2_1_loc2` = 'C\'est l\'époque des bonnes affaires ! Fah la la la la !', `Text3_0_loc2` = 'Bonnes fêtes du Voile d\'hiver à tous ! Et pour bien commencer, foncez aux Gourmandises Fumebois pour vous faire plaisir !', `Text3_1_loc2` = 'Bonnes fêtes du Voile d\'hiver à tous ! Et pour bien commencer, foncez aux Gourmandises Fumebois pour vous faire plaisir !', `Text4_0_loc2` = 'N\'oubliez pas de dire au Grand-père Hiver quel cadeau vous voulez pour le Voile d\'hiver !', `Text4_1_loc2` = 'N\'oubliez pas de dire au Grand-père Hiver quel cadeau vous voulez pour le Voile d\'hiver !', `Text5_0_loc2` = 'Vive le son des cloches, mais pas les trous dans les poches ! Grâce aux Gourmandises Fumebois, économisez sur vos dépenses pour le Voile d\'hiver !', `Text5_1_loc2` = 'Vive le son des cloches, mais pas les trous dans les poches ! Grâce aux Gourmandises Fumebois, économisez sur vos dépenses pour le Voile d\'hiver !', `Text6_0_loc2` = 'Si j\'avais des marrons, je les ferais cuire sur les braises en plein air ! Mmmm !', `Text6_1_loc2` = 'Si j\'avais des marrons, je les ferais cuire sur les braises en plein air ! Mmmm !', `Text7_0_loc2` = 'Ne lésinez pas sur les paquets cadeaux pendant le Voile d\'hiver ! Rien ne vaut un beau nœud rose autour d\'une hache ou d\'une épée pour réjouir le cœur de vos amis !', `Text7_1_loc2` = 'Ne lésinez pas sur les paquets cadeaux pendant le Voile d\'hiver ! Rien ne vaut un beau nœud rose autour d\'une hache ou d\'une épée pour réjouir le cœur de vos amis !' WHERE `entry` = 6194;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Bonnes fêtes du Voile d\'hiver, heu... $Gmon garçon:ma fille;. Les enfants gentils reçoivent des rabais dans toutes les échoppes des Gourmandises Fumebois. Miam !', `Text1_0_loc2` = 'Je crois savoir ce que fera ce vieux Grand-père Hiver quand tout ceci sera fini. J\'ai une bonne bouteille dans mon sac, et j\'ai l\'intention d\'égayer mon Voile d\'hiver en explorant son contenu.', `Text2_0_loc2` = 'Non... Pas question de s\'asseoir sur mes genoux.', `Text3_0_loc2` = 'Ouais, c\'est ça, allez dire au vieux Grand-père Hiver ce que vous voulez comme cadeau pour les fêtes.$B$BAllez, on se grouille !' WHERE `entry` = 6250;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Quelle arme vous intéresse en particulier ?' WHERE `entry` = 6290;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Je vous salue, $gjeune homme:jeune fille;, et vous souhaite la bienvenue aux Pitons du Tonnerre. Vous y trouverez un abri contre les fardeaux de ce monde. Tous les membres de la Horde y sont les bienvenus.$B$BLes esprits du présent et du passé prennent vie en ce lieu sacré, mon $gami:amie;. Honorez-les, car ainsi, vous vous honorerez.' WHERE `entry` = 7013;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Lard garder ici. Lard aussi vendre poisson. Vous vouloir poisson ?', `Text0_1_loc2` = 'Lard garder ici. Lard aussi vendre poisson. Vous vouloir poisson ?' WHERE `entry` = 7211;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Nous devons assurer la survie de ce camp à tout prix, $c ! Nous ne devons pas faire quartier à nos ennemis, car ils ne nous témoigneront de leur part aucune pitié.' WHERE `entry` = 7402;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Joyeux Voile d\'hiver, mon $gami:amie; !', `Text0_1_loc2` = 'Joyeux Voile d\'hiver, mon $gami:amie; !', `Text1_0_loc2` = 'Joyeuses fêtes, et que la paix soit sur vous !', `Text1_1_loc2` = 'Joyeuses fêtes, et que la paix soit sur vous !', `Text2_0_loc2` = 'Je vous souhaite de bonnes fêtes, mon $gami:amie; !', `Text2_1_loc2` = 'Je vous souhaite de bonnes fêtes, mon $gami:amie; !', `Text3_0_loc2` = 'Ah, du gui…', `Text3_1_loc2` = 'Ah, du gui…' WHERE `entry` = 8139;
UPDATE `locales_npc_text` SET `Text0_1_loc2` = 'Bonjour ! C\'est un plaisir de vous rencontrer !' WHERE `entry` = 8787;
UPDATE `locales_npc_text` SET `Text0_1_loc2` = 'Oh, formidable ! C\'était très drôle, non ? Petit à petit, je maudis de plus en plus de ces répugnants Perdus. Bientôt, je serai prête à essayer la malédiction sur un draeneï !' WHERE `entry` = 8809;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Les esprits s’agitent, $r. Prenez garde à votre environnement quand vous serez en Nagrand, sinon vous serez consumé par leur furie.' WHERE `entry` = 9180;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Gardez les yeux grands ouverts, $c. Dans le coin, les bestioles ont tendance à vous traquer, plutôt que le contraire.' WHERE `entry` = 9219;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Hemet est le plus grand chasseur que je connaisse. Nous nous sommes croisés dans les collines de Berceau-de-l\'Hiver, sur Azeroth, il y a de nombreuses lunes. Lui et moi poursuivions la même proie : le grand tigre surnommé Rak\'shiri.$B$BPlutôt que de nous battre pour ce gibier, nous avons préféré conclure un pari ; celui qui récupérerait la peau du sabre-de-givre pourrait demander quelque chose à l’autre. À ma grande honte, c’est ainsi que j’ai gagné mon surnom : Fitz.$B$BFranchement, est-ce que j’ai l’air d’un Fitz ?' WHERE `entry` = 9283;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Vous avez l\'air raisonnable, pour $gun:une:r; $r. Nous pouvons peut-être nous aider mutuellement.' WHERE `entry` = 9312;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Sortez-moi de là, $r !' WHERE `entry` = 9357;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Que voyez-vous quand vous regardez vers l’ouest, $gmortel:mortelle; ?' WHERE `entry` = 9419;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Voyez-vous ce que je vois ? Le prélude d’une invasion.$B$BEffectivement, c’est avec sagesse que le maître a scellé les portes. Mais depuis, il a perdu... comment dire ? Le maître a relâché son attention. Oui... son attention.$B$BLa Légion n’a pas laissé filer cette occasion. Ils sont maintenant en train de se répandre, et ils sont plus nombreux chaque jour.' WHERE `entry` = 9420;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'La Légion ardente. Des démons. Je les vois aussi clairement que vous voyez votre main devant votre figure. En fait, je les voyais très clairement à l’époque.$B$BLa Légion est revenue avec de nouveaux plans machiavéliques. En temps normal je peux sentir la présence d’un démon à mille pas.$B$B<Altuis fais la grimace.>' WHERE `entry` = 9421;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Ils se dérobent. Je n’arrive pas à voir au-delà de leurs protections. Ils ont mis en place des sorts de garde pour ne pas être détectés.$B$B<Altruis pointe vers l’ouest.>$B$BIls nous craignent car ils savent que nous n’avons peur de rien. Le prix d’un tel pouvoir est élevé, et les sacrifices sont nombreux.' WHERE `entry` = 9422;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = '<Altruis se tourne vers vous et sourit.>$B$BJe ne les vois pas.$B$B<Altruis désigne sa monture, Néanstradamus.>$B$BNous devons les arrêter avant que ces camps de forge ne puissent achever ce qu’ils sont en train de bâtir.' WHERE `entry` = 9423;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'C’est ainsi qu’on appelle ces édifices qui jonchent le sol. La Légion se sert des mo’arg et gan’arg pour construire des armes de destruction massive dans ces camps de forge mobiles. Essayons de ne pas attendre de savoir précisément ce qu’ils essayent de construire en Nagrand !$B$BVous serez mes yeux. Vos armes seront ma fureur.' WHERE `entry` = 9424;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Je pense que je vais mettre quelques petits profits personnels de côté, pendant que les autres décident si on peut ou non entrer dans Oshu’gun.$B$BLe temps, c\'est de l\'argent !' WHERE `entry` = 9429;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Avec votre aide, nous pourrons peut-être vaincre cette chose !' WHERE `entry` = 9596;
UPDATE `locales_npc_text` SET `Text0_1_loc2` = 'En tant que représentante de la Ville basse, je suis là pour faire valoir le fait qu\'Auchindoun doit être purgé du Conseil des ombres qui l\'a envahi. Enfin, il le faut si nous nous voulons garder un espoir pour l\'avenir et empêcher l\'avènement d\'un cataclysme plus dévastateur encore que celui qui a vu la création du désert des Ossements !$B$BNos peuples à tous ont déjà beaucoup trop souffert. Je suis là pour mettre fin à cette souffrance !' WHERE `entry` = 9615;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Nous suivons la tradition par habitude, mais la fête du Voile d\'hiver est bien terne maintenant. C\'est à Orgrimmar qu\'on la célèbre vraiment.', `Text0_1_loc2` = 'Nous suivons la tradition par habitude, mais la fête du Voile d\'hiver est bien terne maintenant. C\'est à Orgrimmar qu\'on la célèbre vraiment.' WHERE `entry` = 9710;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Handiir et Buliwyf peuvent vous montrer comment manier correctement une masse, quelle que soit sa taille. Vous pourrez trouver Buliwyf aux Armes de Timberline, à Forgefer. Handiir passe ses journées à l’Exodar, entraînant les draeneï à l’étage des Commerces.', `Text0_1_loc2` = 'Handiir et Buliwyf peuvent vous montrer comment manier correctement une masse, quelle que soit sa taille. Vous pourrez trouver Buliwyf aux Armes de Timberline, à Forgefer. Handiir passe ses journées à l’Exodar, entraînant les draeneï à l’étage des Commerces.' WHERE `entry` = 10755;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Mon esprit est empli de visions d\'événements qui ont lieu partout dans le monde, et d\'autres qui pourraient encore arriver. Beaucoup de ces événements sont sinistres, mais il ne faut pas nécessairement croire qu\'il est impossible d\'en modifier le cours.' WHERE `entry` = 10893;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Mes frères étaient ici il n\'y a pas si longtemps. Mon lien avec eux est devenu précaire. Une forte présence dans la cour bloque la voie.' WHERE `entry` = 11082;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Les temps changent, $N. La guerre est venue.$B$BNotre peuple va-t-il saisir cette occasion et aider nos alliés… Ou allons-nous rester en marge de l\'Histoire ?' WHERE `entry` = 12208;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Avant, je m\'appelais Iolol, jusqu\'à ce qu\'un vote à bulletin secret soit organisé en ville pour que je change de nom. C\'était ça, ou suivre le chemin de Corki. Vous n\'auriez pas hésité non plus. Que pensez-vous de mon nouveau nom ? Il y a un sacré progrès, n\'est-ce pas ?$B$BEt tant que j\'y suis, jetez un œil au panneau d\'affichage si vous cherchez du travail.' WHERE `entry` = 12294;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Glug bmrgl grggl !', `Text1_0_loc2` = 'Mawurrgggl, gurgl lur !', `Text2_0_loc2` = 'Glumrggl ?', `Text3_0_loc2` = 'Brggl-brggl Mrgl-Mrgl ! Gluk !', `Text4_0_loc2` = 'Blrmrrgl gulrgl grr.', `Text5_0_loc2` = 'RAWGRLRLRLRRLGLRL !!!', `Text6_0_loc2` = 'Mrglrglrglrgl... glrgl ?', `Text7_0_loc2` = 'Mrglmrgl Glrggl !' WHERE `entry` = 12362;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'J\'ai à manger si vous avez faim. Et si vous avez besoin de repos, vous pouvez utiliser ma tente.', `Text0_1_loc2` = 'J\'ai à manger si vous avez faim. Et si vous avez besoin de repos, vous pouvez utiliser ma tente.' WHERE `entry` = 12734;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Que puis-je faire pour vous aider, mon enfant ?', `Text0_1_loc2` = 'Que puis-je faire pour vous aider, mon enfant ?' WHERE `entry` = 13022;
UPDATE `locales_npc_text` SET `Text0_0_loc2` = 'Le salon de coiffure est du côté ouest des communs.', `Text0_1_loc2` = 'Le salon de coiffure est du côté ouest des communs.' WHERE `entry` = 13885;


##################
# LOCALES_PAGE_TEXT
##################

UPDATE `locales_page_text` SET `Text_loc2` = 'Lors des derniers jours de la Deuxième guerre, quand la victoire de la Horde sur l\'Alliance semblait inéluctable, deux des plus puissants orcs d\'Azeroth s\'affrontèrent. Tandis que Marteau-du-destin préparait l\'assaut final contre Lordaeron, une bataille qui aurait écrasé les derniers restes de l\'Alliance, Gul’dan et les clans renégats abandonnèrent leurs postes et prirent la mer.' WHERE `entry` = 1983;
UPDATE `locales_page_text` SET `Text_loc2` = 'Soutenu par les puissants clans des Foudreguerre et du Marteau du Crépuscule, Gul’dan parvint à découvrir la tombe de Sargeras au fond des mers. Mais quand il ouvrit la crypte immergée, il n\'y trouva que des démons enragés qui l\'attendaient.' WHERE `entry` = 1986;
UPDATE `locales_page_text` SET `Text_loc2` = 'Ivre de vengeance, Marteau-du-destin envoya ses forces tuer Gul’dan et ramener les renégats dans son armée. Mais Gul’dan avait déjà payé sa témérité de sa vie, déchiqueté par les démons qu\'il avait libérés. Leur chef mort, les clans renégats tombèrent rapidement sous les coups des légions de Marteau-du-destin.' WHERE `entry` = 1987;
UPDATE `locales_page_text` SET `Text_loc2` = 'La rébellion avait été étouffée, mais la Horde ne pouvait se remettre des terribles pertes qu\'elle venait de subir. La trahison de Gul’dan avait donné à l\'Alliance non seulement un nouvel espoir, mais aussi le temps de se regrouper et de riposter.' WHERE `entry` = 1988;
UPDATE `locales_page_text` SET `Text_loc2` = 'La Fête du Voile d\'hiver$B$BLes dernières saisons d\'Azeroth sont une période de changement dans de nombreuses cultures. Les nains et les taurens, plus particulièrement, célèbrent la légende du Voile d\'hiver : la neige recouvre les terres d\'un manteau pur qui annonce le renouveau. C\'est une période de fête et de célébrations. Bien que les légendes que les races d\'Azeroth partagent soient à peu près similaires, les manières qu\'elles choisissent pour les célébrer sont aussi diverses que le nombre de races.' WHERE `entry` = 2571;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les nains$B$BLes nains sont obsédés par la recherche de leurs origines. Les nains ont choisi de célébrer la saison comme une reconnaissance de Grand-père Hiver lui-même. Ils considèrent qu\'il est la personnification d\'un membre des anciens d\'Azeroth : les Titans. Bien qu\'ils revendiquent une descendance plus ou moins éloignée avec ces êtres mystiques, ils considèrent que Dun Morogh est le meilleur exemple des bienfaits de Grand-père Hiver.' WHERE `entry` = 2573;
UPDATE `locales_page_text` SET `Text_loc2` = 'Le très saint temple de Maraudon se trouve très loin dans la vallée des Lances. Cela a beau être un sacrilège, je demande à un non-centaure de nous aider. Vous allez comprendre pourquoi.$B$BLà, juste derrière les portes, où seuls les esprits et nos prêtres et prêtresses les plus sacrés peuvent se rendre, réside le Prophète sans nom. Il est l\'un des plus âgés de toutes les tribus, c’est notre plus haute autorité spirituelle.' WHERE `entry` = 2591;
UPDATE `locales_page_text` SET `Text_loc2` = 'Le Prophète est puissant et communique avec les esprits de nos ancêtres. Mais c\'est un fou ! Il n\'a aucune idée du vrai pouvoir qu\'il possède. L\'Amulette des esprits se trouve sur lui. C\'est de là que toute sa force provient.\n\nJ\'ai appris que l\'Amulette est puissante, mais elle est incomplète.' WHERE `entry` = 2592;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les esprits de nos premiers khans rôdent à travers les cavernes de Maraudon. Les premiers enfants de notre mère et de notre père, et nos plus grands chefs : Gelk, Kolk, Magra, Maraudos et Veng. Chacun de ces esprits détient l\'une des gemmes manquantes.' WHERE `entry` = 2595;
UPDATE `locales_page_text` SET `Text_loc2` = 'Utilisez le pouvoir de l\'Amulette des esprits pour les inciter à se manifester et prenez les gemmes qu\'elles ont ! Puis, placez les gemmes sur l\'Amulette des esprits et rapportez-la-moi. Une fois que j\'aurai l\'Amulette d\'union, je serai assez puissant pour reformer les tribus afin que nous puissions enfin devenir ce que nos ancêtres voulaient !' WHERE `entry` = 2596;
UPDATE `locales_page_text` SET `Text_loc2` = 'Au nom des Gourmandises Fumebois, nous vous remercions d’avoir accepté d’enquêter. Nous ne savons pas avec certitude quel groupe détient Metzen. Vous pouvez donc commencer par l’un ou par l’autre, à votre guise.$B$BLe temps, c’est de l’argent, mais dans ce cas précis, nous en manquons. Soyez rapide, car ces deux bandes sont capables du pire.$B$BVoici les deux demandes de rançon que nous avons reçues. Bonne chance.' WHERE `entry` = 2841;
UPDATE `locales_page_text` SET `Text_loc2` = 'Si vous voulez retrouver le renne vivant, dépêchez-vous de payer la rançon. Les pirates des mers du Sud n’aiment pas les retards de paiement, et nous savons que l’animal vous rend de grands services dans VOTRE forme de piraterie.$B$BApportez 1 000 pièces d’or à l’entrée de la crique des Gréements, à Tanaris. Toute tentative pour libérer le renne nous obligera à lui faire subir le supplice de la planche, avec une toute petite planche suivie d’une très longue chute.$B$BYeargh !$B$BLes pirates des mers du Sud.' WHERE `entry` = 2842;
UPDATE `locales_page_text` SET `Text_loc2` = 'Votre animal bien-aimé supporte assez mal la chaleur incessante de la gorge des Vents brûlants… vous avez intérêt à payer la rançon sans tarder.$B$BNous demandons 700 pièces d’or et cinq rubis étoilés. Vous les placerez dans une boîte dépourvue de signes distinctifs que vous laisserez à l’entrée du passage de Formepierre d’ici une semaine.$B$BSi vous n’obtempérez pas, Metzen deviendra le plat principal du traditionnel festin sombrefer du Voile d’hiver.$B$BMmmm… du renne….' WHERE `entry` = 2843;
UPDATE `locales_page_text` SET `Text_loc2` = 'Plus rapide que des aigles sont ses coursiers,$B$BEt il siffle, et il crie, et il les encourage :$B$B« Hue, Mercer ! Hue, Chilton ! Hue, Jordan et Kaplan !$B$BAllons, Nagle ! Allons, Pardo ! Allons, Goodman et Metzen !$B$BEn haut des murailles ! En haut des toits !$B$BEn avant ! En avant ! En avant, tous ! »' WHERE `entry` = 2844;


##################
# LOCALES_QUEST
##################

UPDATE `locales_quest` SET `Title_loc2` = 'La couronne de volonté', `Details_loc2` = 'Mug\'Thol et ses ogres Cassecrête ont envahi les ruines d\'Alterac. Il va être difficile de lui infliger une sérieuse punition sans d’abord entamer ses troupes.$b$bAprès les avoir réduites à la portion congrue, nous l’attaquerons.$b$bCompris ? Bien. Allez-y à présent.', `Objectives_loc2` = 'Tuer 10 Marteleurs Cassecrête pour Melisara à Moulin-de-Tarren.', `OfferRewardText_loc2` = 'La neige vire au rouge avec le sang des ogres, mais nous ne pouvons cesser nos efforts avant que l\'esprit et bon nombre de Cassecrête aient été écrasés et se retrouvent mélangés à la poussière et la neige.' WHERE `entry` = 518;
UPDATE `locales_quest` SET `Title_loc2` = 'De retour vers Fel’Zerul', `Details_loc2` = 'Jammal\'an le Prophète m\'a condamné à être exilé du temple d\'Atal\'Hakkar. Je considérais autrefois que le grand prêtre était un chef digne.$b$bSa foi inflexible dans sa prophétie apportera la destruction aux Atal\'ai. Si ce n\'est pas déjà fait.$b$bLorsque j\'ai exprimé des réserves, j\'ai été traité d’infidèle et évincé du temple.$b$bLes artefacts que vous avez apportés sont inoffensifs. Mais si Jammal\'an a découvert le bon fétiche d\'enchantement pour le rituel d\'invocation, alors le monde court un grand péril...', `Objectives_loc2` = 'Retourner voir Fel’Zerul à Pierrêche.' WHERE `entry` = 1444;
UPDATE `locales_quest` SET `Title_loc2` = 'Le temple d\'Atal\'Hakkar', `Details_loc2` = 'Ainsi il a parlé de la prophétie de Jammal\'an ?$b$bLe chef spirituel des Atal\'ai croit qu\'une fois Hakkar revenu du Néant pour Azeroth, le dieu accordera l\'immortalité à sa tribu.$b$bUne excuse idiote pour provoquer une fin du monde prématurée, si vous voulez mon avis.$b$bMais vous dites que l\'Exilé a parlé de fétiches enchantés ? Cela m\'inquiète profondément. S\'ils constituent la clé du rituel atal\'ai et qu\'ils sont à l\'origine de ce chaos, nous devons comprendre leurs pouvoirs intrinsèques.$b$bAventurez-vous dans le temple, et emparez-vous des fétiches.', `Objectives_loc2` = 'Rassembler 20 Fétiches d\'Hakkar et les apporter à Fel’Zerul à Pierrêche.' WHERE `entry` = 1445;
UPDATE `locales_quest` SET `Title_loc2` = 'Une découverte sinistre', `Details_loc2` = 'Comment ?$B$BAh, j\'ai parlé d\'une récompense, n\'est-ce pas ? Bon... ça m\'apprendra à ouvrir la bouche !$B$BVous avez fait le travail et je suppose que je vous dois ce que je vous avais promis. Prenez les cornes, je les ai mises dans une caisse pour vous. Portez-les à Belgrom Cogneroche, dans la Vallée de l\'Honneur. Il souhaite entendre votre rapport et vous récompenser.$B$BQue les vents vous portent, $c, et merci encore pour tout.', `Objectives_loc2` = 'Apporter la Caisse de Cornes de Totem-sinistre à Belgrom Cogneroche, Orgrimmar.' WHERE `entry` = 2976;
UPDATE `locales_quest` SET `Title_loc2` = 'L\'hippogriffe miniaturisé', `Details_loc2` = 'Puisque vous avez montré que vous êtes à la fois digne de confiance et $gdoué:douée; pour utiliser le vaisseau miniature, je souhaite à présent que vous capturiez une autre créature.$B$BLes hippogriffes ont été les compagnons loyaux des elfes de la nuit durant plusieurs années. Leur esprit est résolu et ferme.$B$BVotre tâche consiste à tuer 10 hippogriffes Aigreplume et de rapidement les faire rétrécir et les capturer avec le vaisseau, afin que leur esprit soit préservé. Vous trouverez les hippogriffes dans les plateaux Sauvages au sud d\'ici.', `Objectives_loc2` = 'Tuer 10 Hippogriffes Aigreplume de n\'importe quel type, puis utiliser le Vaisseau de muisek pour les faire rétrécir et les capturer.' WHERE `entry` = 3124;
UPDATE `locales_quest` SET `Title_loc2` = 'L\'aide à l\'archidruide Totem-runique', `Details_loc2` = 'Pardonnez-moi, $c, mais j\'aimerais prendre quelques instants de votre temps, si cela est possible.$B$BLe Cercle cénarien des Pitons du Tonnerre est très intéressé par des $gaventuriers aguerris tels:aventurières aguerries telles; que vous pour lui prêter main-forte dans un projet crucial. Bien que je n’en connaisse pas les détails, je peux vous dire que Hamuul Totem-runique lui-même mène ce projet.$B$BJe vous en prie, si cela vous intéresse, allez lui parler en personne à la Cime des Anciens aux Pitons du Tonnerre.', `Objectives_loc2` = 'Parler à l\'archidruide Hamuul Totem-runique aux Pitons du Tonnerre.' WHERE `entry` = 3784;
UPDATE `locales_quest` SET `Title_loc2` = 'Des friandises pour Grand-père Hiver', `Details_loc2` = 'Hé, $gjeune homme:jeune fille;, pourriez-vous rendre au Grand-père Hiver un petit service ? Ce n\'est pas que je me complaise à parler de moi à la troisième personne, mais le Grand-père Hiver a été sur le métier toute la journée, et s\'octroierait lui-même volontiers une de ces friandises. Quelques biscuits en pain d\'épice et un verre de lait glacé pour faire descendre le tout seraient les bienvenus. Pourriez-vous être $gun ami:une amie; pour le Grand-père, et me trouver tout ça ?', `Objectives_loc2` = 'Apporter 5 Biscuits en pain d\'épice et un Verre de lait glacé au Grand-père Hiver, à Orgrimmar.' WHERE `entry` = 6962;
UPDATE `locales_quest` SET `Title_loc2` = 'Grand-père Hiver est ici !', `Details_loc2` = 'Joyeuse fête du Voile d\'hiver, $gl\'ami:l\'amie; ! Assurez-vous d\'aller passer le bonjour au Grand-père Hiver, qui se trouve actuellement à Orgrimmar ! Si vous avez été sage cette année, vous recevrez de merveilleuses friandises, le jour de la fête du Voile d\'hiver. N\'oubliez pas de dire au Grand-père Hiver ce que vous espérez recevoir cette année !$B$BN\'oubliez pas non plus de faire des réserves de friandises à distribuer à tous ceux qui ont été méritants cette année. Nous avons une grande sélection de douceurs dans laquelle choisir. Tout frais de la ferme, directement dans votre assiette. C\'est bon, c\'est sain, ce sont les Gourmandises Fumebois !', `Objectives_loc2` = 'Parler à Grand-père Hiver. Il se trouve près des Gourmandises Fumebois à Orgrimmar.' WHERE `entry` = 7024;
UPDATE `locales_quest` SET `Title_loc2` = 'La fête du Voile d\'hiver', `Details_loc2` = 'Voilà ; si cela vous intéresserait d\'en savoir plus au sujet de la fête du Voile d\'hiver, lisez ce livre. Bien que je pense que notre version de la légende soit la plus appropriée, je suis suffisamment féru d\'étude des légendes pour apprécier la collecte de toutes les informations dans un ouvrage unique.$B$BQuand vous aurez fini de le compulser, apportez donc ce livre à Cairne Sabot-de-sang, aux Pitons du Tonnerre. Je sais qu\'il sera certainement intéressé d\'apprendre que d\'autres personnes se sont intéressées à la tradition de notre peuple.', `Objectives_loc2` = 'Prenez le temps de lire ce livre, "La fête du Voile d\'hiver", pour en apprendre plus sur cette période de fête. Quand vous en aurez fini avec le livre, apportez-le à Cairne Sabot-de-sang, dans la ville des Pitons du Tonnerre.' WHERE `entry` = 7061;
UPDATE `locales_quest` SET `Title_loc2` = 'Metzen le renne', `Details_loc2` = 'C’est un DÉSASTRE ! Metzen le renne a été kidnappé !$B$BMetzen est l’un des huit rennes du Grand-père Hiver - et il appartient aux Gourmandises Fumebois. Nous n’avons pas reçu une, mais DEUX demandes de rançon de groupes qui prétendent détenir Metzen. Comme la saison des fêtes bat son plein, nous sommes enchaînés à la caisse enregistreuse ! Je vous en prie, trouvez Metzen et ramenez-le nous !$B$BLisez attentivement les lettres de rançon pour trouver des indices, et saupoudrez cette poudre de renne sur lui : elle le libéra de toutes ses entraves !$B$BJe vous en supplie, faites vite !', `Objectives_loc2` = 'Trouvez Metzen le renne. Utilisez les notes qui vous ont été fournies comme indices pour découvrir son lieu de détention.$B$BQuand vous aurez trouvé Metzen, saupoudrez sur lui la Bourse de poudre de renne qui vous a été remise. Cela devrait mettre fin à sa captivité.$B$BRapportez la Bourse de poudre de renne à Béachevé Chipsou à Orgrimmar quand Metzen aura été libéré.', `ObjectiveText1_loc2` = 'Trouver Metzen le Renne et le sauver.' WHERE `entry` = 8746;
UPDATE `locales_quest` SET `Title_loc2` = 'Cœur de rage', `Details_loc2` = '$C, rassemblez immédiatement une troupe pour enquêter sur la Fournaise du sang de la citadelle des Flammes infernales ! Et quand je dis immédiatement, princesse, ça veut dire « plus vite que ça ! »$B$BLa magie dont nous disposons nous dit qu’il s’y passe quelque chose de pas naturel. Mais il y a quelque chose là-dedans qui bloque tout enquête arcanique un peu sérieuse. C’est louche.$b$BAttendez-vous à rencontrer une très forte résistance – de tous les gens que nous avons envoyés là-bas, personne n’est revenu !$B$BFaites une reconnaissance complète, puis allez faire votre rapport au commandant de corps.', `Objectives_loc2` = 'Faire une enquête exhaustive sur la Fournaise du sang, puis en faire un rapport au commandant de corps Danath Trollemort, au bastion de l’Honneur dans la péninsule des Flammes infernales.', `EndText_loc2` = 'Enquête exhaustive à la Fournaise du sang' WHERE `entry` = 9607;
UPDATE `locales_quest` SET `Title_loc2` = 'Des champignons familiers', `Details_loc2` = 'Oui, c’est bien ça, je savais que j’avais déjà vu cette sous-classe de champignons ailleurs dans les marais !$B$BVers le nord, il y a un endroit qu’on appelle la Tourbière taillée. C\'est un drôle de nom, mais je ne sais pas d\'où il vient, je n\'y ai jamais mis les pieds. Il me faudrait des échantillons de ces champignons-là pour étayer mon hypothèse.$B$BFaites tout de même attention, $c. J\'ai entendu que des ogres s\'étaient installés là-bas, vous devrez prendre les échantillons sur eux. Peut-être est-ce pour cette raison que les seigneurs-tourbe n’y vont plus chercher leur nourriture ?', `Objectives_loc2` = 'Collectez 15 Échantillons de champignon et apportez-les à la gardienne Leesa\'oh au Poste de garde cénarien dans le marécage de Zangar.' WHERE `entry` = 9708;
UPDATE `locales_quest` SET `Title_loc2` = 'Les ruines de Boha\'mu', `Details_loc2` = 'Avant que mon peuple ne soit décimé par les orcs, Telredor était un lieu de retraite pour les anachorètes et spiritualistes draeneï. Un petit ordre d’anachorètes et de redresseurs de torts entretenait quelques sanctuaires dans cette région.$B$BDurant la guerre, nous avons perdu le contact avec ces anachorètes, et plus particulièrement avec ceux du temple de Boha’mu, au sud-ouest. D’après certains rapports, une tribu de Perdus s’est installée dans la région, et pourrait même utiliser les ruines. Allez voir les ruines de Boha’mu et revenez me dire ce que vous avez trouvé là-bas.', `Objectives_loc2` = 'L\'anachorète Ahuurn de Telredor veut que vous exploriez les Ruines de Boha\'mu.', `EndText_loc2` = 'Explorer les Ruines de Boha\'mu' WHERE `entry` = 9786;
UPDATE `locales_quest` SET `Title_loc2` = 'Une graine rare', `Details_loc2` = 'Vous n’êtes pas très bien $gpréparé: préparée; pour affronter les éléments perturbés de Nagrand. Avant de pouvoir aider le Cercle terrestre, vous devez vous aider vous-même.$B$BSi vous vous dirigez à l’ouest, vous trouverez des tas de crottin laissés par la vie sauvage de Nagrand. Vous devez fouiller le crottin pour trouver les restes digérés de caracoli de Nagrand. À partir de cette graine, je pourrai confectionner un comprimé qui vous aidera à affronter les forces terribles de la nature.$B$BRevenez me voir quand vous aurez rassemblé au moins deux poignées de caracolis… Des poignées d’ogre…', `Objectives_loc2` = 'L’Elémentalise Lo’ap, au Trône des éléments de Nagrand, veut que vous lui apportiez 15 Caracolis digérés' WHERE `entry` = 9800;
UPDATE `locales_quest` SET `Title_loc2` = 'La bénédiction d\'Incineratus', `Details_loc2` = 'Ces misérables Perdus, qui furent bannis à juste titre dans le marécage de Zangar, cherchent à répandre leur souillure sur d’autres régions de notre monde.$B$BJe suis allé consulter la sagesse des furies et j’ai obtenu leur bénédiction. Pour arrêter les dommages à la source, nous devons lâcher sur eux la colère des éléments !$B$BVoici le feu vivant, tiré de l’essence flamboyante d’Incineratus en personne. Rendez-vous à Ventejonc, au sud-est, et libérez le feu vivant sur leurs huttes ! Qu’ils goûtent ainsi la fureur des éléments !', `Objectives_loc2` = 'L’Elémentaliste Lo’ap, au Trône des éléments, en Nagrand, veut que vous détruisiez la Grande hutte, la Hutte de l’ouest, la Hutte du sud et la Hutte de l’est à Ventejonc.$B$BRendez le Feu vivant à l’Elémentaliste Lo’ap quand vous aurez terminé votre tâche.', `ObjectiveText1_loc2` = 'Grande hutte détruite', `ObjectiveText2_loc2` = 'Hutte de l’ouest détruite', `ObjectiveText3_loc2` = 'Hutte du sud détruite', `ObjectiveText4_loc2` = 'Hutte de l’est détruite' WHERE `entry` = 9805;
UPDATE `locales_quest` SET `Title_loc2` = 'Maîtrise de la chasse aux venterocs', `Details_loc2` = 'Si vous voulez traquer un jour les proies les plus puissantes, vous devez toujours repousser vos limites ! Vous n\'êtes pas encore $gprêt:prête;, mais je vais vous montrer le chemin.$B$BIl existe une autre espèce de venteroc encore plus meurtrière. Cherchez des venterocs voraces pour voir de quel bois vous êtes $gfait:faite;. Vous en trouverez au cœur de Nagrand, à l’ouest et au sud-ouest.', `Objectives_loc2` = 'Abattez 30 Venterocs voraces, puis retournez voir Fitz au safari de Nesingwary en Nagrand.' WHERE `entry` = 9855;
UPDATE `locales_quest` SET `Title_loc2` = 'Maîtrise de la chasse aux venterocs', `Details_loc2` = 'Vous êtes $gprêt:prête;, $c. Prêt à affronter la mère de tous les venterocs, Arrache-tripes ! L\'honneur exige qu\'après avoir tué tant de ses enfants, vous lui donniez une chance de vous vaincre !$B$BSi vous deviez survivre, apportez-moi son œil.', `Objectives_loc2` = 'Fitz, du safari de Nesingwary en Nagrand, veut que vous lui rameniez l\'Œil d’Arrache-tripes.' WHERE `entry` = 9856;
UPDATE `locales_quest` SET `Title_loc2` = 'Arrêter la contamination', `Details_loc2` = 'Je viens juste d’apprendre une catastrophe de proportions épiques, $N. Ces maudits Bourbesang ont pillé le village orc qui se trouve au nord-ouest d’ici, le poste de Berceau-de-l\'Été, et ont assassiné tous ses habitants. Pire encore, ils ont commencé à jeter les cadavres dans le lac Berceau-de-l\'Eté. Si ces corps pourrissent, la principale source d’eau potable de la région sera souillée.$B$BJe vais vous confier une tâche macabre, mais elle doit être accomplie. Prenez cette torche enchantée et retournez au Berceau-de-l\'Été. Brûlez tous les cadavres d’orc en décomposition.', `Objectives_loc2` = 'Otonbu le Sage, à Telaar en Nagrand, veut que vous utilisiez la Torche de feu liquide pour détruire 10 Cadavres de villageois du Berceau-de-l’été. Lorsque vous aurez terminé, rendez-lui la Torche de feu liquide.', `ObjectiveText1_loc2` = 'Cadavres de villageois de Berceau-de-l\'Été brûlés' WHERE `entry` = 9874;
UPDATE `locales_quest` SET `Title_loc2` = 'Le totem de Kar\'dash', `Details_loc2` = 'J’aurais été tué si vous n’étiez pas venu, $gétranger:étrangère;. Ils ont déjà assassiné tant de Kurenaï en cherchant leur relique perdue.$B$BIls cherchent le totem de Kar’dash. Et je ne comprends pas pourquoi ils pensent que nous savons quelque chose à son sujet. Un totem n’est-il pas un accessoire orc par nature ?$B$BCette information doit être communiquée à Arechron. Il sait peut-être pourquoi les Bourbesang capturent les Kurenaï et les torturent pour obtenir des informations sur un objet orc.$B$BAllez, partez avant que d’autres n’arrivent.', `Objectives_loc2` = 'Escortez le Captif kurenaï hors du poste du Berceau-de-l’été. Si vous y parvenez, allez parler à Arechron, à Telaar.', `EndText_loc2` = 'Libérer le Captif kurenaï' WHERE `entry` = 9879;
UPDATE `locales_quest` SET `Title_loc2` = 'Voler les voleurs', `Details_loc2` = 'Le prince-nexus Haramad nous a ordonné de ne pas commencer à travailler à l’intérieur d’Oshu’gun, car cela pourrait mettre un certain puissant naaru en colère. Cela ralentit grandement nos opérations.$B$BMais je pense que j’ai trouvé une faille.$B$BVoyez-vous, nous ne sommes pas les seuls éthériens attirés par ce diamant colossal. Un voleur appelé Gava’xi a conduit une bande de voleurs éthériens dans Oshu’gun, et ils ont commencés à en extraire de gros morceaux.$B$BVotre travail, $r, si vous l’acceptez, est de vous rendre là-bas et de récupérer ce qui est légitimement nôtre.', `Objectives_loc2` = 'Procurez-vous 10 Fragments de cristal d’Oshu’gun et remettez-les à Gezhe, au Point d\'ancrage Aeris en Nagrand.' WHERE `entry` = 9882;
UPDATE `locales_quest` SET `Title_loc2` = 'Gava\'xi', `Details_loc2` = 'La présence de voleurs éthériens dans cette région amuse peut-être Gezhe, qui ne voit que des opportunités partout où nous allons, mais elle représente une véritable menace contre la sécurité de nos opérations.$B$BLeur chef, Gava’xi, est un criminel dangereux, et le neutraliser est devenu ma priorité immédiate.$B$BSi vous voulez vous rendre utile, allez donc vous occuper de Gava’xi. Je veillerai à ce que vous soyez $grécompensé:récompensée; comme il se doit.', `Objectives_loc2` = 'Tuez Gava’xi près d’Oshu’gun, puis retournez voir Zerid au Point d\'ancrage Aeris, en Nagrand.' WHERE `entry` = 9900;
UPDATE `locales_quest` SET `Title_loc2` = 'Le Consortium a besoin de vous !', `Details_loc2` = 'Mon organisation, le Consortium, cherche des individus pleins de ressources, comme vous semblez l’être. Vous aurez bien du mal à trouver des éthériens plus honnêtes, plus travailleurs ou plus aimables que nous.$B$BTout ce que nous demandons est de la loyauté, du dévouement et une flexibilité morale raisonnable. Si vous êtes $gintéressé:intéressée; allez voir Gezhe, notre chef d’opérations au sol. Vous le trouverez au point d\'ancrage Aeris, au nord d’Oshu’gun.', `Objectives_loc2` = 'Présentez-vous à Gezhe au Point d\'ancrage Aeris en Nagrand.' WHERE `entry` = 9913;
UPDATE `locales_quest` SET `Title_loc2` = 'Les ruines de la Lame ardente', `Details_loc2` = 'Ces bandes de chasseurs ogres sont les annonciatrices d’une invasion. Nous devons les frapper avant que les ogres n’aient l’occasion d’amasser une armée suffisamment grande pour s’emparer de notre ville.$B$BVous allez avoir besoin de vous salir les mains, $r.$B$BLe plus grand regroupement de Rochepoing dans cette région se trouve aux ruines de la Lame ardente, presque directement à l’est de Telaar, près de la frontière de Terokkar. Allez là-bas et montrez aux Rochepoing que Telaar ne se pliera pas à leur volonté !', `Objectives_loc2` = 'Mo\'mor le Briseur, à Telaar en Nagrand, veut que vous tuiez 15 Écraseurs Rochepoing et 15 Mystiques Rochepoing.' WHERE `entry` = 9921;
UPDATE `locales_quest` SET `Title_loc2` = 'Les failles jumelles de Nagrand', `Details_loc2` = 'Vous avez fait une superbe démonstration, $N. Vous êtes $gprêt:prête; à recommencer ?$B$BJ’ai reçu des rapports sur la présence d’un gros contingent d’ogres Rochepoing, caché dans les failles jumelles de Nagrand, au nord-est d’ici, dans le bassin d’Halaani.$B$BAventurez-vous dans les failles et occupez-vous des ogres Rochepoing restants.', `Objectives_loc2` = 'Mo\'mor le Briseur, à Telaar en Nagrand, veut que vous tuiez 25 Guerriers Rochepoing et 25 Mages Rochepoing.' WHERE `entry` = 9922;
UPDATE `locales_quest` SET `Title_loc2` = 'Corki a encore disparu !', `Details_loc2` = '<Arechron soupire.>$B$BC’est tellement embarrassant. Vous vous souvenez de mon fils, Corki ? Vous l’avez secouru récemment, dans les ruines de la Lame ardente. Et bien, il s’est encore laissé emporter par sa curiosité. Il m’a dit qu’il allait enquêter sur la menace Rochepoing pour « tonton » Mo’mor, et il s’est enfui vers les tertres des ogres dans le Bassin d\'Halaani, au nord d’ici.$B$BVous pensez que vous pourriez suivre ses traces ? Vous auriez ma gratitude éternelle.', `Objectives_loc2` = 'Arechron, de Telaar, vous a demandé de retrouver et de libérer Corki.', `ObjectiveText1_loc2` = 'Corki libéré à nouveau' WHERE `entry` = 9924;
UPDATE `locales_quest` SET `Title_loc2` = 'La caravane ravagée', `Details_loc2` = 'J’appartenais à une caravane qui transportait des fournitures au Havre d’Orebor dans le marécage de Zangar. Nous approchions des limites du marécage lorsque nous avons été attaqués par une bande d’ogres Cogneguerre. Ils ont tué les autres et sont emparés de moi, ainsi que de toutes nos affaires.$b$BHeureusement, ils ont négligé de poster des gardes autour de ma cage. J’ai pu m’enfuir lorsqu’ils se sont endormis.$B$BIl est trop tard pour mes camarades, mais nous avons besoin des fournitures volées. La colline des Cogneguerre se trouve dans les montagnes, au nord-ouest de Nagrand.', `Objectives_loc2` = 'La chasseresse Kima de Telaar en Nagrand, veut que vous récupériez 20 Caisses de fournitures de Telaar.' WHERE `entry` = 9956;
UPDATE `locales_quest` SET `Title_loc2` = 'Il se fait appeler Altruis…', `Details_loc2` = 'Un être monté sur un drake du Néant est arrivé en ville la semaine dernière. Il s’est présenté sous le nom d’Altruis, et nous a posé des questions sur Nagrand.$B$BIl prétendait traquer la Légion. Que c’était son travail. Vous imaginez une telle folie ? Quelqu’un qui chasserait les démons volontairement ?$B$BAvant de partir, il nous a demandé de dire à tous les apprentis héros de passage qu’il resterait un moment à l’ouest de Nagrand, et que s’ils se cherchaient un but, ils pouvaient aller le voir.', `Objectives_loc2` = 'Si vous cherchez à affronter la Légion ardente, allez trouver Altruis le Souffrant dans l\'ouest de Nagrand.' WHERE `entry` = 9982;
UPDATE `locales_quest` SET `Title_loc2` = 'Observer le terrain', `Details_loc2` = 'Si vous voulez me servir d’yeux, il va falloir faire preuve de diligence. Néanstradamus vous conduira aux camps de la Légion, mais vous devez cataloguer tout ce que vous y verrez. Même le plus infime détail qui vous paraîtra sans importance pourra nous être utile.$B$BJe veux surtout que vous observiez les structures qui se trouvent dans le camp, et leurs défenses.$B$BNéanstradamus vous attend, $N. N’ayez pas peur, il vous protègera.', `Objectives_loc2` = 'Asseyez-vous et profitez du voyage. Parlez à Altruis quand vous aurez terminé l\'observation.', `EndText_loc2` = 'Camps de forge observés' WHERE `entry` = 9991;
UPDATE `locales_quest` SET `Title_loc2` = 'Une vision mystique', `Details_loc2` = 'Une étrange vision me hante, $N. Je vois un nuage de fumée s\'élèver sans fin vers le ciel, dans le sillon d\'un brasier géant qui s\'éloigne toujours plus vite. Ce n\'est ni un phénomène naturel, ni une création maléfique, ça je le sais.$B$BJ\'ignore à quoi cela ressemble, tout ce que je sais est qu\'il s\'agit du produit du labeur d\'un grand nombre de gens. Mais sans aide supplémentaire, il se peut que cette création ne voie jamais le jour.$B$BRendez-vous au Raz-de-Néant, $c. Trouvez les responsables de cette création, et offrez-leur votre aide.', `Objectives_loc2` = 'Parlez au Chef-de-fusée Karlingue dans la Zone 52.' WHERE `entry` = 11042;
UPDATE `locales_quest` SET `Title_loc2` = 'Zut, Bricole est entrée dans la nécropole !', `Details_loc2` = 'J\'ai bien dit à Bricole de ne pas se déplacer seule, mais il FALLAIT qu\'elle explore cette nécropole accidentée, à l\'ouest.$B$BJe suis 100', `Objectives_loc2` = 'Trouvez Bricole Sifflemèche à Talramas.' WHERE `entry` = 11697;
