SET NAMES utf8;


##################
# SCRIPT_TEXTS
##################

UPDATE `script_texts` SET `content_loc2` = 'Ma chute n\'y changera rien ! Le maître vous aura ! Vous vous noierez dans votre propre sang ! Ce monde brûlera ! Ahhhhhhh !!' WHERE `entry` = -1585029;
UPDATE `script_texts` SET `content_loc2` = 'Ne vous sentez pas... trop à l\'aise !' WHERE `entry` = -1585028;
UPDATE `script_texts` SET `content_loc2` = 'Maître ! Donne moi la force !' WHERE `entry` = -1585027;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez me trouver renversant !' WHERE `entry` = -1585026;
UPDATE `script_texts` SET `content_loc2` = 'Felomin ashal !' WHERE `entry` = -1585025;
UPDATE `script_texts` SET `content_loc2` = 'La vengeance brûle !' WHERE `entry` = -1585024;
UPDATE `script_texts` SET `content_loc2` = 'Ne prenez pas un air si satisfait. Je sais à quoi vous pensez, mais le Donjon de la Tempête n\'était qu\'un contretemps. Croyez-vous vraiment que je confierais notre avenir à un aveugle ? Un bâtard demi elfe de la nuit ?  Ahahaha ! Oh non ! Ce n\'était qu\'une étape vers un projet plus global ! C\'est ce qui vous amène ici. Et cette fois vous ne vous en mêlerez pas !' WHERE `entry` = -1585023;
UPDATE `script_texts` SET `content_loc2` = 'Ce n\'était pas... prévu...' WHERE `entry` = -1585022;
UPDATE `script_texts` SET `content_loc2` = 'C\'était très sympa ! Vraiment !' WHERE `entry` = -1585021;
UPDATE `script_texts` SET `content_loc2` = 'Que ce nombre un est solitaire.' WHERE `entry` = -1585020;
UPDATE `script_texts` SET `content_loc2` = 'On ne peut plus vraiment parler de groupe, non ?' WHERE `entry` = -1585019;
UPDATE `script_texts` SET `content_loc2` = 'J\'aurais juré que vous étiez plus nombreux.' WHERE `entry` = -1585018;
UPDATE `script_texts` SET `content_loc2` = 'C\'est ce que j\'appelle un bon début.' WHERE `entry` = -1585017;
UPDATE `script_texts` SET `content_loc2` = 'Maudit laquais ! Je vous achèverai moi-même !' WHERE `entry` = -1585016;
UPDATE `script_texts` SET `content_loc2` = 'Là ça commence à m\'exaspérer !' WHERE `entry` = -1585015;
UPDATE `script_texts` SET `content_loc2` = 'Hé bien, quelle chance !' WHERE `entry` = -1585014;
UPDATE `script_texts` SET `content_loc2` = 'Comme c\'est horrible !' WHERE `entry` = -1585013;
UPDATE `script_texts` SET `content_loc2` = 'Exterminez-les !' WHERE `entry` = -1585012;
UPDATE `script_texts` SET `content_loc2` = 'Con...su...mez.' WHERE `entry` = -1585010;
UPDATE `script_texts` SET `content_loc2` = 'Li...bé...ré...' WHERE `entry` = -1585009;
UPDATE `script_texts` SET `content_loc2` = 'Ir...ré...pré...si...ble.' WHERE `entry` = -1585008;
UPDATE `script_texts` SET `content_loc2` = 'Drai...ner...vie !' WHERE `entry` = -1585007;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Encore ! Il m\'en faut encore !' WHERE `entry` = -1585005;
UPDATE `script_texts` SET `content_loc2` = 'Je suis invincible !' WHERE `entry` = -1585004;
UPDATE `script_texts` SET `content_loc2` = 'Assez de distractions !' WHERE `entry` = -1585003;
UPDATE `script_texts` SET `content_loc2` = 'Hum... Oui ! Je suis un dieu !' WHERE `entry` = -1585002;
UPDATE `script_texts` SET `content_loc2` = 'Ma faim n\'a pas de limite !' WHERE `entry` = -1585001;
UPDATE `script_texts` SET `content_loc2` = 'Vous me faites perdre mon temps.' WHERE `entry` = -1585000;
UPDATE `script_texts` SET `content_loc2` = 'Malygos ! Seigneur ! J\'ai fais de mon mieux !' WHERE `entry` = -1580035;
UPDATE `script_texts` SET `content_loc2` = 'Parle ! Ça n\'a que trop duré !' WHERE `entry` = -1580034;
UPDATE `script_texts` SET `content_loc2` = 'Tu vas me dire où ils sont !' WHERE `entry` = -1580033;
UPDATE `script_texts` SET `content_loc2` = 'Ou est Anveena démon ? Qu\'est il devenu de Kalec ?' WHERE `entry` = -1580032;
UPDATE `script_texts` SET `content_loc2` = 'Attendez mes amis ! Ce démon doit nous renseigner avant de recevoir son dû.' WHERE `entry` = -1580031;
UPDATE `script_texts` SET `content_loc2` = 'Argh ! Bien joué ! Ça devient enfin intéressant...' WHERE `entry` = -1580030;
UPDATE `script_texts` SET `content_loc2` = 'Vous appellez ça un réel défi ? Mourez !' WHERE `entry` = -1580029;
UPDATE `script_texts` SET `content_loc2` = 'À chaque jour son glorieux combat !' WHERE `entry` = -1580027;
UPDATE `script_texts` SET `content_loc2` = 'Donnez-moi de l\'action !' WHERE `entry` = -1580026;
UPDATE `script_texts` SET `content_loc2` = 'Trop facile !' WHERE `entry` = -1580025;
UPDATE `script_texts` SET `content_loc2` = 'Viande froide !' WHERE `entry` = -1580024;
UPDATE `script_texts` SET `content_loc2` = 'Meurs insecte !' WHERE `entry` = -1580023;
UPDATE `script_texts` SET `content_loc2` = 'Rahhhh ! Encore des agneaux pour l\'abattoir !' WHERE `entry` = -1580022;
UPDATE `script_texts` SET `content_loc2` = 'Venez tenter votre chance !' WHERE `entry` = -1580021;
UPDATE `script_texts` SET `content_loc2` = 'C\'était marrant mais j\'attends toujours un réel défi !' WHERE `entry` = -1580020;
UPDATE `script_texts` SET `content_loc2` = 'Je vais t\'écraser !' WHERE `entry` = -1580019;
UPDATE `script_texts` SET `content_loc2` = 'Ta magie est faible !' WHERE `entry` = -1580018;
UPDATE `script_texts` SET `content_loc2` = 'Misérable lézard ! La mort est la seule réponse que tu trouveras ici !' WHERE `entry` = -1580017;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai assez joué avec vous !' WHERE `entry` = -1580016;
UPDATE `script_texts` SET `content_loc2` = 'On ne vous avait pas dit ? Je gagne toujours !' WHERE `entry` = -1580015;
UPDATE `script_texts` SET `content_loc2` = 'Que coule votre sang !' WHERE `entry` = -1580013;
UPDATE `script_texts` SET `content_loc2` = 'Je me délecte de votre détresse.' WHERE `entry` = -1580012;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis jamais du côté des perdants !' WHERE `entry` = -1580011;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahaha ! Il n\'y aura pas de sursis ! Mon travail ici est presque terminé !' WHERE `entry` = -1580010;
UPDATE `script_texts` SET `content_loc2` = 'Je vous suis redevable à jamais. Et lorsque nous aurons triomphé de Kil\'Jaeden le monde entier vous sera redevable également.' WHERE `entry` = -1580009;
UPDATE `script_texts` SET `content_loc2` = 'Vite ! C\'est en train de m\'emporter !' WHERE `entry` = -1580008;
UPDATE `script_texts` SET `content_loc2` = 'Arghhhh ! Aidez moi je vais perdre l\'esprit !' WHERE `entry` = -1580007;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai besoin... de votre aide... je ne tiendrai... pas longtemps...' WHERE `entry` = -1580006;
UPDATE `script_texts` SET `content_loc2` = 'Mon réveil est total ! Vous allez tous mourir !' WHERE `entry` = -1580005;
UPDATE `script_texts` SET `content_loc2` = 'Vous étiez prévenus !' WHERE `entry` = -1580004;
UPDATE `script_texts` SET `content_loc2` = 'Au nom de Kil\'Jaeden !' WHERE `entry` = -1580003;
UPDATE `script_texts` SET `content_loc2` = 'La souffrance ne fait que commencer !' WHERE `entry` = -1580002;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez expier !' WHERE `entry` = -1580001;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serais plus jamais l\'esclave de Malygos ! Osez me défier et vous serez détruits !' WHERE `entry` = -1580000;
UPDATE `script_texts` SET `content_loc2` = 'Je vous attendrai de l\'autre côté.' WHERE `entry` = -1568023;
UPDATE `script_texts` SET `content_loc2` = 'Les Amanis... ils vont régner à nouveau !' WHERE `entry` = -1568022;
UPDATE `script_texts` SET `content_loc2` = 'Ahahahaha ! Alors, qu\'est ce que t\'as à dire, hein ?' WHERE `entry` = -1568021;
UPDATE `script_texts` SET `content_loc2` = 'C\'était votre chance ! Maintenant c\'est trop tard !' WHERE `entry` = -1568020;
UPDATE `script_texts` SET `content_loc2` = 'Place ! Voilà le Nalorakk !' WHERE `entry` = -1568019;
UPDATE `script_texts` SET `content_loc2` = 'Vous demandez la bête ? Je vais vous donnez la bête !' WHERE `entry` = -1568018;
UPDATE `script_texts` SET `content_loc2` = 'Ça va faire mal !' WHERE `entry` = -1568017;
UPDATE `script_texts` SET `content_loc2` = 'Vous serez mort bien vite !' WHERE `entry` = -1568016;
UPDATE `script_texts` SET `content_loc2` = 'J\'vous sens étranger ! Essayez pas de retarder votre destin ! Venez à moi maintenant ! Et le sacrifice... il sera rapide !' WHERE `entry` = -1568015;
UPDATE `script_texts` SET `content_loc2` = 'Argh... Y a quoi qu\'est mieux que servir l\'esprit de l\'ours pour l\'éternité ? Approchez maintenant ! Venez me donner vos âmes !' WHERE `entry` = -1568014;
UPDATE `script_texts` SET `content_loc2` = 'Oh ! Je vais perdre ma patience ! Allez et faites leur regretter d\'être nés !' WHERE `entry` = -1568013;
UPDATE `script_texts` SET `content_loc2` = 'Au galop ! Et rapportez-moi des têtes.' WHERE `entry` = -1568012;
UPDATE `script_texts` SET `content_loc2` = 'Gardes ! Allez ! C\'est quoi qui vous fait le plus peur hein ? Eux ou moi ?' WHERE `entry` = -1568011;
UPDATE `script_texts` SET `content_loc2` = 'Gardes ! Bougez-vous ! C\'est l\'heure du massacre !' WHERE `entry` = -1568010;
UPDATE `script_texts` SET `content_loc2` = 'Venez mes amis ! Vos corps, y vont nourrir mes petits ! Vos âmes, elles vont me donner la puissance !' WHERE `entry` = -1568009;
UPDATE `script_texts` SET `content_loc2` = 'Venez étranger ! L\'esprit du faucon-dragon, il a faim d\'âmes honorables.' WHERE `entry` = -1568008;
UPDATE `script_texts` SET `content_loc2` = 'Zul\'Jin... Il a une surprise pour vous !' WHERE `entry` = -1568007;
UPDATE `script_texts` SET `content_loc2` = 'Tazaga-choo !' WHERE `entry` = -1568006;
UPDATE `script_texts` SET `content_loc2` = 'C\'est fini pour toi !' WHERE `entry` = -1568005;
UPDATE `script_texts` SET `content_loc2` = 'Le temps, il est écoulé !' WHERE `entry` = -1568004;
UPDATE `script_texts` SET `content_loc2` = 'J\'vais vous montrer la force... du nombre.' WHERE `entry` = -1568003;
UPDATE `script_texts` SET `content_loc2` = 'Sont où mes perces-coques ? Au boulot ! Faut que ça éclose !' WHERE `entry` = -1568002;
UPDATE `script_texts` SET `content_loc2` = 'Je vais vous cramer !' WHERE `entry` = -1568001;
UPDATE `script_texts` SET `content_loc2` = 'Les esprits du vent, ils vont être votre fin !' WHERE `entry` = -1568000;
UPDATE `script_texts` SET `content_loc2` = 'Aaargh...' WHERE `entry` = -1565018;
UPDATE `script_texts` SET `content_loc2` = 'Meurs...' WHERE `entry` = -1565017;
UPDATE `script_texts` SET `content_loc2` = 'Indigne...' WHERE `entry` = -1565016;
UPDATE `script_texts` SET `content_loc2` = 'Fini..' WHERE `entry` = -1565015;
UPDATE `script_texts` SET `content_loc2` = 'Prie... pour ta vie...' WHERE `entry` = -1565014;
UPDATE `script_texts` SET `content_loc2` = 'Reste là...' WHERE `entry` = -1565013;
UPDATE `script_texts` SET `content_loc2` = 'On ne s\'échappe pas...' WHERE `entry` = -1565012;
UPDATE `script_texts` SET `content_loc2` = 'Cavalez...' WHERE `entry` = -1565011;
UPDATE `script_texts` SET `content_loc2` = 'Venez... mourir...' WHERE `entry` = -1565010;
UPDATE `script_texts` SET `content_loc2` = 'Gruul... vous écrasera...' WHERE `entry` = -1565009;
UPDATE `script_texts` SET `content_loc2` = 'Maulgar est roi !' WHERE `entry` = -1565008;
UPDATE `script_texts` SET `content_loc2` = 'Aha-ha ha ha!' WHERE `entry` = -1565007;
UPDATE `script_texts` SET `content_loc2` = 'T\'es pas si solide en fait !' WHERE `entry` = -1565006;
UPDATE `script_texts` SET `content_loc2` = 'Bien ! Maintenant c\'est à moi !' WHERE `entry` = -1565005;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai pas peur de vous !' WHERE `entry` = -1565004;
UPDATE `script_texts` SET `content_loc2` = 'Ahaha ! Ça ne prouve rien !' WHERE `entry` = -1565003;
UPDATE `script_texts` SET `content_loc2` = 'Tuer le suivant sera pas si facile !' WHERE `entry` = -1565002;
UPDATE `script_texts` SET `content_loc2` = 'Vous ne terrasserez pas la main de Gruul !' WHERE `entry` = -1565001;
UPDATE `script_texts` SET `content_loc2` = 'Les Gronns sont la seule vraie puissance de l\'Outreterre !' WHERE `entry` = -1565000;
UPDATE `script_texts` SET `content_loc2` = 'Diel ma\'ahn...oreindel\'o' WHERE `entry` = -1564096;
UPDATE `script_texts` SET `content_loc2` = 'Le destin... attend.' WHERE `entry` = -1564095;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez... de la chance...' WHERE `entry` = -1564094;
UPDATE `script_texts` SET `content_loc2` = 'Seigneur Illidan... je..' WHERE `entry` = -1564093;
UPDATE `script_texts` SET `content_loc2` = 'Belasa menoor!' WHERE `entry` = -1564092;
UPDATE `script_texts` SET `content_loc2` = 'Comme il convient.' WHERE `entry` = -1564091;
UPDATE `script_texts` SET `content_loc2` = 'Quel glorieux coup de grâce.' WHERE `entry` = -1564090;
UPDATE `script_texts` SET `content_loc2` = 'Bien joué !' WHERE `entry` = -1564089;
UPDATE `script_texts` SET `content_loc2` = 'Shorel\'aran' WHERE `entry` = -1564088;
UPDATE `script_texts` SET `content_loc2` = 'Mon travail est terminé.' WHERE `entry` = -1564087;
UPDATE `script_texts` SET `content_loc2` = 'Bel effort.' WHERE `entry` = -1564086;
UPDATE `script_texts` SET `content_loc2` = 'Selama am\'oronor !' WHERE `entry` = -1564085;
UPDATE `script_texts` SET `content_loc2` = 'Sha\'amoor ara mashal ?' WHERE `entry` = -1564084;
UPDATE `script_texts` SET `content_loc2` = 'Je suis pleine de surprises.' WHERE `entry` = -1564083;
UPDATE `script_texts` SET `content_loc2` = 'Anar\'alah belore !' WHERE `entry` = -1564082;
UPDATE `script_texts` SET `content_loc2` = 'Vous êtes à moi !' WHERE `entry` = -1564081;
UPDATE `script_texts` SET `content_loc2` = 'Diel fin\'al' WHERE `entry` = -1564080;
UPDATE `script_texts` SET `content_loc2` = 'Pas de seconde chance !' WHERE `entry` = -1564079;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'êtes pas taillé pour ça !' WHERE `entry` = -1564078;
UPDATE `script_texts` SET `content_loc2` = 'Savourez vos derniers instants.' WHERE `entry` = -1564077;
UPDATE `script_texts` SET `content_loc2` = 'Sha\'amoor sine menoor !' WHERE `entry` = -1564076;
UPDATE `script_texts` SET `content_loc2` = 'Pour Quel\'Thalas ! Pour le Puit de Soleil !' WHERE `entry` = -1564075;
UPDATE `script_texts` SET `content_loc2` = 'Vous voulez me tuer ? Ahahah ! Vous d\'abord !' WHERE `entry` = -1564074;
UPDATE `script_texts` SET `content_loc2` = 'Assez joué !' WHERE `entry` = -1564073;
UPDATE `script_texts` SET `content_loc2` = 'Allons donc... quelle grossièreté. Bandal !' WHERE `entry` = -1564072;
UPDATE `script_texts` SET `content_loc2` = 'Fuyez ou mourez !' WHERE `entry` = -1564071;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai mieux à faire.' WHERE `entry` = -1564070;
UPDATE `script_texts` SET `content_loc2` = 'Vous voulez me tester ?' WHERE `entry` = -1564069;
UPDATE `script_texts` SET `content_loc2` = 'Je ne vous... laisserez pas... m\'oublier !' WHERE `entry` = -1564068;
UPDATE `script_texts` SET `content_loc2` = 'Prenez garde, pleutre !' WHERE `entry` = -1564067;
UPDATE `script_texts` SET `content_loc2` = 'A genoux !' WHERE `entry` = -1564066;
UPDATE `script_texts` SET `content_loc2` = 'Assez ! Terminé !' WHERE `entry` = -1564065;
UPDATE `script_texts` SET `content_loc2` = '<rire machiavélique>' WHERE `entry` = -1564064;
UPDATE `script_texts` SET `content_loc2` = 'C\'est... stupide.' WHERE `entry` = -1564063;
UPDATE `script_texts` SET `content_loc2` = 'Prenez garde : je suis vivant !' WHERE `entry` = -1564062;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serai jamais loin...' WHERE `entry` = -1564061;
UPDATE `script_texts` SET `content_loc2` = 'Je vous attendrai...' WHERE `entry` = -1564060;
UPDATE `script_texts` SET `content_loc2` = 'Méfiez-vous de ce que vous désirez.' WHERE `entry` = -1564059;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez les yeux plus gros que le ventre.' WHERE `entry` = -1564058;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Vous allez rester avec nous maintenant.' WHERE `entry` = -1564057;
UPDATE `script_texts` SET `content_loc2` = 'Le bonheur est à portée de main.' WHERE `entry` = -1564056;
UPDATE `script_texts` SET `content_loc2` = 'Vous pouvez avoir tout ce que vous désirez... en y mettant le prix.' WHERE `entry` = -1564055;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que je fais maintenant ?' WHERE `entry` = -1564053;
UPDATE `script_texts` SET `content_loc2` = 'Je ne veux pas y retourner !' WHERE `entry` = -1564052;
UPDATE `script_texts` SET `content_loc2` = 'La douleur ne fait que commencer !' WHERE `entry` = -1564051;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'ai pas demandé ça !' WHERE `entry` = -1564050;
UPDATE `script_texts` SET `content_loc2` = 'Regardez ce que vous m\'avez fait faire !' WHERE `entry` = -1564049;
UPDATE `script_texts` SET `content_loc2` = 'Ne me laissez pas seul !' WHERE `entry` = -1564048;
UPDATE `script_texts` SET `content_loc2` = 'Douleurs et souffrances ! Voilà tout ce qui vous attends.' WHERE `entry` = -1564047;
UPDATE `script_texts` SET `content_loc2` = 'La roue... tourne... encore...' WHERE `entry` = -1564046;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez être un peu plus respectueux !' WHERE `entry` = -1564045;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai quelque chose pour vous.' WHERE `entry` = -1564044;
UPDATE `script_texts` SET `content_loc2` = 'Laissez tomber.' WHERE `entry` = -1564043;
UPDATE `script_texts` SET `content_loc2` = 'La mort... ce n\'est pas si terrible.' WHERE `entry` = -1564042;
UPDATE `script_texts` SET `content_loc2` = 'De quoi avez-vous peur ?' WHERE `entry` = -1564041;
UPDATE `script_texts` SET `content_loc2` = 'Le pire est à venir...' WHERE `entry` = -1564040;
UPDATE `script_texts` SET `content_loc2` = 'Vous me serez utile.' WHERE `entry` = -1564039;
UPDATE `script_texts` SET `content_loc2` = 'À moi, la vengeance !' WHERE `entry` = -1564038;
UPDATE `script_texts` SET `content_loc2` = 'J\'étais le premier vous savez... la roue de mon destin a fait tellement de tour... il s\'est écoulé tant de temps... j\'ai beaucoup à rattraper.' WHERE `entry` = -1564037;
UPDATE `script_texts` SET `content_loc2` = 'Aaaahrg...' WHERE `entry` = -1564036;
UPDATE `script_texts` SET `content_loc2` = 'Je vais arracher la chair de vos os !' WHERE `entry` = -1564035;
UPDATE `script_texts` SET `content_loc2` = '<glossolalie>' WHERE `entry` = -1564034;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai grand faim !' WHERE `entry` = -1564033;
UPDATE `script_texts` SET `content_loc2` = 'Boire votre sang ! Manger votre chair !' WHERE `entry` = -1564032;
UPDATE `script_texts` SET `content_loc2` = 'Encore ! J\'en veux encore !' WHERE `entry` = -1564031;
UPDATE `script_texts` SET `content_loc2` = 'Au banquet !' WHERE `entry` = -1564030;
UPDATE `script_texts` SET `content_loc2` = 'La Horde... va... vous écraser !' WHERE `entry` = -1564029;
UPDATE `script_texts` SET `content_loc2` = 'Je n\'avais pas terminé !' WHERE `entry` = -1564028;
UPDATE `script_texts` SET `content_loc2` = 'Arrétez de jouer avec mes sentiments !' WHERE `entry` = -1564027;
UPDATE `script_texts` SET `content_loc2` = 'Les histoires d\'amour finissent mal en général.' WHERE `entry` = -1564026;
UPDATE `script_texts` SET `content_loc2` = 'Un de perdu, dix de retrouvés.' WHERE `entry` = -1564025;
UPDATE `script_texts` SET `content_loc2` = 'Je suis... toute à vous.' WHERE `entry` = -1564024;
UPDATE `script_texts` SET `content_loc2` = 'Soyez pas timide.' WHERE `entry` = -1564023;
UPDATE `script_texts` SET `content_loc2` = 'Vous avez l\'air un peu tendu.' WHERE `entry` = -1564022;
UPDATE `script_texts` SET `content_loc2` = 'Alors... vous êtes en vacance ?' WHERE `entry` = -1564021;
UPDATE `script_texts` SET `content_loc2` = 'Vous vous amusez bien ?' WHERE `entry` = -1564020;
UPDATE `script_texts` SET `content_loc2` = 'Pas très impressionnant.' WHERE `entry` = -1564019;
UPDATE `script_texts` SET `content_loc2` = 'Vous jouez, vous payez.' WHERE `entry` = -1564018;
UPDATE `script_texts` SET `content_loc2` = 'Non ! Pas encore !' WHERE `entry` = -1564014;
UPDATE `script_texts` SET `content_loc2` = 'Je ne tiendrai pas très longtemps' WHERE `entry` = -1564013;
UPDATE `script_texts` SET `content_loc2` = 'Le seigneur Illidan va... vous écraser.' WHERE `entry` = -1564009;
UPDATE `script_texts` SET `content_loc2` = 'Ma puissance à ses limites ! Meurs ! Meurs !' WHERE `entry` = -1564008;
UPDATE `script_texts` SET `content_loc2` = 'Bal\'amer ch\'itah !' WHERE `entry` = -1564007;
UPDATE `script_texts` SET `content_loc2` = 'Le sang va couler !' WHERE `entry` = -1564006;
UPDATE `script_texts` SET `content_loc2` = 'Bel\'anen dal\'lorei!' WHERE `entry` = -1564005;
UPDATE `script_texts` SET `content_loc2` = 'Il est temps pour vous de partir.' WHERE `entry` = -1564004;
UPDATE `script_texts` SET `content_loc2` = 'Votre réussite n\'aura pas duré !' WHERE `entry` = -1564003;
UPDATE `script_texts` SET `content_loc2` = 'Je m\'occuperai de vous tout à l\'heure.' WHERE `entry` = -1564002;
UPDATE `script_texts` SET `content_loc2` = 'Restez là !' WHERE `entry` = -1564001;
UPDATE `script_texts` SET `content_loc2` = 'Vous allez mourir au nom de Dame Vashj !' WHERE `entry` = -1564000;
UPDATE `script_texts` SET `content_loc2` = 'Je ne gâcherai pas cette chance. J\'irai à la rencontre de mon destin.' WHERE `entry` = -1560047;
UPDATE `script_texts` SET `content_loc2` = 'Merci étranger. Vous m\'avez offert l\'espoir.' WHERE `entry` = -1560046;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai vraiment une dette envers vous, étranger.' WHERE `entry` = -1560045;
UPDATE `script_texts` SET `content_loc2` = 'Ce n\'est pas ce que je voulais !' WHERE `entry` = -1560044;
UPDATE `script_texts` SET `content_loc2` = 'Nous n\'aurions pas dû en arriver là !' WHERE `entry` = -1560043;
UPDATE `script_texts` SET `content_loc2` = 'Vous m\'avez forcé la main !' WHERE `entry` = -1560042;
UPDATE `script_texts` SET `content_loc2` = 'L\'Ondenoire va avoir beaucoup de compte à rendre.' WHERE `entry` = -1560041;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis plus un esclave.' WHERE `entry` = -1560040;
UPDATE `script_texts` SET `content_loc2` = 'J\'attends ce jour depuis bien trop longtemps... hors de ma route !' WHERE `entry` = -1560039;
UPDATE `script_texts` SET `content_loc2` = 'J\'ai gagné ma liberté !' WHERE `entry` = -1560038;
UPDATE `script_texts` SET `content_loc2` = 'Un bon jour... pour mourir...' WHERE `entry` = -1560037;
UPDATE `script_texts` SET `content_loc2` = 'Taretha...' WHERE `entry` = -1560036;
UPDATE `script_texts` SET `content_loc2` = 'Je me battrai jusqu\'au bout !' WHERE `entry` = -1560035;
UPDATE `script_texts` SET `content_loc2` = 'L\'avenir semble bien sinistre...' WHERE `entry` = -1560034;
UPDATE `script_texts` SET `content_loc2` = 'Adieu Taretha ! Je n\'oublierais jamais votre bonté.' WHERE `entry` = -1560033;
UPDATE `script_texts` SET `content_loc2` = 'Non !' WHERE `entry` = -1560032;
UPDATE `script_texts` SET `content_loc2` = 'C\'était qui ? Ou quoi ?' WHERE `entry` = -1560031;
UPDATE `script_texts` SET `content_loc2` = 'Chevauchons !' WHERE `entry` = -1560028;
UPDATE `script_texts` SET `content_loc2` = 'Très bien, Moulin-de-Tarren se trouve plus à l\'Ouest. Puisque le temps nous est compté.' WHERE `entry` = -1560027;
UPDATE `script_texts` SET `content_loc2` = 'Je ne serais plus jamais enchaîné !' WHERE `entry` = -1560026;
UPDATE `script_texts` SET `content_loc2` = 'Un cavalier approche.' WHERE `entry` = -1560025;
UPDATE `script_texts` SET `content_loc2` = 'Très bien ! Allons-y !' WHERE `entry` = -1560023;
UPDATE `script_texts` SET `content_loc2` = 'Le projet continuera...' WHERE `entry` = -1554027;
UPDATE `script_texts` SET `content_loc2` = 'On dirait bien que vous avez perdu.' WHERE `entry` = -1554026;
UPDATE `script_texts` SET `content_loc2` = 'Une simple petite nuisance.' WHERE `entry` = -1554025;
UPDATE `script_texts` SET `content_loc2` = 'Je préfère les travaux pratiques !' WHERE `entry` = -1554024;
UPDATE `script_texts` SET `content_loc2` = 'Il est temps de compléter mon équipe de travail.' WHERE `entry` = -1554023;
UPDATE `script_texts` SET `content_loc2` = 'Vous êtes à mon service maintenant.' WHERE `entry` = -1554022;
UPDATE `script_texts` SET `content_loc2` = 'Je recherche un bon coéquipier.' WHERE `entry` = -1554021;
UPDATE `script_texts` SET `content_loc2` = 'Notre calendrier est serré ! Je ne vous laisserai pas perturber notre travail !' WHERE `entry` = -1554020;
UPDATE `script_texts` SET `content_loc2` = 'Anu...bala belore...alon.' WHERE `entry` = -1554019;
UPDATE `script_texts` SET `content_loc2` = 'En\'dala finel el\'dal' WHERE `entry` = -1554018;
UPDATE `script_texts` SET `content_loc2` = 'Et n\'y revenez pas !' WHERE `entry` = -1554017;
UPDATE `script_texts` SET `content_loc2` = 'Anar\'endal dracon !' WHERE `entry` = -1554016;
UPDATE `script_texts` SET `content_loc2` = 'Vous supporterez toute cette chaleur ?' WHERE `entry` = -1554015;
UPDATE `script_texts` SET `content_loc2` = 'Je ne suis pas seule.' WHERE `entry` = -1554014;
UPDATE `script_texts` SET `content_loc2` = 'Vous n\'aimez pas la vie c\'est ca ?' WHERE `entry` = -1554013;
UPDATE `script_texts` SET `content_loc2` = 'Mes calculs ne prévoyaient pas...' WHERE `entry` = -1554011;
UPDATE `script_texts` SET `content_loc2` = 'L\'opération continuera selon le plan.' WHERE `entry` = -1554010;
UPDATE `script_texts` SET `content_loc2` = 'Une conclusion bien prévisible.' WHERE `entry` = -1554009;
UPDATE `script_texts` SET `content_loc2` = 'Un peu dépassé, mais très efficace.' WHERE `entry` = -1554008;
UPDATE `script_texts` SET `content_loc2` = 'Avec l\'angle et la vitesse d\'approche parfaite...' WHERE `entry` = -1554007;
UPDATE `script_texts` SET `content_loc2` = 'Il vous reste approximativement cinq secondes à vivre.' WHERE `entry` = -1554006;
UPDATE `script_texts` SET `content_loc2` = 'Voilà... impondérable...' WHERE `entry` = -1554005;
UPDATE `script_texts` SET `content_loc2` = 'C\'était la seule issue logique.' WHERE `entry` = -1554004;
UPDATE `script_texts` SET `content_loc2` = 'Votre stratégie était imparfaite.' WHERE `entry` = -1554003;
UPDATE `script_texts` SET `content_loc2` = 'Et si ma division est bien posée, je crois que vous êtes mort !' WHERE `entry` = -1554002;
UPDATE `script_texts` SET `content_loc2` = 'Mesurer deux fois, couper une fois.' WHERE `entry` = -1554001;
UPDATE `script_texts` SET `content_loc2` = 'Je vous prédis une mort douloureuse !' WHERE `entry` = -1554000;
UPDATE `script_texts` SET `content_loc2` = 'Je suis si troublé... ce n\'est pas... ma place...' WHERE `entry` = -1553012;
UPDATE `script_texts` SET `content_loc2` = 'Peut-être n\'est ce pas... Non ! Nous nous battrons ! Venez à moi !' WHERE `entry` = -1553011;
UPDATE `script_texts` SET `content_loc2` = 'À moi mes enfants !' WHERE `entry` = -1553010;
UPDATE `script_texts` SET `content_loc2` = 'Qu\'est ce que je fais ? Pourquoi est ce que...' WHERE `entry` = -1553009;
UPDATE `script_texts` SET `content_loc2` = 'Vous devez mourir... euh... attendez ce n\'est pas... non non... euh, si ! Vous devez mourir !' WHERE `entry` = -1553008;
UPDATE `script_texts` SET `content_loc2` = 'Qui trouble ce sanctuaire ?' WHERE `entry` = -1553007;
UPDATE `script_texts` SET `content_loc2` = 'Il faut préserver... les spécimens...' WHERE `entry` = -1553005;
UPDATE `script_texts` SET `content_loc2` = 'La nature se plie à ma volonté.' WHERE `entry` = -1553004;
UPDATE `script_texts` SET `content_loc2` = 'Endorel aluminor !' WHERE `entry` = -1553003;
UPDATE `script_texts` SET `content_loc2` = 'Allez nourrir les vers !' WHERE `entry` = -1553002;
UPDATE `script_texts` SET `content_loc2` = 'Votre cycle de vie est maintenant terminé !' WHERE `entry` = -1553001;
UPDATE `script_texts` SET `content_loc2` = 'Que faîtes-vous ? Ce sont des spécimens très fragiles !' WHERE `entry` = -1553000;
UPDATE `script_texts` SET `content_loc2` = 'Bienvenu, Ô tout-puissant. Je suis votre humble serviteur.' WHERE `entry` = -1552030;
UPDATE `script_texts` SET `content_loc2` = 'Il reste une dernière cellule... Oui tout puissant... tout de suite !' WHERE `entry` = -1552029;
UPDATE `script_texts` SET `content_loc2` = 'L\'anarchie ! Le chaos le plus total ! Oh quelle grande sagesse est la vôtre ! Oui tout est clair maintenant ! Bien sur !' WHERE `entry` = -1552028;
UPDATE `script_texts` SET `content_loc2` = 'Comment ça ? Un pauvre petit gnome ? Je ferai mieux la prochaine fois, Ô tout puissant !' WHERE `entry` = -1552027;
UPDATE `script_texts` SET `content_loc2` = 'Contemplez cette nouvelle créature d\'une puissance incommensurable !' WHERE `entry` = -1552026;
UPDATE `script_texts` SET `content_loc2` = 'Oui ! Oui ! Encore une autre ! Votre esprit est à moi !' WHERE `entry` = -1552025;
UPDATE `script_texts` SET `content_loc2` = 'Les Naarus gardaient certaines des créatures les plus dangeureuses de l\'univers dans ces cellules. Je vais vous en présenter une nouvelle.' WHERE `entry` = -1552024;
UPDATE `script_texts` SET `content_loc2` = 'Je savais que le prince serait en colère, mais je... je n\'étais plus moi même. Il fallait que je les relâche. Le tout-puissant me parle voyez-vous. Attendez... des étrangers... ce n\'est pas Kael Thas qui vous envoie ? Bien, il me suffira de dire au prince que c\'est vous qui avez libéré les prisonniers !' WHERE `entry` = -1552023;
UPDATE `script_texts` SET `content_loc2` = 'Ce soir on vous met... ce soir on vous met le feu !' WHERE `entry` = -1552022;
UPDATE `script_texts` SET `content_loc2` = 'Vous aurez des nouvelles de mon avocat....' WHERE `entry` = -1552021;
UPDATE `script_texts` SET `content_loc2` = 'Du soin... du soin... pour l\'amour de tout ce que ce monde a de sacré... c\'est à dire moi ! Soignez moi ! Je meurs...' WHERE `entry` = -1552020;
UPDATE `script_texts` SET `content_loc2` = 'C\'est impossible ! Elevez-vous serviteurs ! Servez une nouvelle fois votre Maître !' WHERE `entry` = -1469010;
UPDATE `script_texts` SET `content_loc2` = 'Brûlez misérables ! Brûlez !' WHERE `entry` = -1469009;
UPDATE `script_texts` SET `content_loc2` = 'Ah, les fameux héros. Vous êtez tenases, n\'est-ce pas. Votre allié a tenter de m\'affronter et en a payer le prix. Il est maintenant mon serviteur, et il va vous tuer. Debout mon petit dragon rouge. Détruit les !' WHERE `entry` = -1469006;
UPDATE `script_texts` SET `content_loc2` = 'Que les jeux commencent !' WHERE `entry` = -1469005;
UPDATE `script_texts` SET `content_loc2` = 'entre dans une frénésie meutrière !' WHERE `entry` = -1469002;
UPDATE `script_texts` SET `content_loc2` = 'Bien tenté mortel ! Mais il n\'est pas si facile de m\'éloigner de ma tanière !' WHERE `entry` = -1469001;
UPDATE `script_texts` SET `content_loc2` = 'Vous nous quittez déjà ?' WHERE `entry` = -1269010;
UPDATE `script_texts` SET `content_loc2` = 'Je vous avais dit que c\'était une quête idiote !' WHERE `entry` = -1269009;
UPDATE `script_texts` SET `content_loc2` = 'Tu n\'es plus le bienvenu ici, gardien du temps. Disparait !' WHERE `entry` = -1269008;
UPDATE `script_texts` SET `content_loc2` = 'Si vous n\'abandonnez pas cette quête stupide, vous mourrez !' WHERE `entry` = -1269007;
UPDATE `script_texts` SET `content_loc2` = 'Pourquoi aidez-vous le Magus ? Pensez aux nombres de vies épargniées si la porte n\'avait jamais été ouverte, si le guerre résultante pouvait être effacée...' WHERE `entry` = -1269006;
UPDATE `script_texts` SET `content_loc2` = 'Pourquoi insistez-vous ? Surement vous pouvez voir la futilité de tout cela. Il n\'est pas trop tard ! Vous pouvez encore sauver vos propres vies...' WHERE `entry` = -1269000;
