SET NAMES utf8;

UPDATE `db_script_string` SET `content_loc2` = 'Je peux faire le reste du chemin tout seul.$N MERCI !' WHERE `entry` = 2000000018;
UPDATE `db_script_string` SET `content_loc2` = 'Soyez patient $N. Le flambeau est bientôt au complet.' WHERE `entry` = 2000000019;
UPDATE `db_script_string` SET `content_loc2` = 'Cela à du sens !' WHERE `entry` = 2000000030;
UPDATE `db_script_string` SET `content_loc2` = 'Votre corps est à moi ! Nos destins sont pour toujours entrelacés!' WHERE `entry` = 2000000031;
UPDATE `db_script_string` SET `content_loc2` = 'Tenez vous bien $N, pour le démon qui se trouve dans l\'orbe c\'est une bête gangrenée.' WHERE `entry` = 2000000032;
UPDATE `db_script_string` SET `content_loc2` = 'Que tous salue le Seigneur Illidan !' WHERE `entry` = 2000000037;
UPDATE `db_script_string` SET `content_loc2` = 'Seigneur Illidan, voici le Gueule-de-Dragon dont nous vous avons parlé. Il nous guidera vers la victoire !' WHERE `entry` = 2000000038;
UPDATE `db_script_string` SET `content_loc2` = 'Mais...Mon seigneur, je ne comprends pas. $N...Ce sont les orcs qui ont...' WHERE `entry` = 2000000039;
UPDATE `db_script_string` SET `content_loc2` = 'Jusqu\'à notre prochaine rencontre !' WHERE `entry` = 2000000042;
UPDATE `db_script_string` SET `content_loc2` = 'commence un sort d\'invocation..' WHERE `entry` = 2000000043;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est fait...' WHERE `entry` = 2000000044;
UPDATE `db_script_string` SET `content_loc2` = 'Nous ne tolérerons pas la présence des serviteurs des démons dans notre contrée !' WHERE `entry` = 2000000065;
UPDATE `db_script_string` SET `content_loc2` = 'Que la paix et la patience soient avec vous, $N. Rester toujours fort.' WHERE `entry` = 2000000066;
UPDATE `db_script_string` SET `content_loc2` = 'Que fait un intrus comme vous dans le royaume d\'Ysera ? Je vous dis de nous laisser ! Les gens de votre espèces ne sont pas les bienvenus ici !' WHERE `entry` = 2000000067;
UPDATE `db_script_string` SET `content_loc2` = 'Vous....vous n\'êtes pas l\'un d\'entre eux! Mettons nous à l\'abris avant qu\'ils ne nous trouvent ! Vite !' WHERE `entry` = 2000000068;
UPDATE `db_script_string` SET `content_loc2` = 'MOI MECHANT OGRE' WHERE `entry` = 2000005230;
UPDATE `db_script_string` SET `content_loc2` = 'JE SENS LA MORT TOUT AUTOUR' WHERE `entry` = 2000005231;
UPDATE `db_script_string` SET `content_loc2` = 'Plus vous attendez, moins j\'aurais de temps pour votre avenir.' WHERE `entry` = 2000005232;
UPDATE `db_script_string` SET `content_loc2` = 'Asseyez vous par ici et vous allez entendre une cho.....*hic*..une ch...*hic* une chooo...*hic* Mince !' WHERE `entry` = 2000005233;
UPDATE `db_script_string` SET `content_loc2` = 'PERSONNE NE ME DEPASSERA ' WHERE `entry` = 2000005235;
UPDATE `db_script_string` SET `content_loc2` = 'JE SENS LA MORT TOUT AUTOUR' WHERE `entry` = 2000005236;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne suis pas payé assez pour ces excréments de taureaux.' WHERE `entry` = 2000005229;
UPDATE `db_script_string` SET `content_loc2` = 'J\'aurai du prendre la pillule translucide.' WHERE `entry` = 2000005228;
UPDATE `db_script_string` SET `content_loc2` = 'Venez à moi vrais croyants, et voyons ce que l\'avenir attends de vous !' WHERE `entry` = 2000005227;
UPDATE `db_script_string` SET `content_loc2` = 'Le mur arrière a été complétement soufflé !' WHERE `entry` = 2000005226;
UPDATE `db_script_string` SET `content_loc2` = 'Et ils appellent ça une soudure !...' WHERE `entry` = 2000005225;
UPDATE `db_script_string` SET `content_loc2` = 'Cela doit être réglé !' WHERE `entry` = 2000005224;
UPDATE `db_script_string` SET `content_loc2` = 'N\'oubliez pas d\'acheter des rafraîchissements et des souvenirs !' WHERE `entry` = 2000005223;
UPDATE `db_script_string` SET `content_loc2` = 'Ces données seront bien utiles pour le Projet Blue Book. Hum, je voulais dire qu\'ils seront très bien pour mon nouveau look. Voyons si nous pouvons dénicher d\'autres données' WHERE `entry` = 2000005222;
UPDATE `db_script_string` SET `content_loc2` = 'La Foire de Sombrelune est le plus grand évènement de tout l\'Outreterre.' WHERE `entry` = 2000005221;
UPDATE `db_script_string` SET `content_loc2` = 'SERVITEUR PRIER MOI ' WHERE `entry` = 2000005220;
UPDATE `db_script_string` SET `content_loc2` = 'Ceci devrait apporter à Telaar l\'assitance dont elle a besoin !' WHERE `entry` = 2000005219;
UPDATE `db_script_string` SET `content_loc2` = 'Hey, que quelqu\'un m\'aide à attraper cette chose !' WHERE `entry` = 2000005218;
UPDATE `db_script_string` SET `content_loc2` = 'Le Porte-quoi ? Oh , Porte-Cendre ? Jamais entendu parler...Quoi ? Arretez de m\'ennuyer !' WHERE `entry` = 2000005215;
UPDATE `db_script_string` SET `content_loc2` = 'Hey ! Aimez vous la sauce ? La sauce est bonne, non ?' WHERE `entry` = 2000005214;
UPDATE `db_script_string` SET `content_loc2` = 'Peur non ! Toutes les fortunes se profilent pour ceux qui connaissent le chemin.' WHERE `entry` = 2000005213;
UPDATE `db_script_string` SET `content_loc2` = 'Tickets ! Echangez vos tickets de la Foire de Sombrelune ici ! De merveilleux et éxotiques vous attendent !' WHERE `entry` = 2000005212;
UPDATE `db_script_string` SET `content_loc2` = 'Hey, que quelqu\'un m\'aide à attraper cette chose !' WHERE `entry` = 2000005211;
UPDATE `db_script_string` SET `content_loc2` = 'Je n\'arrêterai jamais. Jamais...' WHERE `entry` = 2000005210;
UPDATE `db_script_string` SET `content_loc2` = 'Hmm, ne vous opposez pas si je fais!' WHERE `entry` = 2000005204;
UPDATE `db_script_string` SET `content_loc2` = 'Ahhh, ma préçieuse Ameenah ! Que c\'est merveilleux de vous revoir.' WHERE `entry` = 2000005202;
UPDATE `db_script_string` SET `content_loc2` = 'Chargez !' WHERE `entry` = 2000005201;
UPDATE `db_script_string` SET `content_loc2` = 'Chargez !' WHERE `entry` = 2000005200;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005196;
UPDATE `db_script_string` SET `content_loc2` = 'Vous avez le cafard ? Venez vous amuser au Solitaire bleu !' WHERE `entry` = 2000005194;
UPDATE `db_script_string` SET `content_loc2` = 'Boissons gratuites au Solitaire bleu !' WHERE `entry` = 2000005193;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l\'atmosphère !' WHERE `entry` = 2000005192;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez-moi comment boire à l\'oeil au Solitaire bleu !' WHERE `entry` = 2000005191;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005189;
UPDATE `db_script_string` SET `content_loc2` = 'Vous avez le cafard ? Venez vous amuser au Solitaire bleu !' WHERE `entry` = 2000005188;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l\'atmosphère !' WHERE `entry` = 2000005187;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005186;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez-moi comment boire à l\'oeil au Solitaire bleu !' WHERE `entry` = 2000005197;
UPDATE `db_script_string` SET `content_loc2` = 'Venez pour la bière, restez pour l\'atmosphère !' WHERE `entry` = 2000005198;
UPDATE `db_script_string` SET `content_loc2` = 'La meilleure adresse de Hurlevent !' WHERE `entry` = 2000005199;
UPDATE `db_script_string` SET `content_loc2` = 'Salutation mes amis, et bienvenue dans le plus grand spectacle d\'Azeroth !$B$B S\'il vous plaît, restez ici et prenez tout ce que nous avons à offrir. Grimpez sur les manèges et voyez nos attractions touristiques ! Etonnez vous avec les merveilles de la Foire de Sombrelune qui ont été découvertes dans ce vaste et merveilleux monde ! Nous n\'avons pas lésiné sur les frais pour vous apporter l\'excitation à laquelle les enfants de tous les âges prendront plaisir!' WHERE `entry` = 2000005217;
UPDATE `db_script_string` SET `content_loc2` = 'Tous le monde s\'amuse pour le moment ? C\'est merveilleux ! Bienvenue à la Foire de Sombrelune, le plus grand spectacle de l\'Outreterre ! Assurez-vous d\'avoir parler avec Yebb et ses amis ici avant d\'entrer dans l\'étrange Zoo de Sombrelune de Becquabrach ' WHERE `entry` = 2000005216;
UPDATE `db_script_string` SET `content_loc2` = 'Flopp allait devenir un grand mage. Mais il a été transformé en lapin quand un de ses sorts a mal fonctionné.' WHERE `entry` = 2000005184;
UPDATE `db_script_string` SET `content_loc2` = 'Maman ? Je peux prendre Flopp comme animal de compagnie ?' WHERE `entry` = 2000005183;
UPDATE `db_script_string` SET `content_loc2` = 'Merci, Charys. Viens Paige, ma chérie.' WHERE `entry` = 2000005182;
UPDATE `db_script_string` SET `content_loc2` = 'Bien sur Paige. Soit gentille.' WHERE `entry` = 2000005181;
UPDATE `db_script_string` SET `content_loc2` = 'Bonjour, Charys. J\'ai une liste, pouvez vous m\'avoir tout ça , spécialement le dernier ingrédient.' WHERE `entry` = 2000005180;
UPDATE `db_script_string` SET `content_loc2` = 'Whaou, tout ça pour un philtre d\'amour. J\'espère qu\'il en vaut le coup.' WHERE `entry` = 2000005179;
UPDATE `db_script_string` SET `content_loc2` = 'Mais si nous le stabilisons avec un fil d\'ancrage au point crucial avec l\'énergie approprié alors il devrait fonctionner.' WHERE `entry` = 2000005178;
UPDATE `db_script_string` SET `content_loc2` = 'Si nous utilisons la séquence appropriée, nous devrions être au point. Nous devrions juste étudier sérieusement avant de commencer.' WHERE `entry` = 2000005177;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005053;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005054;
UPDATE `db_script_string` SET `content_loc2` = 'Bip !' WHERE `entry` = 2000005055;
UPDATE `db_script_string` SET `content_loc2` = 'Mais si nous le stabilisons avec un fil d\'ancrage au point crucial avec l\'énergie approprié alors il devrait fonctionner.' WHERE `entry` = 2000005175;
UPDATE `db_script_string` SET `content_loc2` = 'Whaou, tout ça pour un philtre d\'amour. J\'espère qu\'il en vaut le coup.' WHERE `entry` = 2000005174;
UPDATE `db_script_string` SET `content_loc2` = 'Si nous utilisons la séquence appropriée, nous devrions être au point. Nous devrions juste étudier sérieusement avant de commencer.' WHERE `entry` = 2000005172;
UPDATE `db_script_string` SET `content_loc2` = 'Whaou, tout ça pour un philtre d\'amour. J\'espère qu\'il en vaut le coup.' WHERE `entry` = 2000005171;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est vrai que les paladins s\'entrainent ici ?' WHERE `entry` = 2000005167;
UPDATE `db_script_string` SET `content_loc2` = 'N\'allez pas près du lac ! Il est hanté !' WHERE `entry` = 2000005147;
UPDATE `db_script_string` SET `content_loc2` = 'Ceci doit être réglé !' WHERE `entry` = 2000005144;
UPDATE `db_script_string` SET `content_loc2` = 'Je pense que je vois quelque chose.' WHERE `entry` = 2000005120;
UPDATE `db_script_string` SET `content_loc2` = 'Ils me suivent, $R ! Rapidement, dites-moi pourquoi vous êtes ici avant que nous soyons découvert ! S\'ils nous attrapent, cela signifie ma mort et la vôtre!' WHERE `entry` = 2000000069;
UPDATE `db_script_string` SET `content_loc2` = 'Cela aurait pris des années pour trouver le Livre du Corbeau sans vous, jeune crécerelle. Retournez vers votre terre Nagrand avec notre gratitude.' WHERE `entry` = 2000000070;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est ça ! C\'est vraiment ça -- Le Livre du Corbeau !' WHERE `entry` = 2000000071;
UPDATE `db_script_string` SET `content_loc2` = 'Pauvre Dorius. Si jamais je met la main sur ces Sombrefer, bien aidez moi..' WHERE `entry` = 2000005000;
UPDATE `db_script_string` SET `content_loc2` = 'Opus veut plus d\'Or de Cuergo...avec des vers.' WHERE `entry` = 2000005001;
UPDATE `db_script_string` SET `content_loc2` = 'Bijou perdu! SQUAWK! *Tousse*' WHERE `entry` = 2000005002;
UPDATE `db_script_string` SET `content_loc2` = 'Kibler fait l\'objet d\'une enquête du G.E.T.A.' WHERE `entry` = 2000005003;
UPDATE `db_script_string` SET `content_loc2` = 'Bijou sais ou les trésors sont cachés' WHERE `entry` = 2000005004;
UPDATE `db_script_string` SET `content_loc2` = 'Les dragons controllent les orcs ? SQUAWK !' WHERE `entry` = 2000005005;
UPDATE `db_script_string` SET `content_loc2` = 'Ils vont tous au Pic mais ne reviennent jamais...tout comme Bijou.' WHERE `entry` = 2000005006;
UPDATE `db_script_string` SET `content_loc2` = 'Demandez à Kibler a propos du trésor! SQUAWK!' WHERE `entry` = 2000005007;
UPDATE `db_script_string` SET `content_loc2` = 'SQUAWK !! *tousse* *tousse* Je dois arrêté de fumer !' WHERE `entry` = 2000005008;
UPDATE `db_script_string` SET `content_loc2` = 'Bien jouer, soldats ! A l\'aise !' WHERE `entry` = 2000005009;
UPDATE `db_script_string` SET `content_loc2` = 'Zug zug ! Content de pouvoir aider !' WHERE `entry` = 2000005010;
UPDATE `db_script_string` SET `content_loc2` = 'Oui maman tout de suite !' WHERE `entry` = 2000005011;
UPDATE `db_script_string` SET `content_loc2` = 'Ah, ça doît être lui maintenant...non ?' WHERE `entry` = 2000005018;
UPDATE `db_script_string` SET `content_loc2` = 'Vous devriez rester en arrière. La pêche est un travail d\'homme.' WHERE `entry` = 2000005019;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est bon de vous voir défendre Theramore avec fiertée, l\'ami.' WHERE `entry` = 2000005020;
UPDATE `db_script_string` SET `content_loc2` = 'Prix ! Venez récuperer vos prix ici ! Venez par ici et faites le tour de la Foire de Sombrelune pour des prix de grandes valeurs !' WHERE `entry` = 2000005025;
UPDATE `db_script_string` SET `content_loc2` = 'Le Roi Liche constitue ces forces. Il est impératif que notre calendrier soutient ses plans.' WHERE `entry` = 2000005027;
UPDATE `db_script_string` SET `content_loc2` = '...Et la le Tauren dit, "13 Pouces!"' WHERE `entry` = 2000005032;
UPDATE `db_script_string` SET `content_loc2` = 'Je pense que je vois quelque chose.' WHERE `entry` = 2000005118;
UPDATE `db_script_string` SET `content_loc2` = 'J\'espère que c\'est un poisson !' WHERE `entry` = 2000005121;
UPDATE `db_script_string` SET `content_loc2` = 'Et si l\'on se concentre sur trois points du modèle de Tyrean ? Cela devrait résoudre ce problème.' WHERE `entry` = 2000005176;
UPDATE `db_script_string` SET `content_loc2` = 'Et si l\'on se concentre sur trois points du modèle de Tyrean ? Cela devrait résoudre ce problème.' WHERE `entry` = 2000005170;
UPDATE `db_script_string` SET `content_loc2` = 'Le Portail changera légèrement. À ce moment, si vous jeter un sort il pourra vous solidifier sur place.' WHERE `entry` = 2000005173;
UPDATE `db_script_string` SET `content_loc2` = 'Si l\'on inverse le flux d\'essence, nous pouvons peut-être modifier la polarité.' WHERE `entry` = 2000005169;
UPDATE `db_script_string` SET `content_loc2` = 'Pourquoi devons-nous apprendre ça de toute façon ?' WHERE `entry` = 2000005168;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n\'est-ce pas l\'adepte Syleria ce qui a causé les problèmes initiaux avec sa formule magique?' WHERE `entry` = 2000005166;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n\'est-ce pas l\'adepte Syleria ce qui a causé les problèmes initiaux avec sa formule magique?' WHERE `entry` = 2000005162;
UPDATE `db_script_string` SET `content_loc2` = 'Mais n\'est-ce pas l\'adepte Syleria ce qui a causé les problèmes initiaux avec sa formule magique?' WHERE `entry` = 2000005155;
UPDATE `db_script_string` SET `content_loc2` = 'Mais cela ne voudrait pas dire qu\'il faut croiser les flux ? Ca ne peut pas faire de mal ? ' WHERE `entry` = 2000005165;
UPDATE `db_script_string` SET `content_loc2` = 'Mais cela ne voudrait pas dire qu\'il faut croiser les flux ? Ca ne peut pas faire de mal ? ' WHERE `entry` = 2000005160;
UPDATE `db_script_string` SET `content_loc2` = 'Maginor dit que la torsion alternante de flux d\'énergie positive crée en fait un flux beaucoup plus stable.' WHERE `entry` = 2000005164;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne le crois pas, je n\'ai pas besoin d\'être à nouveau emporté par le souffle.' WHERE `entry` = 2000005163;
UPDATE `db_script_string` SET `content_loc2` = 'Pourquoi ne pouvons-nous pas simplement déplacer le tableau pour compenser la variation dans le flux?' WHERE `entry` = 2000005161;
UPDATE `db_script_string` SET `content_loc2` = 'Cela fera se déséquilibrer le point de concentration magique, et causera une vibration inverse dans l\'éther.' WHERE `entry` = 2000005159;
UPDATE `db_script_string` SET `content_loc2` = 'Lorsque les énergies positivement alignés entre en collision avec la charge négative des énergies, ils ne peuvent s\'annuler l\'un de l\'autre.' WHERE `entry` = 2000005158;
UPDATE `db_script_string` SET `content_loc2` = 'Mais et si le changement de fréquence en résultant devait renvoyer les énérgies magiques dans le flux ? ' WHERE `entry` = 2000005157;
UPDATE `db_script_string` SET `content_loc2` = 'Je suppose que ca pourrait fonctionner, si nous avons vingt personnes pour lancer le sort avec nous.' WHERE `entry` = 2000005156;
UPDATE `db_script_string` SET `content_loc2` = 'Au moins nous ne serions pas dans les alentours pour devoir tout nettoyer.' WHERE `entry` = 2000005154;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous ne suivons pas la stricte procédure d\'initialisation.' WHERE `entry` = 2000005153;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous ne suivons pas la stricte procédure d\'initialisation.' WHERE `entry` = 2000005152;
UPDATE `db_script_string` SET `content_loc2` = 'Seulement si nous ne suivons pas la stricte procédure d\'initialisation.' WHERE `entry` = 2000005150;
UPDATE `db_script_string` SET `content_loc2` = 'Au moins nous ne serons pas dans les alentours pour devoir tout nettoyer.' WHERE `entry` = 2000005149;
UPDATE `db_script_string` SET `content_loc2` = 'La résultante des énergies risque de s\'effondrer ,cela pourrait causer un flux d\'énergie qui vous donnera une migraine pendant des semaines.' WHERE `entry` = 2000005151;
UPDATE `db_script_string` SET `content_loc2` = 'L\'insertion de douze points d\'énergies pourrait permettre aux énergies magiques de se former plus solidement, ajoutant la stabilité nécessaire.' WHERE `entry` = 2000005148;
UPDATE `db_script_string` SET `content_loc2` = 'Canard !' WHERE `entry` = 2000005146;
UPDATE `db_script_string` SET `content_loc2` = 'Comment est ce que quelqu\'un peut vivre comme ça ?' WHERE `entry` = 2000005145;
UPDATE `db_script_string` SET `content_loc2` = 'Ce ne sera jamais ..' WHERE `entry` = 2000005143;
UPDATE `db_script_string` SET `content_loc2` = 'Maintenant, jetez un dernier coup d\'oeil avant que nous nous mettons en route vers la Place de la Cathédrale et la grande Cathédrale de la Lumière. ' WHERE `entry` = 2000005142;
UPDATE `db_script_string` SET `content_loc2` = 'À couper le souffle. Les enfants, quand nous retournerons à l\'école, vous me ferez chacun un rapport oral sur une de ces personnes légendaires.' WHERE `entry` = 2000005141;
UPDATE `db_script_string` SET `content_loc2` = 'Ce n\'est pas merveilleux les enfants ? Tous ce qui entre dans la ville doivent marcher sous le regard attentif des plus grands héros de nos terres.' WHERE `entry` = 2000005140;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, bien ... nous nous dirigeons maintenant vers les monument dédiés aux héros des deux Grandes guerres, la Vallée de Héros. Suivez-moi.' WHERE `entry` = 2000005139;
UPDATE `db_script_string` SET `content_loc2` = 'Quand la Horde a été vaincues, les hommes sont revenus ici et ont commencé à reconstruire la majestueuse citée comme un témoignange de notre propre survie.' WHERE `entry` = 2000005138;
UPDATE `db_script_string` SET `content_loc2` = 'Ici, nous avons le Donjon de Hurlevent. Construit sur les ruines du château de Hurlevent, qui a été détruit par la Horde lors de la première Grande Guerre.' WHERE `entry` = 2000005137;
UPDATE `db_script_string` SET `content_loc2` = 'Les enfants si vous voulez bien me suivre, nous allons maintenant aller voir le donjon où le roi Anduin Wrynn lui-même est assis sur son trône.' WHERE `entry` = 2000005136;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, c\'est vrai. Les paladins et aussi bien les prêtres entrainent leurs compétences ici et sont à la recherche de grandes vérités derrière les murs de la cathédrale.' WHERE `entry` = 2000005135;
UPDATE `db_script_string` SET `content_loc2` = 'Ici, nous avons la Cathédrale de la Lumière, le coeur de l\'illumination spirituelle ici dans Hurlevent.' WHERE `entry` = 2000005134;
UPDATE `db_script_string` SET `content_loc2` = 'Vous passez un agréable moment ?' WHERE `entry` = 2000005133;
UPDATE `db_script_string` SET `content_loc2` = 'Vous avez l\'air vivant, chiens ! Nous avons une opération a mené ici !' WHERE `entry` = 2000005132;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est du propre.' WHERE `entry` = 2000005129;
UPDATE `db_script_string` SET `content_loc2` = 'Mon père dit que c\'est juste une histoire.' WHERE `entry` = 2000005126;
UPDATE `db_script_string` SET `content_loc2` = 'Vous pouvez imaginer ?' WHERE `entry` = 2000005123;
UPDATE `db_script_string` SET `content_loc2` = 'Les vers vont sur l\'hameçon, l\'hameçon va dans l\'eau, les poissons sont dans l\'eau, nos poissons.' WHERE `entry` = 2000005122;
UPDATE `db_script_string` SET `content_loc2` = 'Heyy..c\'est pas du poisson !' WHERE `entry` = 2000005119;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai reçu des tripes de ver sur mes chaussures.' WHERE `entry` = 2000005117;
UPDATE `db_script_string` SET `content_loc2` = 'Heyy..c\'est pas du poisson !' WHERE `entry` = 2000005116;
UPDATE `db_script_string` SET `content_loc2` = 'Et c\'est comme ça que Lothar a tué trente six orcs à mains. nues' WHERE `entry` = 2000005115;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne pense pas qu\'il y a du poisson dans ces canaux.' WHERE `entry` = 2000005114;
UPDATE `db_script_string` SET `content_loc2` = 'Vous savez pourquoi les yeux des Orcs scintillent en rouge ? C\'est parce qu\'ils boivent du sang !' WHERE `entry` = 2000005113;
UPDATE `db_script_string` SET `content_loc2` = 'Des sabots fendus, des boucliers brûlés, des badges éparpillés...Que veut dire tout ceci ?' WHERE `entry` = 2000005012;
UPDATE `db_script_string` SET `content_loc2` = 'Tout est ici...la façon dont les adeptes du corbeau ont capturés et soumis les esprits rivaux, qui ont été à jamais piégés dans les statues de pierre ! La tablette mentionne même le nom du Dieu Corbeau - Anzu. Je pensais qu\'il était perdu pour l\'histoire !' WHERE `entry` = 2000000072;
UPDATE `db_script_string` SET `content_loc2` = 'Il y a quelque chose d\'autre ici. Après la description d\'une bataille sanglante et de la chute du Dieu Corbeau, il y a une prophétie. Anzu va hanter les rêves de ses ennemis, et les tourmenter pour revenir dans ce monde...' WHERE `entry` = 2000000073;
UPDATE `db_script_string` SET `content_loc2` = 'La tablette nous apporte la confirmation dont nous avons besoin, tout comme je le pensais. Maintenant, nous devons utiliser ces informations pour tirer et défaire Anzu avant qu\'il ne fasse plus de dommages au Rêve d\'Emeraude!' WHERE `entry` = 2000000074;
UPDATE `db_script_string` SET `content_loc2` = 'Depuis que les Crécerelles ont eu un tel succès dans le fait de retrouver les pierres de corbeau, la Gardienne Elaira a entraîné un autre pour retransmettre ma voix à  grande distance. Il peut nous aider à communiquer avec les esprits d\'oiseaux qui ont révélé par la tablette sur laquelle nous enquêtons !' WHERE `entry` = 2000000075;
UPDATE `db_script_string` SET `content_loc2` = 'Oyez, habitants de Tanaris! Que soit connu $n comme un membre exalté de l\'Ordre du Mithril. Un forgeron plein d\'honneur, de dévouement, et avec une infinie patience. Trois bans pour $n !' WHERE `entry` = 2000000076;
UPDATE `db_script_string` SET `content_loc2` = 'Je pense que Drazzit va avoir besoin de chance pour trouver quelqu\'un pour tuer ce rapace. Je veux dire, il a déjà augmenté deux fois le prix de la récompense ... ' WHERE `entry` = 2000005013;
UPDATE `db_script_string` SET `content_loc2` = 'Mais c\'est le seul batîment qui peut convenir à Brogg ! Les gobelins font des batîments trop petits !' WHERE `entry` = 2000005014;
UPDATE `db_script_string` SET `content_loc2` = 'Je croyais que nous en avions déjà discuté, Brogg. Vous ne pouvez pas rester dans ce bâtiment. Bien sûr, il peut vous abritez, mais il n\'y a de place pour personne d\'autres!' WHERE `entry` = 2000005015;
UPDATE `db_script_string` SET `content_loc2` = 'Oui, nous avons dit, que vous pouvez rester ici, mais ce bâtiment est notre quartier général ! Tous nos manuels et nos plans sont stockés ici!' WHERE `entry` = 2000005016;
UPDATE `db_script_string` SET `content_loc2` = 'Je suis enclin à dire que les ogres sont trop gros ! Je peux le voir, je ne peux pas vous convaincre d\'y aller maintenant, mais pensez bien que ce n\'est que permanent!' WHERE `entry` = 2000005017;
UPDATE `db_script_string` SET `content_loc2` = 'Lorsque vous ne serez plus en service, allons faire un tour à l\'auberge, pour nous rememorer le bon vieux temps.' WHERE `entry` = 2000005021;
UPDATE `db_script_string` SET `content_loc2` = 'N\'aimeriez-vous pas que les beaux jours reviennent? J\'ai quelques amis qui connaissent le moyen d\'y parvenir.' WHERE `entry` = 2000005022;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai acquéris moi même tout les objets que j\'ai à vendre. Je peux vous garantir personnellement leurd authenticités .' WHERE `entry` = 2000005023;
UPDATE `db_script_string` SET `content_loc2` = 'Il s\'échappe !' WHERE `entry` = 2000005024;
UPDATE `db_script_string` SET `content_loc2` = 'Venez parler avec moi, et une fois que ce sera fait tout ce qui a été nuageux deviedra clair comme du cristal.' WHERE `entry` = 2000005026;
UPDATE `db_script_string` SET `content_loc2` = 'Demain, nous allons commencer la formation de nos dragons prometteur, alors n\'oubliez pas vos jouets à mâcher.' WHERE `entry` = 2000005028;
UPDATE `db_script_string` SET `content_loc2` = 'Notre plus ancienne prise de dragons est toujours loin de la maturité, mais avec de la patience et du sérieux, nous sommes sûrs que les dragons seront bientôt prêts.' WHERE `entry` = 2000005029;
UPDATE `db_script_string` SET `content_loc2` = 'Si vous attendez pour venir me voir, il n\'y aura peut être plus rien !' WHERE `entry` = 2000005030;
UPDATE `db_script_string` SET `content_loc2` = 'Je viens du monde souterrain...là ou les femmes ont la peste et les hommes tombent en morceaux.' WHERE `entry` = 2000005031;
UPDATE `db_script_string` SET `content_loc2` = 'Il s\'échappe !' WHERE `entry` = 2000005035;
UPDATE `db_script_string` SET `content_loc2` = 'JE VOUS DETRUIERAI TOUS !' WHERE `entry` = 2000005043;
UPDATE `db_script_string` SET `content_loc2` = 'NOUS D\'ABORD PUIS PLUS ET PLUS ' WHERE `entry` = 2000005044;
UPDATE `db_script_string` SET `content_loc2` = 'Ne me demandez juste pas où je l\'ai eu..' WHERE `entry` = 2000005045;
UPDATE `db_script_string` SET `content_loc2` = 'Vous passez un agréable moment ?' WHERE `entry` = 2000005048;
UPDATE `db_script_string` SET `content_loc2` = 'Hé, vous là-bas. Vous voulez des bonbons?' WHERE `entry` = 2000005052;
UPDATE `db_script_string` SET `content_loc2` = 'Venez ! Venez tous! Bienvenue à la foire de Sombrelune! Vous rêvez d\'aventure? Vous cherchez des trésors exotiques et mystérieux ? N\'allez pas plus loin! Vous, mon ami, vous êtes ici au bon endroit! Plongez droit vers la foire et prenez part à tous que l\'on a à vous offrir! Nous serons à cet endroit toute la semaine, donc assurez-vous de prévenir vos amis et vos proches!' WHERE `entry` = 2000005033;
UPDATE `db_script_string` SET `content_loc2` = 'Bienvenue à tous et à toutes à la foire de Sombrelune, le plus grand événement de tous les mondes! Nous avons de tous ... des plats délicieux , des boissons fortes, des objets exotiques, un diseur de bonne aventure, des prix incroyable et de l\'excitation sans fin! N\'oubliez pas d\'aller voir Gelvas Grasseporte pendant que vous faîtes un tour dans la foire de Sombrelune pour échanger vos billets  ! Il vous faut au minimum cinq tickets et vous êtes sur de trouver le plus merveilleux des prix dans tout l\'Outreterre. Tout le monde est gagnant' WHERE `entry` = 2000005034;
UPDATE `db_script_string` SET `content_loc2` = 'S\'il vous plaît! Je dois me nourrir de quelque chose ... Un cristal de mana ... un éclat ... n\'importe quoi! La douleur est insupportable!' WHERE `entry` = 2000005036;
UPDATE `db_script_string` SET `content_loc2` = 'Je dois juste aller chasser cette bête Avarié maintenant qu\'il y a une prime sur sa tête.' WHERE `entry` = 2000005037;
UPDATE `db_script_string` SET `content_loc2` = 'Dîtes nous ! Qu\'est ce que votre chef nous cache ?' WHERE `entry` = 2000005038;
UPDATE `db_script_string` SET `content_loc2` = 'Le vent nous parle des mouvements de nos ennemis, Ashyen. Les Nagas vont attaquer de nouveau.' WHERE `entry` = 2000005039;
UPDATE `db_script_string` SET `content_loc2` = 'Très bien. Quand cette décision sera prise, je serai prêt. Espérons qu\'il ne sera pas trop tard.' WHERE `entry` = 2000005040;
UPDATE `db_script_string` SET `content_loc2` = 'Je vais faire de mon mieux pour prendre soin des enfants, grand-mère.' WHERE `entry` = 2000005041;
UPDATE `db_script_string` SET `content_loc2` = 'Nouveautée sur le tableau d\'affichage! Que les aventuriers et les héros, se réunissent autour du tableau d\'affichage!' WHERE `entry` = 2000005042;
UPDATE `db_script_string` SET `content_loc2` = 'Je vais à la recherche d\'une prime après la relève.' WHERE `entry` = 2000005046;
UPDATE `db_script_string` SET `content_loc2` = 'Vous voulez vous occuper de la prime après que la relève soit terminée ?' WHERE `entry` = 2000005047;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai un autre ouvrage sur le néant.' WHERE `entry` = 2000005049;
UPDATE `db_script_string` SET `content_loc2` = 'Bien Gazleu !' WHERE `entry` = 2000005051;
UPDATE `db_script_string` SET `content_loc2` = 'Bien. Nous avons  bousillé nos queues pour tirer tout ce truc jusqu\'ici et vous voulez que nous travaillions encore plus ?' WHERE `entry` = 2000005056;
UPDATE `db_script_string` SET `content_loc2` = 'Où est l\'eau Emma ? Va chercher de l\'eau Emma ! Si je n\'étais pas la il ne saurait même pas à quoi ressemble l\'eau.' WHERE `entry` = 2000005104;
UPDATE `db_script_string` SET `content_loc2` = 'Bien sûr je parle toute seule. Mais c\'est le seul moyen d\'avoir une conversation décente dans cette citée.' WHERE `entry` = 2000005105;
UPDATE `db_script_string` SET `content_loc2` = 'Comme si je n\'avais pas mieux à faire à mon âge que transporter des seaux d\'eau.' WHERE `entry` = 2000005106;
UPDATE `db_script_string` SET `content_loc2` = 'On dirait que je fais ce chemin une centaine de fois par jour, je parcours tout les chemins pour obtenir plus d\'eau. Aucun respect pour leurs aînés.' WHERE `entry` = 2000005107;
UPDATE `db_script_string` SET `content_loc2` = 'Du deja Vu. Pendant un instant, j\'ai pensé que j\'étais de retour ... avant la peste ...' WHERE `entry` = 2000005108;
UPDATE `db_script_string` SET `content_loc2` = 'Ils disent qu\'il peut se transformer en un corbeau parfois.' WHERE `entry` = 2000005109;
UPDATE `db_script_string` SET `content_loc2` = 'Ils disent qu\'il peut se transformer en un corbeau parfois.' WHERE `entry` = 2000005110;
UPDATE `db_script_string` SET `content_loc2` = 'Et ensuite le lapin a juste sorti sa tête... Je te jure.' WHERE `entry` = 2000005111;
UPDATE `db_script_string` SET `content_loc2` = 'Je ne peux pas prendre ces taxes! Moi F.I.C.A ? F.I.C.A toi même !' WHERE `entry` = 2000005234;
UPDATE `db_script_string` SET `content_loc2` = 'Les taches de vin, les taches d\'herbe, même les taches animales ne sont rien comparés au Fusil Maculateur Electrostatique !' WHERE `entry` = 2000005208;
UPDATE `db_script_string` SET `content_loc2` = 'N\'attendez pas! Commandez maintenant et recevezt mon Fer de Gaufre Ultra-cinétique sans supplément de prix!' WHERE `entry` = 2000005209;
UPDATE `db_script_string` SET `content_loc2` = 'Déviré de la technologie de pointe offensive de l\'Opération du Soleil Brisé, il fait sauter les taches tenaces avec facilité!' WHERE `entry` = 2000005207;
UPDATE `db_script_string` SET `content_loc2` = 'Soyez le premier de votre bloc a posséder l\'incroyable Fusil Maculateur Electrostatique !' WHERE `entry` = 2000005206;
UPDATE `db_script_string` SET `content_loc2` = 'Il met du temps à venir, Grillegaufre. N\'avez-vous pas un produit de démonstration ou de quelque chose d\'autre?' WHERE `entry` = 2000005205;
UPDATE `db_script_string` SET `content_loc2` = 'La princesse s\'affaiblit, je peux le sentir !' WHERE `entry` = 2000005203;
UPDATE `db_script_string` SET `content_loc2` = 'Je le jure, des gens les ont réellement vus. Les Pandaren existent vraiment!' WHERE `entry` = 2000005112;
UPDATE `db_script_string` SET `content_loc2` = 'Jack et Jill sont froissé, mes fesses! J\'ai de l\'eau jusqu\'au cheveux.' WHERE `entry` = 2000005103;
UPDATE `db_script_string` SET `content_loc2` = 'Bien vous avez mis la main dessus voyons ce que vous avec la !' WHERE `entry` = 2000005050;