SET NAMES utf8;

UPDATE `db_script_string` SET `content_loc2` = 'Allez dans l\'Arène du Sang, $N. Le combat est sur le point de commencer !' WHERE `entry` = 2000000001;
UPDATE `db_script_string` SET `content_loc2` = 'La bataille est sur le point de commencer !' WHERE `entry` = 2000000002;
UPDATE `db_script_string` SET `content_loc2` = '$N contre le féroce Sabot-fourchu, Brisorteil !' WHERE `entry` = 2000000003;
UPDATE `db_script_string` SET `content_loc2` = 'Allons-y.' WHERE `entry` = 2000000004;
UPDATE `db_script_string` SET `content_loc2` = 'Ce n\'est pas ici ! humm...' WHERE `entry` = 2000000005;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est la tente d\'Hollee, mais où se trouve Hollee ?' WHERE `entry` = 2000000006;
UPDATE `db_script_string` SET `content_loc2` = 'Ce n\'est pas ici non plus. Etrange... Où se trouve-t\'il ?' WHERE `entry` = 2000000007;
UPDATE `db_script_string` SET `content_loc2` = 'Hmm. Ce n\'est pas ici. Peut-être qu\'Hollee l\'a...' WHERE `entry` = 2000000008;
UPDATE `db_script_string` SET `content_loc2` = 'Qu\'est ce qui se passe ?' WHERE `entry` = 2000000009;
UPDATE `db_script_string` SET `content_loc2` = 'Volcor a besoin d\'aide ?' WHERE `entry` = 2000000010;
UPDATE `db_script_string` SET `content_loc2` = 'Très bien, je dois trouver des personnes pour l\'aider.' WHERE `entry` = 2000000011;
UPDATE `db_script_string` SET `content_loc2` = 'Très bien, allons y.' WHERE `entry` = 2000000012;
UPDATE `db_script_string` SET `content_loc2` = 'Oh non ! Ils sont ici !' WHERE `entry` = 2000000013;
UPDATE `db_script_string` SET `content_loc2` = 'Oh, bonjour Griffe-sinistre.' WHERE `entry` = 2000000014;
UPDATE `db_script_string` SET `content_loc2` = 'Bien, $N. Maintenant je peux rentrer tout seul à Auberdine. Aller voir Terenthis, il vous attend. Merci encore de votre aide.' WHERE `entry` = 2000000015;
UPDATE `db_script_string` SET `content_loc2` = 'D\'accord, merci pour l\'aide l\'ami et bonne chance.' WHERE `entry` = 2000000016;
UPDATE `db_script_string` SET `content_loc2` = 'Ok, c\'est parti !' WHERE `entry` = 2000000017;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est intéressant...' WHERE `entry` = 2000000020;
UPDATE `db_script_string` SET `content_loc2` = 'Je dois consulter Noram et Horatio.' WHERE `entry` = 2000000021;
UPDATE `db_script_string` SET `content_loc2` = 'Regardez : Les séides de Terokk viennent ici !' WHERE `entry` = 2000000022;
UPDATE `db_script_string` SET `content_loc2` = 'Par ici ! D\'autres arrivent !' WHERE `entry` = 2000000023;
UPDATE `db_script_string` SET `content_loc2` = 'Et même plus !' WHERE `entry` = 2000000024;
UPDATE `db_script_string` SET `content_loc2` = 'Un avatar de Terokk ! Aux armes !' WHERE `entry` = 2000000025;
UPDATE `db_script_string` SET `content_loc2` = 'Oups !' WHERE `entry` = 2000000026;
UPDATE `db_script_string` SET `content_loc2` = '[PH] Text Temporaire' WHERE `entry` = 2000000027;
UPDATE `db_script_string` SET `content_loc2` = 'Bonne chance étranger, et bienvenue dans la ville de Shattrath' WHERE `entry` = 2000000028;
UPDATE `db_script_string` SET `content_loc2` = 'Suivez-moi, $N. Je vais bientôt commencer l\'invocation...' WHERE `entry` = 2000000029;
UPDATE `db_script_string` SET `content_loc2` = 'Restez en mouvement !' WHERE `entry` = 2000000033;
UPDATE `db_script_string` SET `content_loc2` = 'Venez, $N. Le seigneur Hurlorage attend.' WHERE `entry` = 2000000034;
UPDATE `db_script_string` SET `content_loc2` = 'Guerriers Gueule-de-Dragon, rassemblement ! Un de vous a atteint le rang de Seigneur Suprême ! Baissez la tête et à genoux ! Montrez votre respect et votre allégeance envers le Seigneur Suprême, $N !' WHERE `entry` = 2000000035;
UPDATE `db_script_string` SET `content_loc2` = 'Le seigneur Illidan sera la sous peu.' WHERE `entry` = 2000000036;
UPDATE `db_script_string` SET `content_loc2` = 'Ce sera fait, mon seigneur.' WHERE `entry` = 2000000040;
UPDATE `db_script_string` SET `content_loc2` = 'Vous pensez pouvoir vous moquer de Mor\'ghor, hein ? Avant que vous ne soyez envoyés vers le seigneur Illidan, vous allez connaître des souffrances que vous ne soupçonniez même pas. Je vais y prendre du plaisir comme s\'il s\'agissait de ma propre vengeance.' WHERE `entry` = 2000000041;
UPDATE `db_script_string` SET `content_loc2` = 'Il n\'y a rien de mieux qu\'un thé brûlant pour bien commencer une froide journée à Dun Morogh.' WHERE `entry` = 2000000045;
UPDATE `db_script_string` SET `content_loc2` = 'Oooooo chaud chaud chaud ! Si cela ne met pas un peu de printemps DANS votre démarche, je ne sais pas ce qui le fera !' WHERE `entry` = 2000000046;
UPDATE `db_script_string` SET `content_loc2` = 'Ribbit ! Non ! Cela ne peut pas... ribbit... être ! Vous m\'avez trompé avec... ribbit...  vos supercheries ! Ribbit !' WHERE `entry` = 2000000047;
UPDATE `db_script_string` SET `content_loc2` = 'Laissez-moi maintenant placer cette terre rare dans mon terreau...' WHERE `entry` = 2000000048;
UPDATE `db_script_string` SET `content_loc2` = 'Merci encore, $N. Cette terre rare sera très utile dans mes expériences.' WHERE `entry` = 2000000049;
UPDATE `db_script_string` SET `content_loc2` = 'Bonjour Griffe-Sinistre' WHERE `entry` = 2000000050;
UPDATE `db_script_string` SET `content_loc2` = 'Qu\'est ce qui se passe ?' WHERE `entry` = 2000000051;
UPDATE `db_script_string` SET `content_loc2` = 'Volcor est parti ?' WHERE `entry` = 2000000052;
UPDATE `db_script_string` SET `content_loc2` = 'Vous savez où il est ?' WHERE `entry` = 2000000053;
UPDATE `db_script_string` SET `content_loc2` = 'Bien, c\'est entendu. Je vais maintenant envoyer des secours. Nous devons le trouver et l\'aider.' WHERE `entry` = 2000000054;
UPDATE `db_script_string` SET `content_loc2` = 'Combien de fantassins dois-je renvoyer dans un sac à leur mère et à leur père avant que vous ne compreniez qu\'il ne sert à rien de foncer tête la première contre une patrouille de la Légion ?  Et ne faites pas comme si vous sachiez de quoi je parle !' WHERE `entry` = 2000000055;
UPDATE `db_script_string` SET `content_loc2` = 'Hey par ici, Belm ! Donne moi une chope de Tonneblonde, et une aussi pour mon ami $N.' WHERE `entry` = 2000000056;
UPDATE `db_script_string` SET `content_loc2` = 'Esprit de l\'eau, je chante vos louanges, et je vous prie de nous accorder une faveur. Vous avez entendu $N , et je suis convaincu que son coeur est noble. S’il vous plaît, allez-vous nous aider ?' WHERE `entry` = 2000000057;
UPDATE `db_script_string` SET `content_loc2` = 'Merci grand esprit ! Merci !' WHERE `entry` = 2000000058;
UPDATE `db_script_string` SET `content_loc2` = 'Vous êtes renvoyé, $N' WHERE `entry` = 2000000059;
UPDATE `db_script_string` SET `content_loc2` = 'Par les étoiles ! Un esprit a été invoqué !' WHERE `entry` = 2000000060;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est un mystère du passé ! Mais une clé de notre avenir !' WHERE `entry` = 2000000061;
UPDATE `db_script_string` SET `content_loc2` = 'C\'est la fin de la menace ! $N nous a tous sauvés !' WHERE `entry` = 2000000062;
UPDATE `db_script_string` SET `content_loc2` = 'Suivez-moi, bien $C. Je peux vous faire votre carapaçon plus vite que je n\'abattrais un solide Nain !' WHERE `entry` = 2000000063;
UPDATE `db_script_string` SET `content_loc2` = 'Eh bien, cela devrait convenir. Venez maintenant, retour à la boutique pour terminer notre affaire !' WHERE `entry` = 2000000064;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh... Le bébé pleurnicheur !' WHERE `entry` = 2000005057;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée!' WHERE `entry` = 2000005058;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si Betsy sait nager !' WHERE `entry` = 2000005059;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J\'ai Betsy !' WHERE `entry` = 2000005060;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005061;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005062;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh... Le bébé pleurnicheur !' WHERE `entry` = 2000005063;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005064;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si Betsy sait nager !' WHERE `entry` = 2000005065;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J\'ai Betsy !' WHERE `entry` = 2000005066;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée!' WHERE `entry` = 2000005067;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005068;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh... Le bébé pleurnicheur !' WHERE `entry` = 2000005069;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005070;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si Betsy sait nager !' WHERE `entry` = 2000005071;
UPDATE `db_script_string` SET `content_loc2` = 'Ha ! Ha ! J\'ai Betsy !' WHERE `entry` = 2000005072;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée!' WHERE `entry` = 2000005073;
UPDATE `db_script_string` SET `content_loc2` = 'J\'ai ta poupée ! Na Na Na Na Nère !' WHERE `entry` = 2000005074;
UPDATE `db_script_string` SET `content_loc2` = 'Bouh, bouh... Le bébé pleurnicheur !' WHERE `entry` = 2000005075;
UPDATE `db_script_string` SET `content_loc2` = 'Bébé veut sa poupée !' WHERE `entry` = 2000005076;
UPDATE `db_script_string` SET `content_loc2` = 'Je me demande si Betsy sait nager !' WHERE `entry` = 2000005077;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005078;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005079;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas de mal à Betsy, vilain méchant !' WHERE `entry` = 2000005080;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005081;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005082;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005083;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005084;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005085;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas de mal à Betsy, vilain méchant !' WHERE `entry` = 2000005086;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005087;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005088;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005089;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005090;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005091;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas de mal à Betsy, vilain méchant !' WHERE `entry` = 2000005092;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005093;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005094;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005095;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005096;
UPDATE `db_script_string` SET `content_loc2` = 'Donne-moi ma poupée !!' WHERE `entry` = 2000005097;
UPDATE `db_script_string` SET `content_loc2` = 'Ne fais pas de mal à Betsy, vilain méchant !' WHERE `entry` = 2000005098;
UPDATE `db_script_string` SET `content_loc2` = 'Pain frais, tout juste sorti du four !' WHERE `entry` = 2000005099;
UPDATE `db_script_string` SET `content_loc2` = 'Brioches, petits pains et miches. Tout frais sortis du four !' WHERE `entry` = 2000005100;
UPDATE `db_script_string` SET `content_loc2` = 'Pain frais, tout juste sorti du four !' WHERE `entry` = 2000005101;
UPDATE `db_script_string` SET `content_loc2` = 'Brioches, petits pains et miches. Tout frais sortis du four !' WHERE `entry` = 2000005102;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005124;
UPDATE `db_script_string` SET `content_loc2` = 'Wouah.' WHERE `entry` = 2000005125;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005127;
UPDATE `db_script_string` SET `content_loc2` = 'Wouah.' WHERE `entry` = 2000005128;
UPDATE `db_script_string` SET `content_loc2` = 'Wouah.' WHERE `entry` = 2000005130;
UPDATE `db_script_string` SET `content_loc2` = 'Vraiment ?' WHERE `entry` = 2000005131;
UPDATE `db_script_string` SET `content_loc2` = 'L\'étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005185;
UPDATE `db_script_string` SET `content_loc2` = 'L\'étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005190;
UPDATE `db_script_string` SET `content_loc2` = 'L\'étude de la magie vous fatigue les neurones ? Venez vous détendre au Solitaire bleu !' WHERE `entry` = 2000005195;
