SET NAMES utf8;

UPDATE `eventai_texts` SET `content_loc2` = 'Zaricotl semble beaucoup plus calme maintenant qu\'il a mangé les restes de $N.' WHERE `entry` = -405;
UPDATE `eventai_texts` SET `content_loc2` = 'Je ne peux pas vous autoriser à entrer dans le temple! Je dois vous détruire pour votre propre bien!' WHERE `entry` = -404;
UPDATE `eventai_texts` SET `content_loc2` = 'Faucon-dragon en approche en approche à l\'ouest! Abattez-moi ce chasseur!' WHERE `entry` = -403;
UPDATE `eventai_texts` SET `content_loc2` = 'Restez bien sur les démons. Aujourd\'hui, on s\'occupe pas de tuer les créature du Fléau.' WHERE `entry` = -402;
UPDATE `eventai_texts` SET `content_loc2` = 'Ordure du Soleil brisé! Feu à volonté!' WHERE `entry` = -401;
UPDATE `eventai_texts` SET `content_loc2` = 'C\'est tout ce que j\'avais à dire pour l\'instant. Restez sur le branle-bas, mes enfants.' WHERE `entry` = -400;
UPDATE `eventai_texts` SET `content_loc2` = 'Inutile de le préciser, beaucoup d\'entre vous ne rentreront pas chez eux. Mais si vous appliquez votre entraînement et gardez la tête froide, vous serez un grand atout pour nous.' WHERE `entry` = -399;
UPDATE `eventai_texts` SET `content_loc2` = 'Notre boulot est de dégager autant de cette chaire à canon que possible, tout en aidant les spécialistes que les grands manitoux nous envoient.' WHERE `entry` = -398;
UPDATE `eventai_texts` SET `content_loc2` = 'Là-haut, sur le plateau, lui et ses amis les démons essaient de rallumer le Puit de Soleil et d\'ouvrir une faille pour ramener leur grand sachem, Kil\'Jaeden, en ce bas monde.' WHERE `entry` = -397;
UPDATE `eventai_texts` SET `content_loc2` = 'L\'île de Quel\'Danas a été envahie par les troupes du prince Kael\'thas Haut-soleil. Nos renseignements le donnaient pour mort. Nos renseignement se trompaient.' WHERE `entry` = -396;
UPDATE `eventai_texts` SET `content_loc2` = 'Bonjour, jeunes recrues. Je suis le sergent instructeur Bahduum. Pour les quelques jours à venir, je serai chargé de vous orienter.' WHERE `entry` = -395;
UPDATE `eventai_texts` SET `content_loc2` = 'Pour vos affectations précises, j\'attends les ordres. En attendant, restez ici et soyez prêts à partir d\'un instant à l\'autre!' WHERE `entry` = -394;
UPDATE `eventai_texts` SET `content_loc2` = 'Les guerriers seront déployés pour tenir les points clés pendant que vous, les tireurs d\'élite, aurez pour mission de tenir les troupes volantes ennemies à distance.' WHERE `entry` = -393;
UPDATE `eventai_texts` SET `content_loc2` = 'Je peux vous assurer que, s\'il réussit, ce que ce monde subira sera bien pire que tout ce qu\'a jamais enduré l\'Outreterre. Alors faisons en sorte que ça n\'arrive pas.' WHERE `entry` = -392;
UPDATE `eventai_texts` SET `content_loc2` = 'Je sais, nous aussi nous pensions qu\'il était mort, mais ce n\'est pas le cas. Il essaie d\'utiliser le Puits de soleil pour invoquer le maître de la Légion ardente, Kil\'Jaeden, en ce monde.' WHERE `entry` = -391;
UPDATE `eventai_texts` SET `content_loc2` = 'La situation actuelle ressemble à peu près à ça : on tient ce qu\'on peut, pendant que des gens plus expérimentés et mieux équipés vont chercher Kael\'Thas.' WHERE `entry` = -390;
UPDATE `eventai_texts` SET `content_loc2` = 'Bienvenue au Puits de soleil. Malgré la température agréable et la belle vue, vous n\'êtes pas là pour les vacances, mesdames et messieurs!' WHERE `entry` = -389;
UPDATE `eventai_texts` SET `content_loc2` = 'Bonne Chance!' WHERE `entry` = -388;
UPDATE `eventai_texts` SET `content_loc2` = 'Mesdames, si vous n\'avez pas de question, vous pouvez aller demander des instructions supplémentaires et vos affectations à vos chefs d\'unités. C\'est tout pour aujourd\'hui.' WHERE `entry` = -387;
UPDATE `eventai_texts` SET `content_loc2` = 'Nous sommes ici comme troupes de soutient pour les « aventuriers », c\'est leur petit nom, que les galonnés ont recrutés. Nous allons les aider à tenir les points clés de l\'île et baisser un peu la pression pour qu\'ils puissent faire leur boulot.' WHERE `entry` = -386;
UPDATE `eventai_texts` SET `content_loc2` = 'Maintenant que ce point-là est éclairci, bienvenue sur l\'île de Quel\'Danas. Le Puits de soleil se trouve sur le plateau au sud, et le prince Kael\'thas se terre sur la terrasse des Magistères, à l\'est.' WHERE `entry` = -385;
UPDATE `eventai_texts` SET `content_loc2` = 'Mais d\'abord, écoutez-moi, les sin\'dorei. Ici, on est pas là pour rigoler... Ca va vous changer de ce à quoi vous avez été habitué chez les Clairvoyants. Faites votre part du boulot, ou remontez sur le bateau!' WHERE `entry` = -384;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai déjà combattu aux côtés des draeneï à Skettis, et dans la vallée d\'Ombrelune. Mais maintenant, nous sommes en Azeroth. Et la situation a l\'air très mauvaise.' WHERE `entry` = -383;
UPDATE `eventai_texts` SET `content_loc2` = 'Allons, calmez-vous. Nous avons beaucoup à faire et peu de temps pour le faire, mes amis.' WHERE `entry` = -382;
UPDATE `eventai_texts` SET `content_loc2` = 'ATTENTION!' WHERE `entry` = -381;
UPDATE `eventai_texts` SET `content_loc2` = 'Dégagez, cet endroit est à nous !' WHERE `entry` = -380;
UPDATE `eventai_texts` SET `content_loc2` = 'A moi! Vous ne prendrez pas cet endroit!' WHERE `entry` = -379;
UPDATE `eventai_texts` SET `content_loc2` = 'Position de berserker! Attaquez-les avec imprudence!' WHERE `entry` = -378;
UPDATE `eventai_texts` SET `content_loc2` = '[Orcish] Tago mog regas gi mog Tov\'nokaz Kagg' WHERE `entry` = -377;
UPDATE `eventai_texts` SET `content_loc2` = '[Orcish] Ogg kaz ko zugas kil mog Tov\'nokaz Kagg' WHERE `entry` = -376;
UPDATE `eventai_texts` SET `content_loc2` = 'à les yeux rougis qui brillent tandis qu\'il allume sa dynamite et se met à caqueter comme un fou!' WHERE `entry` = -375;
UPDATE `eventai_texts` SET `content_loc2` = '[Dwarvish] Dum mos' WHERE `entry` = -374;
UPDATE `eventai_texts` SET `content_loc2` = 'Mourez au nom de Ragnaros!' WHERE `entry` = -373;
UPDATE `eventai_texts` SET `content_loc2` = 'Le Loch appartient à la Tribu Brisepierre maintenant, $N! Mourez maintenant!' WHERE `entry` = -372;
UPDATE `eventai_texts` SET `content_loc2` = 'Mourez $R! Ces terrains appartiennent à la Tribu Brisepierre!' WHERE `entry` = -371;
UPDATE `eventai_texts` SET `content_loc2` = 'Un $C appelé $N? Vous ferez un petit déjeuner parfait!' WHERE `entry` = -370;
UPDATE `eventai_texts` SET `content_loc2` = 'Frappez-le!' WHERE `entry` = -369;
UPDATE `eventai_texts` SET `content_loc2` = 'Hein? Quoi Dat ?' WHERE `entry` = -367;
UPDATE `eventai_texts` SET `content_loc2` = 'ARRRRRRR!' WHERE `entry` = -366;
UPDATE `eventai_texts` SET `content_loc2` = 'Aidez-moi !' WHERE `entry` = -365;
UPDATE `eventai_texts` SET `content_loc2` = 'Wahehe! Je vous emporte avec moi!' WHERE `entry` = -364;
UPDATE `eventai_texts` SET `content_loc2` = 'Le Roi Magni Barbe-de-bronze est un imbécile et un charlatan!' WHERE `entry` = -362;
UPDATE `eventai_texts` SET `content_loc2` = 'Raaar!!! Moi fracasser $R!' WHERE `entry` = -361;
UPDATE `eventai_texts` SET `content_loc2` = 'Moi fracasser! Vous mourir!' WHERE `entry` = -360;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vous écraserai!' WHERE `entry` = -359;
UPDATE `eventai_texts` SET `content_loc2` = 'Il est temps de mourir,$C!' WHERE `entry` = -358;
UPDATE `eventai_texts` SET `content_loc2` = 'Sentez le pouvoir des Nains au fer Sombre!' WHERE `entry` = -357;
UPDATE `eventai_texts` SET `content_loc2` = 'Faible $C! Vous n\'avez pas le niveau pour la Tribu Brisepierre!' WHERE `entry` = -356;
UPDATE `eventai_texts` SET `content_loc2` = 'Le seul bon $R est un $R mort!' WHERE `entry` = -355;
UPDATE `eventai_texts` SET `content_loc2` = 'Yip! Moi tuer!' WHERE `entry` = -354;
UPDATE `eventai_texts` SET `content_loc2` = 'Moi pas courir comme un $C!' WHERE `entry` = -353;
UPDATE `eventai_texts` SET `content_loc2` = 'C\'était un Porto Pupellyverbos vieux de 200ans!' WHERE `entry` = -352;
UPDATE `eventai_texts` SET `content_loc2` = 'Comment osez-vous déranger le dîner du Maître!' WHERE `entry` = -350;
UPDATE `eventai_texts` SET `content_loc2` = 'examine les informations sur l\'affiche "Recherché".' WHERE `entry` = -340;
UPDATE `eventai_texts` SET `content_loc2` = 'chuchote doucement d\'un ton respectueux.' WHERE `entry` = -339;
UPDATE `eventai_texts` SET `content_loc2` = 'Ahh, un autre puissant voyageur. Le coin peut être dangereux... vous voudrez les sorts les plus puissant à votre disposition. Je possède les meilleurs réactifs, communs ou exotiques. Venez et achetez - vous ne le regretterez pas!' WHERE `entry` = -338;
UPDATE `eventai_texts` SET `content_loc2` = 'Ici les créatures sont puissantes. Vous aurez besoin de beaucoup de munitions si vous souhaitez survivre. Vous êtes chanceux - je possède une bonne quantité de flèches, balles et armes de tir. Le prix est raisonnable considérant les circonstances.' WHERE `entry` = -337;
UPDATE `eventai_texts` SET `content_loc2` = 'Cette guerre - et ne faites pas l’erreur de croire que ce n’est pas une guerre - ne va pas se gagner toute seule. Si nous ne faisons pas de notre mieux pour combattre, griffer, mordre et ruer pour chaque parcelle de cette terre brisée, tout est perdu.' WHERE `entry` = -336;
UPDATE `eventai_texts` SET `content_loc2` = 'Combien de soldats devront mourir avant que nous commencions à faire un peu attention à ce qui se passe ici ?' WHERE `entry` = -335;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous pensez que les démons respectent les règles ? Ces bêtes sont plus sauvages que les orcs et plus rusées que les morts-vivants. N’essayez pas d’affronter la Légion selon les principes classiques de la guerre.' WHERE `entry` = -334;
UPDATE `eventai_texts` SET `content_loc2` = 'Je ne comprends pas! Êtes-vous aveugle? Ne pouvez-vous pas voir les démons frapper à nos portes? Qui vais-je envoyé pour parlé à vos amis shamans? Choisis-les!' WHERE `entry` = -333;
UPDATE `eventai_texts` SET `content_loc2` = 'Bron! Hey Bron! Hey Bron! Frappe-moi!' WHERE `entry` = -332;
UPDATE `eventai_texts` SET `content_loc2` = 'Non... c\'est pour les peureux. Frappe-moi avec ton marteau!' WHERE `entry` = -331;
UPDATE `eventai_texts` SET `content_loc2` = 'FAIS-LE, ESPÈCE DE JOUFFLU!' WHERE `entry` = -330;
UPDATE `eventai_texts` SET `content_loc2` = '...C\'ÉTAIT GÉNIAL!' WHERE `entry` = -329;
UPDATE `eventai_texts` SET `content_loc2` = 'bat des cils, une expression perplexe passant sur son visage.' WHERE `entry` = -328;
UPDATE `eventai_texts` SET `content_loc2` = 'Quoi, avec mes poings?' WHERE `entry` = -327;
UPDATE `eventai_texts` SET `content_loc2` = 'Je... ne suis pas certain que ce soit une bonne idée, \'Moke. Tu pourrais te blesser...' WHERE `entry` = -326;
UPDATE `eventai_texts` SET `content_loc2` = 'Er... \'Moke ?' WHERE `entry` = -325;
UPDATE `eventai_texts` SET `content_loc2` = 'Il est temps de tout casser!' WHERE `entry` = -324;
UPDATE `eventai_texts` SET `content_loc2` = 'So ju weh siame is fus nehjo skam worl Uptfeel' WHERE `entry` = -323;
UPDATE `eventai_texts` SET `content_loc2` = 'Dim wha Siame cyaa fi so yudo' WHERE `entry` = -322;
UPDATE `eventai_texts` SET `content_loc2` = 'Iman m t\'ief fu Fus\'obeah italaf' WHERE `entry` = -321;
UPDATE `eventai_texts` SET `content_loc2` = 'Les sables vous consomment!' WHERE `entry` = -320;
UPDATE `eventai_texts` SET `content_loc2` = 'Je devrais peut-être recueillir quelques autres agents et les commander suite à ce changement ?' WHERE `entry` = -319;
UPDATE `eventai_texts` SET `content_loc2` = 'La dernière fois que quelqu\'un est allé essayer de recueillir la prime sur Netherlock, il nous est retourné écrasé comme une cape d\'aventurier téméraire!' WHERE `entry` = -318;
UPDATE `eventai_texts` SET `content_loc2` = 'Avec une récompense comme ça, comment pourraient-ils refuser?' WHERE `entry` = -317;
UPDATE `eventai_texts` SET `content_loc2` = 'Si je vois un paysan lâche par ici... je le charge dans une catapulte et je l\'envoie sur le Temple Noir !' WHERE `entry` = -316;
UPDATE `eventai_texts` SET `content_loc2` = 'Quand vous voudrez vous reposer, paysan, le cimetière est juste là...' WHERE `entry` = -315;
UPDATE `eventai_texts` SET `content_loc2` = 'Satanés ogres. Quelqu\'un nous sauvera t\'il de ces sauvages? C\'est le cinquième enlèvement en si peu de jours.' WHERE `entry` = -314;
UPDATE `eventai_texts` SET `content_loc2` = 'Ceci est la meilleure récompense que nous pouvons offrir. Espérons que quelqu\'un acceptera la mission...' WHERE `entry` = -313;
UPDATE `eventai_texts` SET `content_loc2` = 'Comment s\'y prend-il ?' WHERE `entry` = -312;
UPDATE `eventai_texts` SET `content_loc2` = 'VEUILLEZ RE-UTILISER CET ID' WHERE `entry` = -311;
UPDATE `eventai_texts` SET `content_loc2` = 'Je veux être exactement comme ce combattant!' WHERE `entry` = -310;
UPDATE `eventai_texts` SET `content_loc2` = 'Il est tellement bien discipliné!' WHERE `entry` = -309;
UPDATE `eventai_texts` SET `content_loc2` = 'Vaincra-t-il? Le peut-il?' WHERE `entry` = -308;
UPDATE `eventai_texts` SET `content_loc2` = 'Wow! Regardez ces muscles!' WHERE `entry` = -307;
UPDATE `eventai_texts` SET `content_loc2` = 'Priez vos dieux, shaman. Peut-être vous aideront-ils. La Horde par contre, ne le peux pas...' WHERE `entry` = -306;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'avez pas d\'yeux? N\'avez-vous pas vu les démons à nos portes? Je n\'ai pas de soldat à vous passer!' WHERE `entry` = -305;
UPDATE `eventai_texts` SET `content_loc2` = 'Que me voulez-vous, shaman?' WHERE `entry` = -304;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui, nous avons des problèmes. Je crois que c\'est clair comme de l\'eau de roche. La question est : que ferez vous à ce propos?' WHERE `entry` = -303;
UPDATE `eventai_texts` SET `content_loc2` = 'Le chef a mis la tête d\'Arazzius à prix! Et maintenant, ce bon à rien de démon est l\'ennemi numéro un.' WHERE `entry` = -302;
UPDATE `eventai_texts` SET `content_loc2` = 'Mais comment est-ce possible, chef? Je croyais que la malédiction était levée...' WHERE `entry` = -301;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous voulez dire...' WHERE `entry` = -300;
UPDATE `eventai_texts` SET `content_loc2` = 'Quels sortes d\'orcs, chef ?' WHERE `entry` = -299;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai vu des gnomes travailler plus fort que vous, paysan! Des fillettes gnomes - avec des queues de cheva ! BOUGEZ-VOUS!' WHERE `entry` = -298;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre nourriture est prête. Venez la chercher...' WHERE `entry` = -297;
UPDATE `eventai_texts` SET `content_loc2` = 'Et si j\'entend que vous êtes encore allés vous plaindre à Nazgrel, ce sera un de vous dont je m\'occuperai la prochaine fois...' WHERE `entry` = -296;
UPDATE `eventai_texts` SET `content_loc2` = 'Si mon estomac ne menaçait pas de sortir de mon corps et de se sauver pour manger ce que nous donnons aux prisonniers, je pourrai être insulté par cette... nourriture.' WHERE `entry` = -295;
UPDATE `eventai_texts` SET `content_loc2` = 'Est-ce que je détecte un soupçon de cannelle? Ou est-ce de la noix de muscade? Peu importe ce que c\'est, une chose est sûre... personne ne cuisine comme vous!' WHERE `entry` = -294;
UPDATE `eventai_texts` SET `content_loc2` = 'Donc nous y étions - moi et le bataillon, faisant une ronde de routine. Nous avons envoyé les éclaireurs pour vérifier au cas où il y aurait du danger.' WHERE `entry` = -293;
UPDATE `eventai_texts` SET `content_loc2` = 'Certainement, il est revenu en courant, parlant de quelques orcs sur le chemin. Ils ne nous ont pas vu encore donc nous avons pensé d\'aller les rencontrer.' WHERE `entry` = -292;
UPDATE `eventai_texts` SET `content_loc2` = 'Gros bâtards rouges! Plus gros que n\'importe quel orc que j\'ai jamais vu. Des muscles jusqu\'ici...' WHERE `entry` = -291;
UPDATE `eventai_texts` SET `content_loc2` = 'Gangr\'orc...' WHERE `entry` = -290;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'sais pas, *grogne*. Je - ne - sais - juste - pas...' WHERE `entry` = -289;
UPDATE `eventai_texts` SET `content_loc2` = 'Mais ce n\'est pas le pire. Avant d\'avoir pu nous rassembler, un groupe nous a repéré et nous a attaqué.' WHERE `entry` = -288;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai perdu plusieurs de mes meilleurs soldats ce jour là...' WHERE `entry` = -287;
UPDATE `eventai_texts` SET `content_loc2` = 'hoche de la tête' WHERE `entry` = -286;
UPDATE `eventai_texts` SET `content_loc2` = 'Par les Naaru, qu\'il en soit ainsi.' WHERE `entry` = -285;
UPDATE `eventai_texts` SET `content_loc2` = 'Donnez-nous la tolérance pour nos visiteurs elfiques.' WHERE `entry` = -284;
UPDATE `eventai_texts` SET `content_loc2` = 'Continue de bénir ceci, nos anciennes demeures, nous vous supplions.' WHERE `entry` = -283;
UPDATE `eventai_texts` SET `content_loc2` = 'Bénissez et protégez-les. Donnez-leur la victoire contre ceux qui nous veulent du mal...' WHERE `entry` = -282;
UPDATE `eventai_texts` SET `content_loc2` = 'Dans notre guerre contre l\'ombre, nous avons envoyé nos enfants.' WHERE `entry` = -281;
UPDATE `eventai_texts` SET `content_loc2` = 'Lumière que nous embrassons, nous te sollicitons...' WHERE `entry` = -280;
UPDATE `eventai_texts` SET `content_loc2` = 'Mes amis, joignez-moi en prière pour la Lumière.' WHERE `entry` = -279;
UPDATE `eventai_texts` SET `content_loc2` = 'Une noble requête. Ce sera un honneur, Erothem.' WHERE `entry` = -278;
UPDATE `eventai_texts` SET `content_loc2` = 'Bien sûr mon ami. Comment puis-je vous servir?' WHERE `entry` = -277;
UPDATE `eventai_texts` SET `content_loc2` = 'Qu\'il en soit ainsi.' WHERE `entry` = -276;
UPDATE `eventai_texts` SET `content_loc2` = 'Nous venons d\'envoyer un autre équipe sans expérience à Nagrand. Ferez-vous une prière pour eux?' WHERE `entry` = -275;
UPDATE `eventai_texts` SET `content_loc2` = 'Anchorite Nindumen, j\'ai une requête pour vous.' WHERE `entry` = -274;
UPDATE `eventai_texts` SET `content_loc2` = 'Qu\'il en soit ainsi.' WHERE `entry` = -273;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai des muffins ici-même. Venez par ici!' WHERE `entry` = -272;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui, oui, Je suis l\'homme aux muffins. Vous savez pourquoi? Parce que je vends des muffins, voilà pourquoi!' WHERE `entry` = -271;
UPDATE `eventai_texts` SET `content_loc2` = 'Ouais, ça c\'est le bon endroit. Muffins à vendre! Achetez vos muffins frais ici!' WHERE `entry` = -270;
UPDATE `eventai_texts` SET `content_loc2` = 'Rien de telle qu\'une bonne boisson pour faire glisser un de mes magnifiques muffins.' WHERE `entry` = -269;
UPDATE `eventai_texts` SET `content_loc2` = 'Grok fâché si va pas à Blade\'s Edge et parler à Mog\'dorg!' WHERE `entry` = -268;
UPDATE `eventai_texts` SET `content_loc2` = 'VENDEUR DE FRUITS!!! Votre chariot est toujours sur notre chemin! Nous te donnons une heure pour le sortir de notre territoire. Ne teste plus notre patience!' WHERE `entry` = -267;
UPDATE `eventai_texts` SET `content_loc2` = 'Moi faim. Fruits l\'air bons.' WHERE `entry` = -266;
UPDATE `eventai_texts` SET `content_loc2` = 'En peine d\'amour? J\'ai ce qu\'il faut. Vous m\'achetez ce médaillon et le portez au cou... quand l\'amour de ta vie posera les yeux dessus... il te sautera au cou!' WHERE `entry` = -265;
UPDATE `eventai_texts` SET `content_loc2` = 'Je sens que la guerre approche rapidement. Le vendeur de fruits a décidé d\'aider un ogre. Je devrait envisager d\'aider aussi.' WHERE `entry` = -264;
UPDATE `eventai_texts` SET `content_loc2` = 'Quel est le propos des cris de ce pauvre orc? Quelqu\'un devrait aller voir de quoi il s\'agit.' WHERE `entry` = -263;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous paraissez fatigué, $C. J\'ai quelque chose pour vous. Ces amulettes, elles vous aidront à vaincre les obstacles et nager comme si vous étiez né pour ça. Elles énergisent la nourriture que vous mangez... Vos blessures se ferment devant vos yeux!' WHERE `entry` = -262;
UPDATE `eventai_texts` SET `content_loc2` = 'Le clan Bladespire ne combat pas loyalement. Ils ont des Gronn pour les aider. Vous allez à Blade\'s Edge Mountains. Parlez à Mog\'dorg le Sage. Tuez Gromm!' WHERE `entry` = -261;
UPDATE `eventai_texts` SET `content_loc2` = 'Mog\'dorg le Sage dit Grok va à ville, trouve aide. Grok va.' WHERE `entry` = -260;
UPDATE `eventai_texts` SET `content_loc2` = 'Grok a besoin d\'aide! Pourquoi personne aide?' WHERE `entry` = -259;
UPDATE `eventai_texts` SET `content_loc2` = 'Hey! Hey, $R! J\'ai LA chose qu\'il vous faut. Vous avez déjà vu un Tikbalang? Créatures effrayantes. Elles veulent vous enlever. Ce dont vous avez besoin, c\'est ma protection contre les tikbalands. J\'vous garanti de les faire fuir!' WHERE `entry` = -258;
UPDATE `eventai_texts` SET `content_loc2` = 'Regarde par ici, $C! J\'ai quelque chose pour vous. Juste ce dont vous avez besoin. C\'est du savon... et fixé à une corde! Sans offense, mais vous êtes un peu pourri... vous voyez de quoi je parle?' WHERE `entry` = -257;
UPDATE `eventai_texts` SET `content_loc2` = 'Si personne aide. Grok frappe!' WHERE `entry` = -256;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'aurais pu jurer avoir plus de pommes. Grok!' WHERE `entry` = -255;
UPDATE `eventai_texts` SET `content_loc2` = 'Des amulettes incroyables! Les nouveaux joailliers ne savent rien des méthodes mystiques et vérifiées du vieux Griftah! Je t\'améliore avec ces talismans magique pour un prix d\'ami!' WHERE `entry` = -254;
UPDATE `eventai_texts` SET `content_loc2` = 'C\'est dangereux là dedans, non? Tu sais ce dont tu as besoin? De protection. Je peux t\'aider à défier la mort elle-même! Porte ceci autour de ton cou et tu pourras revenir si tu te retrouves dans le royaume des morts!' WHERE `entry` = -253;
UPDATE `eventai_texts` SET `content_loc2` = 'Z\'avez l\'air d\'vous languir. L\'être cher qui délaisse, c\'est ça ? Pas d\'soucis. Vous m\'prenez ce médaillon, vous l\'portez quand vous l\'revoyez, et vous aurez plus une minute à vous, mon grand !' WHERE `entry` = -252;
UPDATE `eventai_texts` SET `content_loc2` = 's\'évanouit' WHERE `entry` = -251;
UPDATE `eventai_texts` SET `content_loc2` = 'Apprendre à lire n\'est pas une tâche aisée. Un toast, hein ?' WHERE `entry` = -250;
UPDATE `eventai_texts` SET `content_loc2` = 'Expédier cela!' WHERE `entry` = -249;
UPDATE `eventai_texts` SET `content_loc2` = 'Grek prend à boire' WHERE `entry` = -247;
UPDATE `eventai_texts` SET `content_loc2` = 'Cette huile n\'est pas bonne pour Grek! À quoi Grek vous ressemble, un certain faible dans des robes ?' WHERE `entry` = -246;
UPDATE `eventai_texts` SET `content_loc2` = 'Grek essai!' WHERE `entry` = -245;
UPDATE `eventai_texts` SET `content_loc2` = 'Quelqu\'un vient lire cette affiche de recherche à Grek. Grek ne sait pas lire.' WHERE `entry` = -244;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous mourrez pour votre orgueil, druide!' WHERE `entry` = -243;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous osez déranger les disciples loyaux du Corbeau?' WHERE `entry` = -242;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous mourrez pour votre orgueil, druide!' WHERE `entry` = -241;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous osez déranger les disciples loyaux du Corbeau?' WHERE `entry` = -240;
UPDATE `eventai_texts` SET `content_loc2` = 'Le temps du Corbeau est la nuit, mais le vôtre finira ici!' WHERE `entry` = -239;
UPDATE `eventai_texts` SET `content_loc2` = 'Imbécile! L\'essence du faucon ne sera jamais la vôtre!' WHERE `entry` = -238;
UPDATE `eventai_texts` SET `content_loc2` = 'à cibler $N.' WHERE `entry` = -237;
UPDATE `eventai_texts` SET `content_loc2` = 'fait voler sa chair en lambeaux en entrant dans une colère surnaturelle!' WHERE `entry` = -235;
UPDATE `eventai_texts` SET `content_loc2` = 'Tellement à faire, tellement à faire! Où le temps va-t-il?' WHERE `entry` = -233;
UPDATE `eventai_texts` SET `content_loc2` = 'La Fraternité ne sera pas gênée par des insectes.' WHERE `entry` = -232;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vous couperai!' WHERE `entry` = -231;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous serez mort bientôt!' WHERE `entry` = -230;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre mise à mort est facile.' WHERE `entry` = -229;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vais vous transformer en mojo!' WHERE `entry` = -228;
UPDATE `eventai_texts` SET `content_loc2` = 'La terre et le ciel brûleront!' WHERE `entry` = -227;
UPDATE `eventai_texts` SET `content_loc2` = 'Beaux rêves...' WHERE `entry` = -225;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous semblez fatigué...' WHERE `entry` = -224;
UPDATE `eventai_texts` SET `content_loc2` = 'Peste sur vous!' WHERE `entry` = -223;
UPDATE `eventai_texts` SET `content_loc2` = 'L\'essaim désire s\'alimenter!' WHERE `entry` = -222;
UPDATE `eventai_texts` SET `content_loc2` = 'L\'horloge... tourne... toujours.' WHERE `entry` = -221;
UPDATE `eventai_texts` SET `content_loc2` = 'Pitié, pas le temps de vous accorder une mort lente!' WHERE `entry` = -220;
UPDATE `eventai_texts` SET `content_loc2` = 'Vos espoirs sont perdus!' WHERE `entry` = -218;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous êtes les défenseurs d\'un monde condamné! Fuyez d\'ici et peut-être vous prolongerez vos vies pathétiques!' WHERE `entry` = -217;
UPDATE `eventai_texts` SET `content_loc2` = 'Tous vos efforts ont été en vain, le drainage de l\'Arbre Mondial a déjà commencé! Bientôt, le coeur de votre monde ne battra plus!' WHERE `entry` = -216;
UPDATE `eventai_texts` SET `content_loc2` = 'Détruit!' WHERE `entry` = -215;
UPDATE `eventai_texts` SET `content_loc2` = 'Tue!' WHERE `entry` = -214;
UPDATE `eventai_texts` SET `content_loc2` = 'Ecrase!' WHERE `entry` = -213;
UPDATE `eventai_texts` SET `content_loc2` = 'Que la lumière soit avec vous' WHERE `entry` = -212;
UPDATE `eventai_texts` SET `content_loc2` = 'Mourez au nom d\'Edwin Cleef!' WHERE `entry` = -211;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vais vous envoyer dans votre tombe, faible $C!' WHERE `entry` = -210;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai un message spécial pour $N. Et il dit que vous devez mourir!' WHERE `entry` = -209;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n’auriez pas une ou deux pièces ?' WHERE `entry` = -208;
UPDATE `eventai_texts` SET `content_loc2` = 'Un coup de main à un pauvre malheureux ?' WHERE `entry` = -207;
UPDATE `eventai_texts` SET `content_loc2` = 'Je ferai reluire votre armure pour une simple pièce de cuivre.' WHERE `entry` = -206;
UPDATE `eventai_texts` SET `content_loc2` = 'Pain frais, tout juste sorti du four !' WHERE `entry` = -205;
UPDATE `eventai_texts` SET `content_loc2` = 'Pain frais !' WHERE `entry` = -204;
UPDATE `eventai_texts` SET `content_loc2` = 'Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE `entry` = -203;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre tête fera un trophée parfait , $R.' WHERE `entry` = -202;
UPDATE `eventai_texts` SET `content_loc2` = 'Mes serres déchiquetteront votre corps chétif, $R.' WHERE `entry` = -201;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous serez une proie facile, $C.' WHERE `entry` = -200;
UPDATE `eventai_texts` SET `content_loc2` = 'Souffrez insecte méprisable!' WHERE `entry` = -199;
UPDATE `eventai_texts` SET `content_loc2` = 'Mon seigneur sera la fin de vous tous..' WHERE `entry` = -198;
UPDATE `eventai_texts` SET `content_loc2` = 'Vos jours sont comptés!' WHERE `entry` = -196;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre temps s\'épuise!' WHERE `entry` = -195;
UPDATE `eventai_texts` SET `content_loc2` = 'Le Seigneur Sombre rit de vous!' WHERE `entry` = -194;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'êtes rien, je réponds à un plus haut appel!' WHERE `entry` = -193;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous avez fait face à beaucoup de défis. Bientôt votre peuple s\'agenouillera devant mon seigneur!' WHERE `entry` = -192;
UPDATE `eventai_texts` SET `content_loc2` = '... et reste mort! Il a été servi!' WHERE `entry` = -191;
UPDATE `eventai_texts` SET `content_loc2` = 'Explosions! PLUS d\'explosions! Je dois avoir plus d\'explosions!' WHERE `entry` = -190;
UPDATE `eventai_texts` SET `content_loc2` = 'Mes machines sont l\'avenir! Elles vous détruiront tous!' WHERE `entry` = -189;
UPDATE `eventai_texts` SET `content_loc2` = 'USURPATEURS!!! GNOMEREGAN EST MIEN!!!' WHERE `entry` = -188;
UPDATE `eventai_texts` SET `content_loc2` = 'appelle son worgs!' WHERE `entry` = -187;
UPDATE `eventai_texts` SET `content_loc2` = 'La vie est ici!' WHERE `entry` = -186;
UPDATE `eventai_texts` SET `content_loc2` = 'Avouez et nous vous libérerons.' WHERE `entry` = -185;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous parlerez finalement. Vous pourriez aussi le renverser maintenant.' WHERE `entry` = -184;
UPDATE `eventai_texts` SET `content_loc2` = 'Que? Oh non. Je ne me soucie pas de ce que vous devez dire. J\'apprécie juste d\'infliger la douleur.' WHERE `entry` = -183;
UPDATE `eventai_texts` SET `content_loc2` = 'Le mien! Le mien! Le mien! Gizlock est la règle de ce domaine! Vous ne révélerez jamais ma présence!' WHERE `entry` = -182;
UPDATE `eventai_texts` SET `content_loc2` = 'Nous sommes la vraie Horde!' WHERE `entry` = -181;
UPDATE `eventai_texts` SET `content_loc2` = 'Mes animaux de compagnie ont faim et ils dîneront sur votre chair!' WHERE `entry` = -180;
UPDATE `eventai_texts` SET `content_loc2` = 'Retenez-les pendant que je libère les chiens de meute de guerre!' WHERE `entry` = -179;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vais porter votre peau comme une veste de smoking!' WHERE `entry` = -177;
UPDATE `eventai_texts` SET `content_loc2` = 'Dugh, maintenant vous me mettez en colère!' WHERE `entry` = -176;
UPDATE `eventai_texts` SET `content_loc2` = 'Les amoureux de votre terre sont très tenaces donc j\'ai réfléchi! Je devrai improviser.' WHERE `entry` = -175;
UPDATE `eventai_texts` SET `content_loc2` = 'Nous sommes attaqués! Repoussez les envahisseurs!' WHERE `entry` = -174;
UPDATE `eventai_texts` SET `content_loc2` = 'La Confrérie prévaudra!' WHERE `entry` = -173;
UPDATE `eventai_texts` SET `content_loc2` = 'Imbéciles! Notre cause est juste!' WHERE `entry` = -172;
UPDATE `eventai_texts` SET `content_loc2` = 'Bande de chiens que vous êtes!' WHERE `entry` = -171;
UPDATE `eventai_texts` SET `content_loc2` = 'et reste à terre!' WHERE `entry` = -170;
UPDATE `eventai_texts` SET `content_loc2` = 'Personne ne peut défier la Confrérie!' WHERE `entry` = -169;
UPDATE `eventai_texts` SET `content_loc2` = 'Oh avancez-vous! Ne les laisse pas se battre!' WHERE `entry` = -168;
UPDATE `eventai_texts` SET `content_loc2` = 'A quoi sert cette violence? Ce qui est fait est fait. J\'ai failli pour mon peuple.' WHERE `entry` = -167;
UPDATE `eventai_texts` SET `content_loc2` = 'Shaza-Kiel!' WHERE `entry` = -166;
UPDATE `eventai_texts` SET `content_loc2` = 'Misérable nuisance!' WHERE `entry` = -165;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous ... n\'êtes rien!' WHERE `entry` = -164;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous... êtes marqué.' WHERE `entry` = -163;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre mort sera très douloureuse.' WHERE `entry` = -162;
UPDATE `eventai_texts` SET `content_loc2` = 'Pleurez pour de la pitié! Vos vies vides dénuées de sens vont bientôt être confisquées.' WHERE `entry` = -161;
UPDATE `eventai_texts` SET `content_loc2` = 'Ce monde est le NÔTRE!' WHERE `entry` = -160;
UPDATE `eventai_texts` SET `content_loc2` = 'Lok\'tar Illidari!' WHERE `entry` = -159;
UPDATE `eventai_texts` SET `content_loc2` = 'Pour Kargath! Pour la Victoire!' WHERE `entry` = -158;
UPDATE `eventai_texts` SET `content_loc2` = 'Lok Narash!' WHERE `entry` = -157;
UPDATE `eventai_texts` SET `content_loc2` = 'Le sang est notre pouvoir!' WHERE `entry` = -156;
UPDATE `eventai_texts` SET `content_loc2` = 'commence à armer la Bombe de Proximité!' WHERE `entry` = -155;
UPDATE `eventai_texts` SET `content_loc2` = 'Illidan règnes!' WHERE `entry` = -154;
UPDATE `eventai_texts` SET `content_loc2` = 's\'affaiblit!' WHERE `entry` = -153;
UPDATE `eventai_texts` SET `content_loc2` = 'grandit en observant $N!' WHERE `entry` = -152;
UPDATE `eventai_texts` SET `content_loc2` = 'devient furieux!' WHERE `entry` = -151;
UPDATE `eventai_texts` SET `content_loc2` = 'commence à jeter un soin massif!' WHERE `entry` = -150;
UPDATE `eventai_texts` SET `content_loc2` = 'entre dans une frénésie!' WHERE `entry` = -149;
UPDATE `eventai_texts` SET `content_loc2` = 'Woot! Merci!' WHERE `entry` = -148;
UPDATE `eventai_texts` SET `content_loc2` = 'Craignez-vous la mort?' WHERE `entry` = -147;
UPDATE `eventai_texts` SET `content_loc2` = 'C\'est la partie que je préfère.' WHERE `entry` = -146;
UPDATE `eventai_texts` SET `content_loc2` = 'Ne soyez pas présomptueux... mortel!' WHERE `entry` = -145;
UPDATE `eventai_texts` SET `content_loc2` = 'Finalement! Quelque chose pour briser la monotonie!' WHERE `entry` = -144;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vous casserai!' WHERE `entry` = -143;
UPDATE `eventai_texts` SET `content_loc2` = 'Mortels pitoyables! Vous allez le payer très cher.' WHERE `entry` = -142;
UPDATE `eventai_texts` SET `content_loc2` = 'Envahisseurs! Sonnez l\'alarme!' WHERE `entry` = -141;
UPDATE `eventai_texts` SET `content_loc2` = 'Les rouleaux de la mort... Vous écraserons.' WHERE `entry` = -140;
UPDATE `eventai_texts` SET `content_loc2` = 'Venez me rejoindre bruddahs!' WHERE `entry` = -139;
UPDATE `eventai_texts` SET `content_loc2` = 'Tout ce que vous faites c\'est me faire perdre mon temps!' WHERE `entry` = -138;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'avez rien!' WHERE `entry` = -137;
UPDATE `eventai_texts` SET `content_loc2` = 'Arrêtez de pleurer!' WHERE `entry` = -136;
UPDATE `eventai_texts` SET `content_loc2` = 'Nourriture, moi bruddahs!' WHERE `entry` = -135;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous ne pouvez pas... tuer... mon esprit' WHERE `entry` = -134;
UPDATE `eventai_texts` SET `content_loc2` = 'Je suis le prédateur! Vous êtes la proie...' WHERE `entry` = -133;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous avez gagné cette bataille, mais pas... la guerre...' WHERE `entry` = -132;
UPDATE `eventai_texts` SET `content_loc2` = 'Victoire à la Légion!' WHERE `entry` = -131;
UPDATE `eventai_texts` SET `content_loc2` = 'Toute la vie doit périr!' WHERE `entry` = -130;
UPDATE `eventai_texts` SET `content_loc2` = 'Des cendres aux cendres, de la poussière à la poussière' WHERE `entry` = -129;
UPDATE `eventai_texts` SET `content_loc2` = 'Effondrez-vous et pourrissez!' WHERE `entry` = -128;
UPDATE `eventai_texts` SET `content_loc2` = 'Ce sera beaucoup plus froid dans votre tombe' WHERE `entry` = -127;
UPDATE `eventai_texts` SET `content_loc2` = 'Succombez au froid glacial... de la mort!' WHERE `entry` = -126;
UPDATE `eventai_texts` SET `content_loc2` = 'La conquête finale de la Légion a commencé! De nouveau l\'assujettissement de ce monde est à notre portée. Ne laissez personne survivre!' WHERE `entry` = -125;
UPDATE `eventai_texts` SET `content_loc2` = 'Insolence!' WHERE `entry` = -124;
UPDATE `eventai_texts` SET `content_loc2` = 'Je suis le roi serpent! Je peux faire n\'importe quoi.' WHERE `entry` = -123;
UPDATE `eventai_texts` SET `content_loc2` = 'Personne ne va vous sauver!' WHERE `entry` = -122;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre temps est presque... écoulé' WHERE `entry` = -121;
UPDATE `eventai_texts` SET `content_loc2` = 'Ne combattez pas contre lui' WHERE `entry` = -120;
UPDATE `eventai_texts` SET `content_loc2` = 'Juste un avant-goût... de ce qui vous attend.' WHERE `entry` = -119;
UPDATE `eventai_texts` SET `content_loc2` = 'Reesh, hokta!' WHERE `entry` = -118;
UPDATE `eventai_texts` SET `content_loc2` = 'Abandonnez tout espoir ! La légion est revenue pour finir ce qui a été commencé il y a tant d\\\'années. Cette fois il n\\\'y aura aucune échappatoire !' WHERE `entry` = -117;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous ne réveillerez jamais le rêveur!' WHERE `entry` = -99;
UPDATE `eventai_texts` SET `content_loc2` = 'Je... le mérite.' WHERE `entry` = -98;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'auriez pas du venir.' WHERE `entry` = -97;
UPDATE `eventai_texts` SET `content_loc2` = 'Ca devait être fait.' WHERE `entry` = -96;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous l\'avez apporté sur vous.' WHERE `entry` = -95;
UPDATE `eventai_texts` SET `content_loc2` = 'Ne m\'obligez pas à vous tuer!' WHERE `entry` = -94;
UPDATE `eventai_texts` SET `content_loc2` = 'Le travail doit continuer.' WHERE `entry` = -93;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous ne direz pas que je ne vous ai pas averti!' WHERE `entry` = -92;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous pensez que vous pouvez me blesser, heuh? Pensez-vous que j\'ai peur de vous?' WHERE `entry` = -91;
UPDATE `eventai_texts` SET `content_loc2` = 'Allez en avant, donnez-moi votre meilleur tir. Je peux le prendre!' WHERE `entry` = -90;
UPDATE `eventai_texts` SET `content_loc2` = 'Voyou!' WHERE `entry` = -89;
UPDATE `eventai_texts` SET `content_loc2` = 'Sacrebleu, je suis bon!' WHERE `entry` = -88;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous devriez fendre tant que vous pouvez.' WHERE `entry` = -87;
UPDATE `eventai_texts` SET `content_loc2` = 'Je prévois une mort douloureuse.' WHERE `entry` = -86;
UPDATE `eventai_texts` SET `content_loc2` = 'Si mon calcul est correct, vous devriez bien être mort.' WHERE `entry` = -85;
UPDATE `eventai_texts` SET `content_loc2` = 'Mesurer deux fois, couper une fois !' WHERE `entry` = -84;
UPDATE `eventai_texts` SET `content_loc2` = 'Une éventualité... imprévue.' WHERE `entry` = -83;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui, la seule issue logique.' WHERE `entry` = -82;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre strategie était imparfaite.' WHERE `entry` = -81;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vous taillerai en pièces!' WHERE `entry` = -80;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui, la seule issue logique.' WHERE `entry` = -79;
UPDATE `eventai_texts` SET `content_loc2` = 'Ahh... Exactement ce que j\'attendais.' WHERE `entry` = -78;
UPDATE `eventai_texts` SET `content_loc2` = 'Ahh... C\'est beaucoup mieux.' WHERE `entry` = -77;
UPDATE `eventai_texts` SET `content_loc2` = 'Maintenant je suis vraiment... en colère...' WHERE `entry` = -76;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous avez choisi le mauvais adversaire.' WHERE `entry` = -75;
UPDATE `eventai_texts` SET `content_loc2` = 'Complètement inefficace. Exactement comme quelqu\'un d\'autre que je connais.' WHERE `entry` = -74;
UPDATE `eventai_texts` SET `content_loc2` = 'Il est imprudent de me mettre en colère.' WHERE `entry` = -73;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous allez réussir à vous damner vous même!' WHERE `entry` = -72;
UPDATE `eventai_texts` SET `content_loc2` = 'Partez tant qu\'il est encore temps!' WHERE `entry` = -71;
UPDATE `eventai_texts` SET `content_loc2` = 'Cela... ne changera rien. La damnation éternelle vous attend!' WHERE `entry` = -70;
UPDATE `eventai_texts` SET `content_loc2` = 'D\'autres prendront ma place!' WHERE `entry` = -69;
UPDATE `eventai_texts` SET `content_loc2` = 'Le même sort attend tous ceux qui veulent voler le maître' WHERE `entry` = -68;
UPDATE `eventai_texts` SET `content_loc2` = 'La mort est bien trop miséricordieuse à votre goût.' WHERE `entry` = -67;
UPDATE `eventai_texts` SET `content_loc2` = 'Il est temps de partir...' WHERE `entry` = -66;
UPDATE `eventai_texts` SET `content_loc2` = 'Libre... au moins' WHERE `entry` = -65;
UPDATE `eventai_texts` SET `content_loc2` = 'Est-ce vraiment passé?' WHERE `entry` = -64;
UPDATE `eventai_texts` SET `content_loc2` = 'C\'est tout... revenez me voir.' WHERE `entry` = -63;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui... Je crois que je me rappelle maintenant...' WHERE `entry` = -62;
UPDATE `eventai_texts` SET `content_loc2` = 'J\'ai loupé le spectacle!' WHERE `entry` = -61;
UPDATE `eventai_texts` SET `content_loc2` = 'Ils se sont endormis après. Moi, je me suis endormi pendant....' WHERE `entry` = -60;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui... Je crois que je me rappelle maintenant...' WHERE `entry` = -59;
UPDATE `eventai_texts` SET `content_loc2` = 'Il a demandé si l\'imp pouvait nous rejoindre... vous le croyez ? Généralement, ce n\'est pas plus mal...' WHERE `entry` = -58;
UPDATE `eventai_texts` SET `content_loc2` = 'Et j\'ai dis, "Ok, mais cela vous coûtera un supplément."' WHERE `entry` = -57;
UPDATE `eventai_texts` SET `content_loc2` = 'Cinq secondes! Je ne plaisante pas!' WHERE `entry` = -56;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous serez puni!' WHERE `entry` = -55;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous... allez... payer...' WHERE `entry` = -54;
UPDATE `eventai_texts` SET `content_loc2` = 'Que se passe-t-il?' WHERE `entry` = -53;
UPDATE `eventai_texts` SET `content_loc2` = 'Où suis-je? Quoi?' WHERE `entry` = -52;
UPDATE `eventai_texts` SET `content_loc2` = 'Le destin s\'est retourné contre moi!' WHERE `entry` = -51;
UPDATE `eventai_texts` SET `content_loc2` = 'Ce n\'est... pas juste...' WHERE `entry` = -50;
UPDATE `eventai_texts` SET `content_loc2` = 'Attendez... non! Non!' WHERE `entry` = -49;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous êtes repéré par l\'oeil de Grillok!' WHERE `entry` = -48;
UPDATE `eventai_texts` SET `content_loc2` = 'essaie de s\'enfuire dans un moment de panique!' WHERE `entry` = -47;
UPDATE `eventai_texts` SET `content_loc2` = 'devient furieux!' WHERE `entry` = -46;
UPDATE `eventai_texts` SET `content_loc2` = 'Le maître... sera en colère...' WHERE `entry` = -45;
UPDATE `eventai_texts` SET `content_loc2` = 'Je suis fini!' WHERE `entry` = -44;
UPDATE `eventai_texts` SET `content_loc2` = 'Non!' WHERE `entry` = -43;
UPDATE `eventai_texts` SET `content_loc2` = 'VEUILLEZ REUTILISER CET ID' WHERE `entry` = -42;
UPDATE `eventai_texts` SET `content_loc2` = 'Que vont devenir...' WHERE `entry` = -41;
UPDATE `eventai_texts` SET `content_loc2` = 'Est-ce la fin?' WHERE `entry` = -40;
UPDATE `eventai_texts` SET `content_loc2` = 'Gardes! Venez et tuez ces intrus!' WHERE `entry` = -39;
UPDATE `eventai_texts` SET `content_loc2` = 'Band\'or shorel\'aran!' WHERE `entry` = -38;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'êtes plus en rapport avec certains exécutants.' WHERE `entry` = -37;
UPDATE `eventai_texts` SET `content_loc2` = 'Je n\'ai pas encore... commencé...' WHERE `entry` = -36;
UPDATE `eventai_texts` SET `content_loc2` = 'Cessez vos jérémiades' WHERE `entry` = -35;
UPDATE `eventai_texts` SET `content_loc2` = 'Avancez! Je verrez si vous êtes correctement accueilli.' WHERE `entry` = -34;
UPDATE `eventai_texts` SET `content_loc2` = 'Le vide... attire' WHERE `entry` = -33;
UPDATE `eventai_texts` SET `content_loc2` = 'Plus... de... vie' WHERE `entry` = -32;
UPDATE `eventai_texts` SET `content_loc2` = 'Ce navire... est vide.' WHERE `entry` = -31;
UPDATE `eventai_texts` SET `content_loc2` = 'L\'ombre... va s\'abattre sur vous' WHERE `entry` = -30;
UPDATE `eventai_texts` SET `content_loc2` = 'Energie vitale... à consumer' WHERE `entry` = -29;
UPDATE `eventai_texts` SET `content_loc2` = 'Etes-vous venu pour tuer Dalliah? Puis-je regarder?' WHERE `entry` = -28;
UPDATE `eventai_texts` SET `content_loc2` = 'Enfin, une cible pour mes frustrations!' WHERE `entry` = -27;
UPDATE `eventai_texts` SET `content_loc2` = 'Oui, c\'était plutôt satisfaisant' WHERE `entry` = -26;
UPDATE `eventai_texts` SET `content_loc2` = 'Su que c\'était... Le seul moyen de sortir' WHERE `entry` = -25;
UPDATE `eventai_texts` SET `content_loc2` = 'Défendez-vous, pour tout le bien que cela fera...' WHERE `entry` = -24;
UPDATE `eventai_texts` SET `content_loc2` = 'En garde!' WHERE `entry` = -23;
UPDATE `eventai_texts` SET `content_loc2` = 'VanCleef paye cher pour vos têtes!' WHERE `entry` = -22;
UPDATE `eventai_texts` SET `content_loc2` = 'Ces spécimens... doivent être... préservés' WHERE `entry` = -21;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre cycle de vie est maintenant terminé!' WHERE `entry` = -20;
UPDATE `eventai_texts` SET `content_loc2` = 'Endorel aluminor!' WHERE `entry` = -19;
UPDATE `eventai_texts` SET `content_loc2` = 'La nature se plie à ma volonté!' WHERE `entry` = -18;
UPDATE `eventai_texts` SET `content_loc2` = 'Que faites-vous? Ces spécimens sont particulièrement fragiles!' WHERE `entry` = -17;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous n\'irez pas loin...' WHERE `entry` = -16;
UPDATE `eventai_texts` SET `content_loc2` = 'Je déteste répéter ce que j\'ai déjà dis...' WHERE `entry` = -15;
UPDATE `eventai_texts` SET `content_loc2` = 'Votre vie sera mienne!' WHERE `entry` = -14;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous recherchez une récompense, hein! Que diriez vous de la mort?' WHERE `entry` = -13;
UPDATE `eventai_texts` SET `content_loc2` = 'Je me reconnais dans votre douleur!' WHERE `entry` = -12;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vais vous incinérer!' WHERE `entry` = -11;
UPDATE `eventai_texts` SET `content_loc2` = 'Criez pendant que vous brulez!' WHERE `entry` = -10;
UPDATE `eventai_texts` SET `content_loc2` = 'Quelle est cette aggravation? Vous allez mourir!' WHERE `entry` = -9;
UPDATE `eventai_texts` SET `content_loc2` = 'Yiieeeee! Moi courir!' WHERE `entry` = -8;
UPDATE `eventai_texts` SET `content_loc2` = 'Vous pas prendre bougie!' WHERE `entry` = -7;
UPDATE `eventai_texts` SET `content_loc2` = 'Grrrr... viande fraîche!' WHERE `entry` = -6;
UPDATE `eventai_texts` SET `content_loc2` = 'Plus d\'os à ronger...' WHERE `entry` = -5;
UPDATE `eventai_texts` SET `content_loc2` = 'Sentez le pouvoir de la confrérie!' WHERE `entry` = -4;
UPDATE `eventai_texts` SET `content_loc2` = 'Ah, une chance d\'utiliser cette lame fraîchement aiguisée.' WHERE `entry` = -3;
UPDATE `eventai_texts` SET `content_loc2` = 'La confrérie ne tolèrera pas vos actions.' WHERE `entry` = -2;
UPDATE `eventai_texts` SET `content_loc2` = 'Je vois que ces imbéciles de l\'Abbaye ont envoyé de la viande fraîche pour nous.' WHERE `entry` = -1;
