SET NAMES utf8;

UPDATE `game_event` SET `description` = 'Solstice d\'été : la fête du Feu' WHERE `entry` = 1;
UPDATE `game_event` SET `description` = 'La fête du Voile d\'hiver' WHERE `entry` = 2;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Forêt de Terrokar)' WHERE `entry` = 3;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Elwynn)' WHERE `entry` = 4;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Mulgore)' WHERE `entry` = 5;
UPDATE `game_event` SET `description` = 'Le nouvel an' WHERE `entry` = 6;
UPDATE `game_event` SET `description` = 'La fête lunaire' WHERE `entry` = 7;
UPDATE `game_event` SET `description` = 'De l\'amour dans l\'air' WHERE `entry` = 8;
UPDATE `game_event` SET `description` = 'Le jardin des nobles' WHERE `entry` = 9;
UPDATE `game_event` SET `description` = 'La semaine des enfants' WHERE `entry` = 10;
UPDATE `game_event` SET `description` = 'La fête des moissons' WHERE `entry` = 11;
UPDATE `game_event` SET `description` = 'La Sanssaint' WHERE `entry` = 12;
UPDATE `game_event` SET `description` = 'Invasions d\'élémentaux' WHERE `entry` = 13;
UPDATE `game_event` SET `description` = 'Annonce du concours de pêche de Strangleronce' WHERE `entry` = 14;
UPDATE `game_event` SET `description` = 'Concours de pêche de Strangleronce' WHERE `entry` = 15;
UPDATE `game_event` SET `description` = 'Le coffre pirate de Gurubashi' WHERE `entry` = 16;
UPDATE `game_event` SET `description` = 'L\'invasion du fléau' WHERE `entry` = 17;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : vallée d\'Alterac !' WHERE `entry` = 18;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : goulet des Chanteguerres !' WHERE `entry` = 19;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : bassin d\'Arathi !' WHERE `entry` = 20;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : l\'Œil du cyclone !' WHERE `entry` = 21;
UPDATE `game_event` SET `description` = 'L\'effort de guerre d\'Ahn Qiraj' WHERE `entry` = 22;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Elwynn)' WHERE `entry` = 23;
UPDATE `game_event` SET `description` = 'L\'Appel des armes' WHERE `entry` = 25;
UPDATE `game_event` SET `description` = 'La fête des Brasseurs' WHERE `entry` = 26;
UPDATE `game_event` SET `description` = 'Nuit' WHERE `entry` = 27;
UPDATE `game_event` SET `description` = 'Le jardin des nobles' WHERE `entry` = 28;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Gri\'lek' WHERE `entry` = 29;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Hazza\'rah' WHERE `entry` = 30;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Renataki' WHERE `entry` = 31;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Wushoolay' WHERE `entry` = 32;
UPDATE `game_event` SET `description` = 'Tournoi de l\'arène' WHERE `entry` = 33;
UPDATE `game_event` SET `description` = 'Concert des L70ETC' WHERE `entry` = 34;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 1 - La prise du Sanctum des Confins du Soleil' WHERE `entry` = 35;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 1 - La prise du Sanctum des Confins du Soleil COMPLETE' WHERE `entry` = 36;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 2 - La prise de l\'armurerie des Confins du Soleil' WHERE `entry` = 37;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 2 - La prise de l\'armurerie des Confins du Soleil COMPLETE' WHERE `entry` = 38;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 2b - Activation du portail pour Quel\'danas' WHERE `entry` = 39;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 2b - Activation du portail pour Quel\'anas COMPLETE' WHERE `entry` = 40;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 3 - La prise du Port des Confins du Soleil' WHERE `entry` = 41;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 3 - La prise du Port des Confins du Soleil COMPLETE' WHERE `entry` = 42;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 3b - Reconstruction de l\'Enclume et de la Forge' WHERE `entry` = 43;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 3b - Reconstruction de l\'Enclume et de la Forge COMPLETE' WHERE `entry` = 44;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 4a - Création du Laboratoire d\'alchimie' WHERE `entry` = 45;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 4a - Création du Laboratoire d\'alchimie COMPLETE' WHERE `entry` = 46;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 4b - Construction du Monument aux Déchus' WHERE `entry` = 47;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 4b - Construction du Monument aux Déchus COMPLETE' WHERE `entry` = 48;
UPDATE `game_event` SET `description` = 'Opération Soleil brisé: Phase 4 - COMPLETE' WHERE `entry` = 49;
